// This file provides a client with methods as well as functions to interact with the HTTP API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package auth

import (
	"context"
	"encoding/base64"
	"encoding/json/v2"
	"errors"
	"net/http"
	"net/url"
	"os"
	"strings"

	"github.com/go-api-libs/api"
)

const defaultUserAgent = "API"

var defaultBaseURL = &url.URL{
	Scheme: "https",
	Host:   "api.example.com",
	Path:   "/",
}

// Client is an HTTP client for the auth API.
type Client struct {
	// The HTTP client to use for requests.
	cli *http.Client
	// The bearer token
	bearer string
	// The basic auth header
	basic string
	// On every path too: a client field, read from the environment.
	apiKey string
	// On every path, so a client field; it has no example, so its value comes from the recordings.
	client string
	// The base URL
	baseURL *url.URL
	// The user agent
	userAgent string
}

// ClientOption configures a [Client].
type ClientOption func(*Client)

// WithBaseURL returns a [ClientOption] that overrides the default base URL.
// It will prefix a leading slash to the path if there is none.
func WithBaseURL(baseURL *url.URL) ClientOption {
	if !strings.HasPrefix(baseURL.Path, "/") {
		baseURL.Path = "/" + baseURL.Path
	}

	return func(c *Client) { c.baseURL = baseURL }
}

// WithHTTPClient returns a [ClientOption] that sets a custom HTTP client.
//
// To mock the client in tests, pass one whose Transport is cassette.Replay(interactions), from
// github.com/MarkRosemaker/openapi-enrich/cassette: it answers each request from the recorded interaction it matches,
// and fails any other, without the network.
func WithHTTPClient(cli *http.Client) ClientOption {
	return func(c *Client) { c.cli = cli }
}

// WithBearer returns a [ClientOption] that sets a custom bearer.
func WithBearer(bearer string) ClientOption {
	return func(c *Client) {
		if bearer != "" {
			c.bearer = "Bearer " + strings.TrimPrefix(bearer, "Bearer ")
		}
	}
}

// WithBasic returns a [ClientOption] that sets a custom basic auth username and password.
func WithBasic(username, password string) ClientOption {
	return func(c *Client) {
		if username != "" || password != "" {
			c.basic = "Basic " + base64.StdEncoding.EncodeToString([]byte(username+":"+password))
		}
	}
}

// WithAPIKey returns a [ClientOption] that sets a custom API key.
func WithAPIKey(apiKey string) ClientOption {
	return func(c *Client) { c.apiKey = apiKey }
}

// WithClient returns a [ClientOption] that sets a custom client parameter.
func WithClient(client string) ClientOption {
	return func(c *Client) { c.client = client }
}

// NewClient creates a new Client, reading the bearer token from [os.Getenv]("API_TOKEN"), reading the basic auth username and password from [os.Getenv]("API_USERNAME") and [os.Getenv]("API_PASSWORD").
func NewClient(opts ...ClientOption) (*Client, error) {
	c := &Client{
		cli:       http.DefaultClient,
		baseURL:   defaultBaseURL,
		client:    "golden-test",
		userAgent: defaultUserAgent,
	}

	WithBearer(os.Getenv("API_TOKEN"))(c)

	WithBasic(os.Getenv("API_USERNAME"), os.Getenv("API_PASSWORD"))(c)

	c.apiKey = os.Getenv("API_KEY")

	for _, opt := range opts {
		opt(c)
	}

	if c.bearer == "" && c.basic == "" {
		return nil, errors.New("neither bearer token API_TOKEN nor basic auth API_USERNAME / API_PASSWORD provided")
	}

	if c.apiKey == "" {
		return nil, errors.New("api key API_KEY not provided")
	}

	if c.client == "" {
		return nil, errors.New("client parameter not provided")
	}

	return c, nil
}

// Requires the token.
//
//	GET /items
func (c *Client) ListItems(ctx context.Context) ([]string, error) {
	out, err := c.ListItemsWithResult[[]string](ctx)
	if err != nil {
		return nil, err
	}

	return *out, nil
}

// Requires the token.
// You can define a custom result to unmarshal the response into.
//
//	GET /items
func (c *Client) ListItemsWithResult[R any](ctx context.Context) (*R, error) {
	if c.bearer == "" {
		return nil, errors.New("bearer token API_TOKEN not provided")
	}

	u := c.baseURL.JoinPath("items")
	req := (&http.Request{
		Header: http.Header{
			"Authorization": []string{c.bearer},
			"X-Api-Key":     []string{c.apiKey},
			"X-Client":      []string{c.client},
			"User-Agent":    []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// ok
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R

			// a type of the caller's own declares only what it needs of the response, so it is decoded leniently
			opts := jsonOptsLenient
			if _, ok := any(&out).(*[]string); ok {
				opts = jsonOpts
			}

			if err := json.UnmarshalRead(rsp.Body, &out, opts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Takes the token if there is one.
//
//	GET /feed
func (c *Client) GetFeed(ctx context.Context) ([]string, error) {
	out, err := c.GetFeedWithResult[[]string](ctx)
	if err != nil {
		return nil, err
	}

	return *out, nil
}

// Takes the token if there is one.
// You can define a custom result to unmarshal the response into.
//
//	GET /feed
func (c *Client) GetFeedWithResult[R any](ctx context.Context) (*R, error) {
	if c.bearer == "" {
		return nil, errors.New("bearer token API_TOKEN not provided")
	}

	u := c.baseURL.JoinPath("feed")
	req := (&http.Request{
		Header: http.Header{
			"Authorization": []string{c.bearer},
			"X-Api-Key":     []string{c.apiKey},
			"X-Client":      []string{c.client},
			"User-Agent":    []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// ok
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R

			// a type of the caller's own declares only what it needs of the response, so it is decoded leniently
			opts := jsonOptsLenient
			if _, ok := any(&out).(*[]string); ok {
				opts = jsonOpts
			}

			if err := json.UnmarshalRead(rsp.Body, &out, opts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Takes a username and password instead.
//
//	GET /admin
func (c *Client) GetAdmin(ctx context.Context) error {
	if c.basic == "" {
		return errors.New("basic auth API_USERNAME / API_PASSWORD not provided")
	}

	u := c.baseURL.JoinPath("admin")
	req := (&http.Request{
		Header: http.Header{
			"Authorization": []string{c.basic},
			"X-Api-Key":     []string{c.apiKey},
			"X-Client":      []string{c.client},
			"User-Agent":    []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusNoContent:
		// ok
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "":

			return nil
		default:
			return api.NewErrUnknownContentType(rsp)
		}
	default:
		return api.NewErrUnknownStatusCode(rsp)
	}
}

// Never takes the token.
//
//	GET /health
func (c *Client) Health(ctx context.Context) error {
	u := c.baseURL.JoinPath("health")
	req := (&http.Request{
		Header: http.Header{
			"X-Api-Key":  []string{c.apiKey},
			"X-Client":   []string{c.client},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusNoContent:
		// ok
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "":

			return nil
		default:
			return api.NewErrUnknownContentType(rsp)
		}
	default:
		return api.NewErrUnknownStatusCode(rsp)
	}
}
