// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package things

import (
	"context"
	"encoding/json/v2"
	"errors"
	"fmt"
	"log/slog"
	"net/http"

	"github.com/go-api-libs/api/server"
)

// Service defines the operations the server must implement.
type Service interface {
	GetThing(ctx context.Context, thingID string) error
	StartThing(ctx context.Context, thingID string) (*StartThingOk, error)
	ListRunningThings(ctx context.Context) (*ListRunningThingsOk, error)
}

// RegisterService registers a [Service] with an [*http.ServeMux].
// Optionally, a path prefix may be provided.
func RegisterService(svc Service, mux *http.ServeMux, pathPrefix string) {
	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/{thingID}")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "GetThing"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			thingID := r.PathValue("thingID")

			if err := svc.GetThing(ctx, thingID); err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.WriteHeader(http.StatusOK)

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/{thingID}/start")
		l := slog.Default().With(slog.String("method", "POST"), slog.String("path", path), slog.String("function", "StartThing"))

		mux.HandleFunc(fmt.Sprintf("POST %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			thingID := r.PathValue("thingID")

			res, err := svc.StartThing(ctx, thingID)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/running")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "ListRunningThings"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			res, err := svc.ListRunningThings(ctx)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}
}
