// This file provides types for the API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package things

import (
	"encoding/json/v2"
)

var jsonOpts = json.JoinOptions(
	json.RejectUnknownMembers(true),
)

// ListRunningThingsOk defines a model
type ListRunningThingsOk struct {
	Status string `json:"status,omitzero"`
}

// StartThingOk defines a model
type StartThingOk struct {
	ID string `json:"id,omitzero"`
}
