// This file provides types for the API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package things

import (
	"encoding/json/v2"
)

var jsonOpts = json.JoinOptions(
	json.RejectUnknownMembers(true),
)

// jsonOptsLenient is jsonOpts accepting members the specification does not know, as debug mode decodes once a strict
// decoding failed, and as a caller's own type of a result is decoded.
var jsonOptsLenient = json.JoinOptions(jsonOpts, json.RejectUnknownMembers(false))

// ListRunningThingsOk defines a model
type ListRunningThingsOk struct {
	Status string `json:"status"`
}

// StartThingOk defines a model
type StartThingOk struct {
	ID string `json:"id"`
}
