// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package habitica

import (
	"context"
	"encoding/json/v2"
	"errors"
	"fmt"
	"log/slog"
	"net/http"

	"github.com/go-api-libs/api/server"
)

// Service defines the operations the server must implement.
type Service interface {
	ListApiv3TasksUser(ctx context.Context) (*ListApiv3TasksUserOkJSONResponse, error)
	GetApiv3TaskByTaskID(ctx context.Context, taskID string) (*GetApiv3TaskByTaskIDOkJSONResponse, error)
	ListApiv3User(ctx context.Context) (*ListApiv3UserOkJSONResponse, error)
	PostApiv3TaskScoreUp(ctx context.Context, taskID string) (*PostApiv3TaskScoreUpOkJSONResponse, error)
}

// RegisterService registers a [Service] with an [*http.ServeMux].
// Optionally, a path prefix may be provided.
func RegisterService(svc Service, mux *http.ServeMux, pathPrefix string) {
	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/tasks/user")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "ListApiv3TasksUser"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			res, err := svc.ListApiv3TasksUser(ctx)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/tasks/{taskId}")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "GetApiv3TaskByTaskID"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			taskID := r.PathValue("taskId")

			res, err := svc.GetApiv3TaskByTaskID(ctx, taskID)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/user")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "ListApiv3User"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			res, err := svc.ListApiv3User(ctx)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/tasks/{taskId}/score/up")
		l := slog.Default().With(slog.String("method", "POST"), slog.String("path", path), slog.String("function", "PostApiv3TaskScoreUp"))

		mux.HandleFunc(fmt.Sprintf("POST %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			taskID := r.PathValue("taskId")

			res, err := svc.PostApiv3TaskScoreUp(ctx, taskID)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}
}
