// This file provides types for the API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package habitica

import (
	"encoding/json/v2"
	"time"

	"github.com/MarkRosemaker/jsonutil"
	"github.com/go-api-libs/types"
	"github.com/google/uuid"
)

var jsonOpts = json.JoinOptions(
	json.RejectUnknownMembers(true),
	json.WithUnmarshalers(json.JoinUnmarshalers(
		json.UnmarshalFromFunc(jsonutil.TimeUnmarshalStringOrIntUnix),
	)),
)

// ListApiv3TasksUserParams holds the query parameters for ListApiv3TasksUser.
type ListApiv3TasksUserParams struct {
	XAPIUser uuid.UUID
}

// GetApiv3TaskByTaskIDParams holds the query parameters for GetApiv3TaskByTaskID.
type GetApiv3TaskByTaskIDParams struct {
	XAPIUser uuid.UUID
}

// ListApiv3UserParams holds the query parameters for ListApiv3User.
type ListApiv3UserParams struct {
	XAPIUser uuid.UUID
}

// PostApiv3TaskScoreUpParams holds the query parameters for PostApiv3TaskScoreUp.
type PostApiv3TaskScoreUpParams struct {
	XAPIUser uuid.UUID
}

// ApivTaskByTaskIDDataGroup defines a model
type ApivTaskByTaskIDDataGroup struct {
	AssignedUsers []struct{}                        `json:"assignedUsers"`
	Approval      ApivTaskByTaskIDDataGroupApproval `json:"approval"`
}

// ApivTaskByTaskIDDataGroupApproval defines a model
type ApivTaskByTaskIDDataGroupApproval struct {
	Required  bool `json:"required"`
	Approved  bool `json:"approved"`
	Requested bool `json:"requested"`
}

// GetApiv3TaskByTaskIDOkJSONResponse defines a model
type GetApiv3TaskByTaskIDOkJSONResponse struct {
	Success       bool                                   `json:"success"`
	Data          GetApiv3TaskByTaskIDOkJSONResponseData `json:"data"`
	Notifications []struct{}                             `json:"notifications"`
}

// GetApiv3TaskByTaskIDOkJSONResponseData defines a model
type GetApiv3TaskByTaskIDOkJSONResponseData struct {
	UnderscoreID uuid.UUID                                       `json:"_id,omitzero"`
	UserID       uuid.UUID                                       `json:"userId,omitzero"`
	Text         string                                          `json:"text,omitzero"`
	Alias        string                                          `json:"alias,omitzero"`
	Type         string                                          `json:"type,omitzero"`
	Notes        string                                          `json:"notes,omitzero"`
	Tags         []struct{}                                      `json:"tags"`
	Value        float64                                         `json:"value"`
	Priority     float64                                         `json:"priority"`
	Attribute    string                                          `json:"attribute,omitzero"`
	Challenge    GetApiv3TaskByTaskIDOkJSONResponseDataChallenge `json:"challenge"`
	Group        ApivTaskByTaskIDDataGroup                       `json:"group"`
	Reminders    []struct{}                                      `json:"reminders"`
	CreatedAt    time.Time                                       `json:"createdAt,omitzero"`
	UpdatedAt    time.Time                                       `json:"updatedAt,omitzero"`
	History      GetApiv3TaskByTaskIDOkJSONResponseDataHistory   `json:"history"`
	Down         bool                                            `json:"down"`
	Up           bool                                            `json:"up"`
	ID           uuid.UUID                                       `json:"id,omitzero"`
}

// GetApiv3TaskByTaskIDOkJSONResponseDataChallenge defines a model
type GetApiv3TaskByTaskIDOkJSONResponseDataChallenge struct {
	TaskID uuid.UUID `json:"taskId,omitzero"`
	ID     uuid.UUID `json:"id,omitzero"`
}

// GetApiv3TaskByTaskIDOkJSONResponseDataHistory defines a model
type GetApiv3TaskByTaskIDOkJSONResponseDataHistory []GetApiv3TaskByTaskIDOkJSONResponseDataHistoryItem

// GetApiv3TaskByTaskIDOkJSONResponseDataHistoryItem defines a model
type GetApiv3TaskByTaskIDOkJSONResponseDataHistoryItem struct {
	Value float64 `json:"value"`
	Date  int     `json:"date"`
}

// ListApiv3TasksUserOkJSONResponse defines a model
type ListApiv3TasksUserOkJSONResponse struct {
	Success       bool                                 `json:"success"`
	Data          ListApiv3TasksUserOkJSONResponseData `json:"data"`
	Notifications []struct{}                           `json:"notifications"`
}

// ListApiv3TasksUserOkJSONResponseData defines a model
type ListApiv3TasksUserOkJSONResponseData []ListApiv3TasksUserOkJSONResponseDataItem

// ListApiv3TasksUserOkJSONResponseDataItem defines a model
type ListApiv3TasksUserOkJSONResponseDataItem struct {
	UnderscoreID      uuid.UUID                                         `json:"_id,omitzero"`
	UserID            uuid.UUID                                         `json:"userId,omitzero"`
	Text              string                                            `json:"text,omitzero"`
	Type              string                                            `json:"type,omitzero"`
	Notes             string                                            `json:"notes,omitzero"`
	Tags              []struct{}                                        `json:"tags"`
	Value             int                                               `json:"value"`
	Priority          int                                               `json:"priority"`
	Attribute         string                                            `json:"attribute,omitzero"`
	Challenge         struct{}                                          `json:"challenge"`
	Group             ApivTaskByTaskIDDataGroup                         `json:"group"`
	Reminders         ListApiv3TasksUserOkJSONResponseDataItemReminders `json:"reminders"`
	CreatedAt         time.Time                                         `json:"createdAt,omitzero"`
	UpdatedAt         time.Time                                         `json:"updatedAt,omitzero"`
	ID                uuid.UUID                                         `json:"id,omitzero"`
	Alias             string                                            `json:"alias,omitzero"`
	Checklist         []struct{}                                        `json:"checklist,omitzero"`
	CollapseChecklist bool                                              `json:"collapseChecklist,omitempty"`
	Completed         bool                                              `json:"completed,omitempty"`
	History           []struct{}                                        `json:"history,omitzero"`
	Streak            *int                                              `json:"streak,omitempty"`
	Repeat            *ListApiv3TasksUserOkJSONResponseDataItemRepeat   `json:"repeat,omitempty"`
	StartDate         time.Time                                         `json:"startDate,omitempty"`
	EveryX            *int                                              `json:"everyX,omitempty"`
	Frequency         string                                            `json:"frequency,omitzero"`
}

// ListApiv3TasksUserOkJSONResponseDataItemReminders defines a model
type ListApiv3TasksUserOkJSONResponseDataItemReminders []ListApiv3TasksUserOkJSONResponseDataItemRemindersItem

// ListApiv3TasksUserOkJSONResponseDataItemRemindersItem defines a model
type ListApiv3TasksUserOkJSONResponseDataItemRemindersItem struct {
	Time      time.Time  `json:"time,omitempty"`
	StartDate time.Time  `json:"startDate,omitempty"`
	ID        *uuid.UUID `json:"id,omitempty"`
}

// ListApiv3TasksUserOkJSONResponseDataItemRepeat defines a model
type ListApiv3TasksUserOkJSONResponseDataItemRepeat struct {
	Su bool `json:"su"`
	S  bool `json:"s"`
	F  bool `json:"f"`
	Th bool `json:"th"`
	W  bool `json:"w"`
	T  bool `json:"t"`
	M  bool `json:"m"`
}

// ListApiv3UserOkJSONResponse defines a model
type ListApiv3UserOkJSONResponse struct {
	Success       bool                            `json:"success"`
	Data          ListApiv3UserOkJSONResponseData `json:"data"`
	Notifications []struct{}                      `json:"notifications"`
	UserV         int                             `json:"userV"`
	AppVersion    string                          `json:"appVersion,omitzero"`
}

// ListApiv3UserOkJSONResponseData defines a model
type ListApiv3UserOkJSONResponseData struct {
	Auth                   ListApiv3UserOkJSONResponseDataAuth         `json:"auth"`
	Achievements           ListApiv3UserOkJSONResponseDataAchievements `json:"achievements"`
	Backer                 struct{}                                    `json:"backer"`
	Contributor            struct{}                                    `json:"contributor"`
	Permissions            struct{}                                    `json:"permissions"`
	Purchased              ListApiv3UserOkJSONResponseDataPurchased    `json:"purchased"`
	Flags                  ListApiv3UserOkJSONResponseDataFlags        `json:"flags"`
	History                ListApiv3UserOkJSONResponseDataHistory      `json:"history"`
	Items                  ListApiv3UserOkJSONResponseDataItems        `json:"items"`
	Invitations            ListApiv3UserOkJSONResponseDataInvitations  `json:"invitations"`
	Party                  ListApiv3UserOkJSONResponseDataParty        `json:"party"`
	Preferences            ListApiv3UserOkJSONResponseDataPreferences  `json:"preferences"`
	Profile                ListApiv3UserOkJSONResponseDataProfile      `json:"profile"`
	Stats                  ListApiv3UserOkJSONResponseDataStats        `json:"stats"`
	Inbox                  ListApiv3UserOkJSONResponseDataInbox        `json:"inbox"`
	TasksOrder             ListApiv3UserOkJSONResponseDataTasksOrder   `json:"tasksOrder"`
	UnderscoreID           uuid.UUID                                   `json:"_id,omitzero"`
	UnderscoreABtest       string                                      `json:"_ABtest,omitzero"`
	LoginIncentives        int                                         `json:"loginIncentives"`
	Webhooks               []struct{}                                  `json:"webhooks"`
	PushDevices            ListApiv3UserOkJSONResponseDataPushDevices  `json:"pushDevices"`
	Extra                  struct{}                                    `json:"extra"`
	Tags                   ListApiv3UserOkJSONResponseDataTags         `json:"tags"`
	Notifications          []struct{}                                  `json:"notifications"`
	Guilds                 []uuid.UUID                                 `json:"guilds"`
	Challenges             []uuid.UUID                                 `json:"challenges"`
	NewMessages            struct{}                                    `json:"newMessages"`
	LastCron               time.Time                                   `json:"lastCron,omitzero"`
	Balance                int                                         `json:"balance"`
	UnderscoreV            int                                         `json:"_v"`
	Migration              string                                      `json:"migration,omitzero"`
	PinnedItems            ListApiv3UserOkJSONResponseDataPinnedItems  `json:"pinnedItems"`
	UnpinnedItems          []struct{}                                  `json:"unpinnedItems"`
	InvitesSent            int                                         `json:"invitesSent"`
	PinnedItemsOrder       []struct{}                                  `json:"pinnedItemsOrder"`
	UnderscoreSubSignature string                                      `json:"_subSignature,omitzero"`
	ID                     uuid.UUID                                   `json:"id,omitzero"`
	NeedsCron              bool                                        `json:"needsCron"`
}

// ListApiv3UserOkJSONResponseDataAchievements defines a model
type ListApiv3UserOkJSONResponseDataAchievements struct {
	UltimateGearSets   ListApiv3UserOkJSONResponseDataAchievementsUltimateGearSets `json:"ultimateGearSets"`
	Perfect            int                                                         `json:"perfect"`
	Quests             ListApiv3UserOkJSONResponseDataAchievementsQuests           `json:"quests"`
	Challenges         []struct{}                                                  `json:"challenges"`
	PartyUp            bool                                                        `json:"partyUp"`
	PartyOn            bool                                                        `json:"partyOn"`
	HabitBirthdays     int                                                         `json:"habitBirthdays"`
	Streak             int                                                         `json:"streak"`
	JoinedGuild        bool                                                        `json:"joinedGuild"`
	JoinedChallenge    bool                                                        `json:"joinedChallenge"`
	HabiticaDays       int                                                         `json:"habiticaDays"`
	InvitedFriend      bool                                                        `json:"invitedFriend"`
	BackToBasics       bool                                                        `json:"backToBasics"`
	DustDevil          bool                                                        `json:"dustDevil"`
	MonsterMagus       bool                                                        `json:"monsterMagus"`
	CompletedTask      bool                                                        `json:"completedTask"`
	CreatedTask        bool                                                        `json:"createdTask"`
	FedPet             bool                                                        `json:"fedPet"`
	HatchedPet         bool                                                        `json:"hatchedPet"`
	PurchasedEquipment bool                                                        `json:"purchasedEquipment"`
	SeeingRed          bool                                                        `json:"seeingRed"`
	ShadyCustomer      bool                                                        `json:"shadyCustomer"`
	RoyallyLoyal       bool                                                        `json:"royallyLoyal"`
	AllYourBase        bool                                                        `json:"allYourBase"`
	PearlyPro          bool                                                        `json:"pearlyPro"`
}

// ListApiv3UserOkJSONResponseDataAchievementsQuests defines a model
type ListApiv3UserOkJSONResponseDataAchievementsQuests struct {
	Dustbunnies  int `json:"dustbunnies"`
	Basilist     int `json:"basilist"`
	Moon1        int `json:"moon1"`
	Moon2        int `json:"moon2"`
	Dysheartener int `json:"dysheartener"`
	Moon3        int `json:"moon3"`
	Vice1        int `json:"vice1"`
	Vice2        int `json:"vice2"`
	Vice3        int `json:"vice3"`
	Atom1        int `json:"atom1"`
	Atom2        int `json:"atom2"`
}

// ListApiv3UserOkJSONResponseDataAchievementsUltimateGearSets defines a model
type ListApiv3UserOkJSONResponseDataAchievementsUltimateGearSets struct {
	Warrior bool `json:"warrior"`
	Rogue   bool `json:"rogue"`
	Wizard  bool `json:"wizard"`
	Healer  bool `json:"healer"`
}

// ListApiv3UserOkJSONResponseDataAuth defines a model
type ListApiv3UserOkJSONResponseDataAuth struct {
	Local      ListApiv3UserOkJSONResponseDataAuthLocal      `json:"local"`
	Timestamps ListApiv3UserOkJSONResponseDataAuthTimestamps `json:"timestamps"`
	Google     ListApiv3UserOkJSONResponseDataAuthGoogle     `json:"google"`
	Apple      struct{}                                      `json:"apple"`
	Facebook   struct{}                                      `json:"facebook"`
}

// ListApiv3UserOkJSONResponseDataAuthGoogle defines a model
type ListApiv3UserOkJSONResponseDataAuthGoogle struct {
	ID     string                                          `json:"id,omitzero"`
	Emails ListApiv3UserOkJSONResponseDataAuthGoogleEmails `json:"emails"`
}

// ListApiv3UserOkJSONResponseDataAuthGoogleEmails defines a model
type ListApiv3UserOkJSONResponseDataAuthGoogleEmails []ListApiv3UserOkJSONResponseDataAuthGoogleEmailsItem

// ListApiv3UserOkJSONResponseDataAuthGoogleEmailsItem defines a model
type ListApiv3UserOkJSONResponseDataAuthGoogleEmailsItem struct {
	Value    types.Email `json:"value,omitzero"`
	Verified bool        `json:"verified"`
}

// ListApiv3UserOkJSONResponseDataAuthLocal defines a model
type ListApiv3UserOkJSONResponseDataAuthLocal struct {
	Username          string      `json:"username,omitzero"`
	LowerCaseUsername string      `json:"lowerCaseUsername,omitzero"`
	Email             types.Email `json:"email,omitzero"`
	HasPassword       bool        `json:"has_password"`
}

// ListApiv3UserOkJSONResponseDataAuthTimestamps defines a model
type ListApiv3UserOkJSONResponseDataAuthTimestamps struct {
	Loggedin time.Time `json:"loggedin,omitzero"`
	Created  time.Time `json:"created,omitzero"`
	Updated  time.Time `json:"updated,omitzero"`
}

// ListApiv3UserOkJSONResponseDataFlags defines a model
type ListApiv3UserOkJSONResponseDataFlags struct {
	Tour                        ListApiv3UserOkJSONResponseDataFlagsTour       `json:"tour"`
	Tutorial                    ListApiv3UserOkJSONResponseDataFlagsTutorial   `json:"tutorial"`
	CustomizationsNotification  bool                                           `json:"customizationsNotification"`
	ShowTour                    bool                                           `json:"showTour"`
	DropsEnabled                bool                                           `json:"dropsEnabled"`
	ItemsEnabled                bool                                           `json:"itemsEnabled"`
	LastNewStuffRead            uuid.UUID                                      `json:"lastNewStuffRead,omitzero"`
	Rewrite                     bool                                           `json:"rewrite"`
	ClassSelected               bool                                           `json:"classSelected"`
	RebirthEnabled              bool                                           `json:"rebirthEnabled"`
	RecaptureEmailsPhase        int                                            `json:"recaptureEmailsPhase"`
	WeeklyRecapEmailsPhase      int                                            `json:"weeklyRecapEmailsPhase"`
	CommunityGuidelinesAccepted bool                                           `json:"communityGuidelinesAccepted"`
	CronCount                   int                                            `json:"cronCount"`
	Welcomed                    bool                                           `json:"welcomed"`
	ArmoireEnabled              bool                                           `json:"armoireEnabled"`
	ArmoireOpened               bool                                           `json:"armoireOpened"`
	ArmoireEmpty                bool                                           `json:"armoireEmpty"`
	CardReceived                bool                                           `json:"cardReceived"`
	WarnedLowHealth             bool                                           `json:"warnedLowHealth"`
	VerifiedUsername            bool                                           `json:"verifiedUsername"`
	LevelDrops                  ListApiv3UserOkJSONResponseDataFlagsLevelDrops `json:"levelDrops"`
	LastWeeklyRecap             time.Time                                      `json:"lastWeeklyRecap,omitzero"`
	InitializedUserHistory      bool                                           `json:"initializedUserHistory"`
	ThirdPartyTools             time.Time                                      `json:"thirdPartyTools,omitzero"`
	NewStuff                    bool                                           `json:"newStuff"`
}

// ListApiv3UserOkJSONResponseDataFlagsLevelDrops defines a model
type ListApiv3UserOkJSONResponseDataFlagsLevelDrops struct {
	Atom1         bool `json:"atom1"`
	Vice1         bool `json:"vice1"`
	Goldenknight1 bool `json:"goldenknight1"`
	Moonstone1    bool `json:"moonstone1"`
}

// ListApiv3UserOkJSONResponseDataFlagsTour defines a model
type ListApiv3UserOkJSONResponseDataFlagsTour struct {
	Intro      int `json:"intro"`
	Classes    int `json:"classes"`
	Stats      int `json:"stats"`
	Tavern     int `json:"tavern"`
	Party      int `json:"party"`
	Guilds     int `json:"guilds"`
	Challenges int `json:"challenges"`
	Market     int `json:"market"`
	Pets       int `json:"pets"`
	Mounts     int `json:"mounts"`
	Hall       int `json:"hall"`
	Equipment  int `json:"equipment"`
	GroupPlans int `json:"groupPlans"`
}

// ListApiv3UserOkJSONResponseDataFlagsTutorial defines a model
type ListApiv3UserOkJSONResponseDataFlagsTutorial struct {
	Common ListApiv3UserOkJSONResponseDataFlagsTutorialCommon `json:"common"`
	Ios    ListApiv3UserOkJSONResponseDataFlagsTutorialIos    `json:"ios"`
}

// ListApiv3UserOkJSONResponseDataFlagsTutorialCommon defines a model
type ListApiv3UserOkJSONResponseDataFlagsTutorialCommon struct {
	Habits    bool `json:"habits"`
	Dailies   bool `json:"dailies"`
	Todos     bool `json:"todos"`
	Rewards   bool `json:"rewards"`
	Party     bool `json:"party"`
	Pets      bool `json:"pets"`
	Gems      bool `json:"gems"`
	Skills    bool `json:"skills"`
	Classes   bool `json:"classes"`
	Tavern    bool `json:"tavern"`
	Equipment bool `json:"equipment"`
	Items     bool `json:"items"`
	Mounts    bool `json:"mounts"`
	Inbox     bool `json:"inbox"`
	Stats     bool `json:"stats"`
}

// ListApiv3UserOkJSONResponseDataFlagsTutorialIos defines a model
type ListApiv3UserOkJSONResponseDataFlagsTutorialIos struct {
	AddTask     bool `json:"addTask"`
	EditTask    bool `json:"editTask"`
	DeleteTask  bool `json:"deleteTask"`
	FilterTask  bool `json:"filterTask"`
	GroupPets   bool `json:"groupPets"`
	InviteParty bool `json:"inviteParty"`
	ReorderTask bool `json:"reorderTask"`
}

// ListApiv3UserOkJSONResponseDataHistory defines a model
type ListApiv3UserOkJSONResponseDataHistory struct {
	Todos ListApivUserDataHistoryExp `json:"todos"`
	Exp   ListApivUserDataHistoryExp `json:"exp"`
}

// ListApiv3UserOkJSONResponseDataInbox defines a model
type ListApiv3UserOkJSONResponseDataInbox struct {
	OptOut      bool                                         `json:"optOut"`
	Messages    ListApiv3UserOkJSONResponseDataInboxMessages `json:"messages"`
	Blocks      []struct{}                                   `json:"blocks"`
	NewMessages int                                          `json:"newMessages"`
}

// ListApiv3UserOkJSONResponseDataInboxMessages defines a model
type ListApiv3UserOkJSONResponseDataInboxMessages struct {
	EightSixThreeSixThreeB9cF1c4400787f9607d399af305 ListApivUserDataInboxMessagesfeffAcddbf `json:"86363b9c-f1c4-4007-87f9-607d399af305"`
	EightThreeBe6b884fd2494c8f9b0bb22d2ff6cf         ListApivUserDataInboxMessagesfeffAcddbf `json:"83be6b88-4fd2-494c-8f9b-0bb22d2ff6cf"`
	Da886215C4f446498be8Da7535a5e3dc                 ListApivUserDataInboxMessagesfeffAcddbf `json:"da886215-c4f4-4649-8be8-da7535a5e3dc"`
	A891481d84e64bb597283948867ad46e                 ListApivUserDataInboxMessagesfeffAcddbf `json:"a891481d-84e6-4bb5-9728-3948867ad46e"`
	ZeroSixEightFe676885443ffA0cd673d7b766f01        ListApivUserDataInboxMessagesfeffAcddbf `json:"068fe676-8854-43ff-a0cd-673d7b766f01"`
}

// ListApiv3UserOkJSONResponseDataInvitations defines a model
type ListApiv3UserOkJSONResponseDataInvitations struct {
	Party   struct{}   `json:"party"`
	Guilds  []struct{} `json:"guilds"`
	Parties []struct{} `json:"parties"`
}

// ListApiv3UserOkJSONResponseDataItems defines a model
type ListApiv3UserOkJSONResponseDataItems struct {
	Gear            ListApiv3UserOkJSONResponseDataItemsGear            `json:"gear"`
	Special         ListApiv3UserOkJSONResponseDataItemsSpecial         `json:"special"`
	LastDrop        ListApiv3UserOkJSONResponseDataItemsLastDrop        `json:"lastDrop"`
	Quests          ListApiv3UserOkJSONResponseDataItemsQuests          `json:"quests"`
	Mounts          ListApiv3UserOkJSONResponseDataItemsMounts          `json:"mounts"`
	Food            ListApiv3UserOkJSONResponseDataItemsFood            `json:"food"`
	HatchingPotions ListApiv3UserOkJSONResponseDataItemsHatchingPotions `json:"hatchingPotions"`
	Eggs            ListApiv3UserOkJSONResponseDataItemsEggs            `json:"eggs"`
	Pets            ListApiv3UserOkJSONResponseDataItemsPets            `json:"pets"`
	CurrentPet      string                                              `json:"currentPet,omitzero"`
	CurrentMount    string                                              `json:"currentMount,omitzero"`
}

// ListApiv3UserOkJSONResponseDataItemsEggs defines a model
type ListApiv3UserOkJSONResponseDataItemsEggs struct {
	Wolf      int `json:"Wolf"`
	Cactus    int `json:"Cactus"`
	PandaCub  int `json:"PandaCub"`
	Fox       int `json:"Fox"`
	BearCub   int `json:"BearCub"`
	Dragon    int `json:"Dragon"`
	LionCub   int `json:"LionCub"`
	FlyingPig int `json:"FlyingPig"`
	TigerCub  int `json:"TigerCub"`
}

// ListApiv3UserOkJSONResponseDataItemsFood defines a model
type ListApiv3UserOkJSONResponseDataItemsFood struct {
	Potatoe              int `json:"Potatoe"`
	Chocolate            int `json:"Chocolate"`
	CottonCandyPink      int `json:"CottonCandyPink"`
	Meat                 int `json:"Meat"`
	CottonCandyBlue      int `json:"CottonCandyBlue"`
	RottenMeat           int `json:"RottenMeat"`
	CakeSkeleton         int `json:"Cake_Skeleton"`
	CakeBase             int `json:"Cake_Base"`
	CakeCottonCandyBlue  int `json:"Cake_CottonCandyBlue"`
	CakeCottonCandyPink  int `json:"Cake_CottonCandyPink"`
	CakeShade            int `json:"Cake_Shade"`
	CakeWhite            int `json:"Cake_White"`
	CakeGolden           int `json:"Cake_Golden"`
	CakeZombie           int `json:"Cake_Zombie"`
	CakeDesert           int `json:"Cake_Desert"`
	CakeRed              int `json:"Cake_Red"`
	Honey                int `json:"Honey"`
	Strawberry           int `json:"Strawberry"`
	Milk                 int `json:"Milk"`
	Fish                 int `json:"Fish"`
	Saddle               int `json:"Saddle"`
	CandySkeleton        int `json:"Candy_Skeleton"`
	CandyBase            int `json:"Candy_Base"`
	CandyCottonCandyBlue int `json:"Candy_CottonCandyBlue"`
	CandyCottonCandyPink int `json:"Candy_CottonCandyPink"`
	CandyShade           int `json:"Candy_Shade"`
	CandyWhite           int `json:"Candy_White"`
	CandyGolden          int `json:"Candy_Golden"`
	CandyZombie          int `json:"Candy_Zombie"`
	CandyDesert          int `json:"Candy_Desert"`
	CandyRed             int `json:"Candy_Red"`
	PieSkeleton          int `json:"Pie_Skeleton"`
	PieBase              int `json:"Pie_Base"`
	PieCottonCandyBlue   int `json:"Pie_CottonCandyBlue"`
	PieCottonCandyPink   int `json:"Pie_CottonCandyPink"`
	PieShade             int `json:"Pie_Shade"`
	PieWhite             int `json:"Pie_White"`
	PieGolden            int `json:"Pie_Golden"`
	PieZombie            int `json:"Pie_Zombie"`
	PieDesert            int `json:"Pie_Desert"`
	PieRed               int `json:"Pie_Red"`
}

// ListApiv3UserOkJSONResponseDataItemsGear defines a model
type ListApiv3UserOkJSONResponseDataItemsGear struct {
	Equipped ListApiv3UserOkJSONResponseDataItemsGearEquipped `json:"equipped"`
	Costume  ListApiv3UserOkJSONResponseDataItemsGearCostume  `json:"costume"`
	Owned    ListApiv3UserOkJSONResponseDataItemsGearOwned    `json:"owned"`
}

// ListApiv3UserOkJSONResponseDataItemsGearCostume defines a model
type ListApiv3UserOkJSONResponseDataItemsGearCostume struct {
	Shield string `json:"shield,omitzero"`
	Head   string `json:"head,omitzero"`
	Armor  string `json:"armor,omitzero"`
}

// ListApiv3UserOkJSONResponseDataItemsGearEquipped defines a model
type ListApiv3UserOkJSONResponseDataItemsGearEquipped struct {
	Weapon  string `json:"weapon,omitzero"`
	Armor   string `json:"armor,omitzero"`
	Head    string `json:"head,omitzero"`
	Shield  string `json:"shield,omitzero"`
	Back    string `json:"back,omitzero"`
	Eyewear string `json:"eyewear,omitzero"`
	Body    string `json:"body,omitzero"`
}

// ListApiv3UserOkJSONResponseDataItemsGearOwned defines a model
type ListApiv3UserOkJSONResponseDataItemsGearOwned struct {
	EyewearSpecialYellowTopFrame       bool `json:"eyewear_special_yellowTopFrame"`
	EyewearSpecialWhiteTopFrame        bool `json:"eyewear_special_whiteTopFrame"`
	EyewearSpecialRedTopFrame          bool `json:"eyewear_special_redTopFrame"`
	EyewearSpecialPinkTopFrame         bool `json:"eyewear_special_pinkTopFrame"`
	EyewearSpecialGreenTopFrame        bool `json:"eyewear_special_greenTopFrame"`
	EyewearSpecialBlueTopFrame         bool `json:"eyewear_special_blueTopFrame"`
	EyewearSpecialBlackTopFrame        bool `json:"eyewear_special_blackTopFrame"`
	ArmorSpecialBardRobes              bool `json:"armor_special_bardRobes"`
	HeadSpecialBardHat                 bool `json:"head_special_bardHat"`
	HeadWarrior1                       bool `json:"head_warrior_1"`
	WeaponWarrior0                     bool `json:"weapon_warrior_0"`
	ShieldWarrior1                     bool `json:"shield_warrior_1"`
	WeaponWarrior1                     bool `json:"weapon_warrior_1"`
	ArmorSpecialBirthday               bool `json:"armor_special_birthday"`
	WeaponWarrior2                     bool `json:"weapon_warrior_2"`
	HeadWarrior2                       bool `json:"head_warrior_2"`
	WeaponSpecialBardInstrument        bool `json:"weapon_special_bardInstrument"`
	ArmorWarrior1                      bool `json:"armor_warrior_1"`
	ShieldWarrior2                     bool `json:"shield_warrior_2"`
	ArmorWarrior2                      bool `json:"armor_warrior_2"`
	HeadWarrior3                       bool `json:"head_warrior_3"`
	HeadSpecialLunarWarriorHelm        bool `json:"head_special_lunarWarriorHelm"`
	ShieldSpecialSpring2017Warrior     bool `json:"shield_special_spring2017Warrior"`
	WeaponWarrior3                     bool `json:"weapon_warrior_3"`
	ArmorSpecialPageArmor              bool `json:"armor_special_pageArmor"`
	HeadSpecialPageHelm                bool `json:"head_special_pageHelm"`
	ArmorWarrior3                      bool `json:"armor_warrior_3"`
	WeaponSpecialPageBanner            bool `json:"weapon_special_pageBanner"`
	ShieldSpecialDiamondStave          bool `json:"shield_special_diamondStave"`
	ArmorSpecialLunarWarriorArmor      bool `json:"armor_special_lunarWarriorArmor"`
	WeaponArmoireBasicLongbow          bool `json:"weapon_armoire_basicLongbow"`
	ArmorWarrior4                      bool `json:"armor_warrior_4"`
	ShieldWarrior3                     bool `json:"shield_warrior_3"`
	ShieldSpecialLootBag               bool `json:"shield_special_lootBag"`
	WeaponSpecialSkeletonKey           bool `json:"weapon_special_skeletonKey"`
	HeadSpecialNye                     bool `json:"head_special_nye"`
	ArmorSpecialSneakthiefRobes        bool `json:"armor_special_sneakthiefRobes"`
	HeadSpecialClandestineCowl         bool `json:"head_special_clandestineCowl"`
	ShieldSpecialWinter2018Warrior     bool `json:"shield_special_winter2018Warrior"`
	ArmorSpecialSnowSovereignRobes     bool `json:"armor_special_snowSovereignRobes"`
	HeadSpecialSnowSovereignCrown      bool `json:"head_special_snowSovereignCrown"`
	ArmorSpecialBirthday2015           bool `json:"armor_special_birthday2015"`
	BackSpecialSnowdriftVeil           bool `json:"back_special_snowdriftVeil"`
	ShieldSpecialWintryMirror          bool `json:"shield_special_wintryMirror"`
	HeadAccessorySpecialBlackHeadband  bool `json:"headAccessory_special_blackHeadband"`
	HeadAccessorySpecialBlueHeadband   bool `json:"headAccessory_special_blueHeadband"`
	HeadAccessorySpecialGreenHeadband  bool `json:"headAccessory_special_greenHeadband"`
	HeadAccessorySpecialPinkHeadband   bool `json:"headAccessory_special_pinkHeadband"`
	HeadAccessorySpecialRedHeadband    bool `json:"headAccessory_special_redHeadband"`
	HeadAccessorySpecialWhiteHeadband  bool `json:"headAccessory_special_whiteHeadband"`
	HeadAccessorySpecialYellowHeadband bool `json:"headAccessory_special_yellowHeadband"`
	WeaponWarrior4                     bool `json:"weapon_warrior_4"`
	WeaponWarrior5                     bool `json:"weapon_warrior_5"`
	HeadWarrior4                       bool `json:"head_warrior_4"`
	ArmorWarrior5                      bool `json:"armor_warrior_5"`
	ShieldWarrior4                     bool `json:"shield_warrior_4"`
	WeaponSpecialLunarScythe           bool `json:"weapon_special_lunarScythe"`
	HeadSpecialNye2014                 bool `json:"head_special_nye2014"`
	ArmorSpecialNomadsCuirass          bool `json:"armor_special_nomadsCuirass"`
	WeaponSpecialNomadsScimitar        bool `json:"weapon_special_nomadsScimitar"`
	HeadArmoireBigWig                  bool `json:"head_armoire_bigWig"`
	ArmorSpecialBirthday2016           bool `json:"armor_special_birthday2016"`
	HeadSpecialSpikedHelm              bool `json:"head_special_spikedHelm"`
	HeadSpecialPiDay                   bool `json:"head_special_piDay"`
	ShieldSpecialPiDay                 bool `json:"shield_special_piDay"`
	EyewearSpecialBlackHalfMoon        bool `json:"eyewear_special_blackHalfMoon"`
	EyewearSpecialBlueHalfMoon         bool `json:"eyewear_special_blueHalfMoon"`
	EyewearSpecialGreenHalfMoon        bool `json:"eyewear_special_greenHalfMoon"`
	EyewearSpecialPinkHalfMoon         bool `json:"eyewear_special_pinkHalfMoon"`
	EyewearSpecialRedHalfMoon          bool `json:"eyewear_special_redHalfMoon"`
	EyewearSpecialWhiteHalfMoon        bool `json:"eyewear_special_whiteHalfMoon"`
	EyewearSpecialYellowHalfMoon       bool `json:"eyewear_special_yellowHalfMoon"`
	HeadSpecialNamingDay2017           bool `json:"head_special_namingDay2017"`
	HeadSpecialNye2015                 bool `json:"head_special_nye2015"`
	ArmorSpecialBirthday2017           bool `json:"armor_special_birthday2017"`
	BodySpecialNamingDay2018           bool `json:"body_special_namingDay2018"`
	HeadSpecialNye2016                 bool `json:"head_special_nye2016"`
	ArmorSpecialBirthday2018           bool `json:"armor_special_birthday2018"`
	BackSpecialNamingDay2020           bool `json:"back_special_namingDay2020"`
	HeadSpecialDandyHat                bool `json:"head_special_dandyHat"`
	WeaponSpecialFencingFoil           bool `json:"weapon_special_fencingFoil"`
	ArmorSpecialDandySuit              bool `json:"armor_special_dandySuit"`
	ShieldWarrior5                     bool `json:"shield_warrior_5"`
	HeadWarrior5                       bool `json:"head_warrior_5"`
	WeaponWarrior6                     bool `json:"weapon_warrior_6"`
	WeaponSpecialFall2021Warrior       bool `json:"weapon_special_fall2021Warrior"`
	ArmorSpecialTurkeyArmorBase        bool `json:"armor_special_turkeyArmorBase"`
	BackSpecialTurkeyTailBase          bool `json:"back_special_turkeyTailBase"`
	HeadSpecialTurkeyHelmBase          bool `json:"head_special_turkeyHelmBase"`
	HeadSpecialNye2017                 bool `json:"head_special_nye2017"`
	WeaponArmoireJesterBaton           bool `json:"weapon_armoire_jesterBaton"`
	WeaponSpecialTachi                 bool `json:"weapon_special_tachi"`
	ArmorSpecialSamuraiArmor           bool `json:"armor_special_samuraiArmor"`
	WeaponSpecialWinter2022Warrior     bool `json:"weapon_special_winter2022Warrior"`
	HeadSpecialWinter2022Warrior       bool `json:"head_special_winter2022Warrior"`
	ShieldSpecialWinter2022Warrior     bool `json:"shield_special_winter2022Warrior"`
	ArmorSpecialBirthday2019           bool `json:"armor_special_birthday2019"`
	HeadSpecialKabuto                  bool `json:"head_special_kabuto"`
	ShieldSpecialWakizashi             bool `json:"shield_special_wakizashi"`
	WeaponSpecial2                     bool `json:"weapon_special_2"`
	WeaponArmoirePotionBase            bool `json:"weapon_armoire_potionBase"`
	WeaponArmoirePotionSkeleton        bool `json:"weapon_armoire_potionSkeleton"`
	WeaponSpecialSpring2022Warrior     bool `json:"weapon_special_spring2022Warrior"`
	HeadSpecialSpring2022Warrior       bool `json:"head_special_spring2022Warrior"`
	HeadSpecialFall2022Warrior         bool `json:"head_special_fall2022Warrior"`
	WeaponSpecialFall2022Warrior       bool `json:"weapon_special_fall2022Warrior"`
	ArmorSpecialFall2022Warrior        bool `json:"armor_special_fall2022Warrior"`
	ShieldSpecialFall2022Warrior       bool `json:"shield_special_fall2022Warrior"`
	ArmorSpecialTurkeyArmorGilded      bool `json:"armor_special_turkeyArmorGilded"`
	BackSpecialTurkeyTailGilded        bool `json:"back_special_turkeyTailGilded"`
	HeadSpecialTurkeyHelmGilded        bool `json:"head_special_turkeyHelmGilded"`
	HeadSpecialNye2018                 bool `json:"head_special_nye2018"`
	ArmorSpecialSummer2023Warrior      bool `json:"armor_special_summer2023Warrior"`
	HeadSpecialSummer2023Warrior       bool `json:"head_special_summer2023Warrior"`
	WeaponSpecialSummer2023Warrior     bool `json:"weapon_special_summer2023Warrior"`
	ShieldSpecialSummer2023Warrior     bool `json:"shield_special_summer2023Warrior"`
	HeadSpecialNye2019                 bool `json:"head_special_nye2019"`
	ArmorSpecialBirthday2020           bool `json:"armor_special_birthday2020"`
	HeadSpecialNye2020                 bool `json:"head_special_nye2020"`
	ArmorSpecialBirthday2021           bool `json:"armor_special_birthday2021"`
	ArmorSpecialSpring2025Warrior      bool `json:"armor_special_spring2025Warrior"`
	WeaponSpecialSpring2025Warrior     bool `json:"weapon_special_spring2025Warrior"`
	HeadSpecialSpring2025Warrior       bool `json:"head_special_spring2025Warrior"`
	ShieldSpecialSpring2025Warrior     bool `json:"shield_special_spring2025Warrior"`
	ShieldArmoireBaseballGlove         bool `json:"shield_armoire_baseballGlove"`
	HeadSpecialNye2021                 bool `json:"head_special_nye2021"`
	ArmorSpecialBirthday2022           bool `json:"armor_special_birthday2022"`
}

// ListApiv3UserOkJSONResponseDataItemsHatchingPotions defines a model
type ListApiv3UserOkJSONResponseDataItemsHatchingPotions struct {
	RoyalPurple     int `json:"RoyalPurple"`
	Desert          int `json:"Desert"`
	CottonCandyPink int `json:"CottonCandyPink"`
	CottonCandyBlue int `json:"CottonCandyBlue"`
	Red             int `json:"Red"`
	Zombie          int `json:"Zombie"`
	Base            int `json:"Base"`
	White           int `json:"White"`
	Shade           int `json:"Shade"`
	Skeleton        int `json:"Skeleton"`
	Golden          int `json:"Golden"`
}

// ListApiv3UserOkJSONResponseDataItemsLastDrop defines a model
type ListApiv3UserOkJSONResponseDataItemsLastDrop struct {
	Count int       `json:"count"`
	Date  time.Time `json:"date,omitzero"`
}

// ListApiv3UserOkJSONResponseDataItemsMounts defines a model
type ListApiv3UserOkJSONResponseDataItemsMounts struct {
	WolfRoyalPurple         bool `json:"Wolf-RoyalPurple"`
	PandaCubDesert          bool `json:"PandaCub-Desert"`
	OrcaBase                bool `json:"Orca-Base"`
	GryphonRoyalPurple      bool `json:"Gryphon-RoyalPurple"`
	HippogriffHopeful       bool `json:"Hippogriff-Hopeful"`
	JackOLanternBase        bool `json:"JackOLantern-Base"`
	TurkeyBase              bool `json:"Turkey-Base"`
	DragonRed               bool `json:"Dragon-Red"`
	WolfRed                 bool `json:"Wolf-Red"`
	PandaCubBase            bool `json:"PandaCub-Base"`
	PandaCubWhite           bool `json:"PandaCub-White"`
	FlyingPigDesert         bool `json:"FlyingPig-Desert"`
	TigerCubShade           bool `json:"TigerCub-Shade"`
	WolfSkeleton            bool `json:"Wolf-Skeleton"`
	TigerCubZombie          bool `json:"TigerCub-Zombie"`
	PandaCubZombie          bool `json:"PandaCub-Zombie"`
	TigerCubSkeleton        bool `json:"TigerCub-Skeleton"`
	WolfCottonCandyPink     bool `json:"Wolf-CottonCandyPink"`
	DragonCottonCandyPink   bool `json:"Dragon-CottonCandyPink"`
	WolfCottonCandyBlue     bool `json:"Wolf-CottonCandyBlue"`
	CactusCottonCandyBlue   bool `json:"Cactus-CottonCandyBlue"`
	DragonGolden            bool `json:"Dragon-Golden"`
	WolfGolden              bool `json:"Wolf-Golden"`
	FoxCottonCandyBlue      bool `json:"Fox-CottonCandyBlue"`
	PandaCubShade           bool `json:"PandaCub-Shade"`
	WolfWhite               bool `json:"Wolf-White"`
	BearCubGolden           bool `json:"BearCub-Golden"`
	CactusDesert            bool `json:"Cactus-Desert"`
	TigerCubRed             bool `json:"TigerCub-Red"`
	WolfBase                bool `json:"Wolf-Base"`
	JackOLanternGhost       bool `json:"JackOLantern-Ghost"`
	TurkeyGilded            bool `json:"Turkey-Gilded"`
	JackOLanternGlow        bool `json:"JackOLantern-Glow"`
	JackOLanternRoyalPurple bool `json:"JackOLantern-RoyalPurple"`
	WolfDesert              bool `json:"Wolf-Desert"`
	WolfShade               bool `json:"Wolf-Shade"`
	WolfZombie              bool `json:"Wolf-Zombie"`
	TigerCubBase            bool `json:"TigerCub-Base"`
	TigerCubWhite           bool `json:"TigerCub-White"`
	TigerCubDesert          bool `json:"TigerCub-Desert"`
	TigerCubCottonCandyPink bool `json:"TigerCub-CottonCandyPink"`
	TigerCubCottonCandyBlue bool `json:"TigerCub-CottonCandyBlue"`
	TigerCubGolden          bool `json:"TigerCub-Golden"`
	PandaCubRed             bool `json:"PandaCub-Red"`
	PandaCubSkeleton        bool `json:"PandaCub-Skeleton"`
	PandaCubCottonCandyPink bool `json:"PandaCub-CottonCandyPink"`
	PandaCubCottonCandyBlue bool `json:"PandaCub-CottonCandyBlue"`
	PandaCubGolden          bool `json:"PandaCub-Golden"`
	LionCubBase             bool `json:"LionCub-Base"`
	LionCubWhite            bool `json:"LionCub-White"`
	LionCubShade            bool `json:"LionCub-Shade"`
	LionCubSkeleton         bool `json:"LionCub-Skeleton"`
	LionCubZombie           bool `json:"LionCub-Zombie"`
	LionCubCottonCandyPink  bool `json:"LionCub-CottonCandyPink"`
	LionCubCottonCandyBlue  bool `json:"LionCub-CottonCandyBlue"`
	FoxBase                 bool `json:"Fox-Base"`
	BearCubBase             bool `json:"BearCub-Base"`
	CactusBase              bool `json:"Cactus-Base"`
	DragonBase              bool `json:"Dragon-Base"`
	FlyingPigBase           bool `json:"FlyingPig-Base"`
	FlyingPigWhite          bool `json:"FlyingPig-White"`
	FoxWhite                bool `json:"Fox-White"`
	DragonWhite             bool `json:"Dragon-White"`
	DragonDesert            bool `json:"Dragon-Desert"`
	DragonShade             bool `json:"Dragon-Shade"`
	DragonSkeleton          bool `json:"Dragon-Skeleton"`
	DragonZombie            bool `json:"Dragon-Zombie"`
	DragonCottonCandyBlue   bool `json:"Dragon-CottonCandyBlue"`
	BearCubWhite            bool `json:"BearCub-White"`
	BearCubDesert           bool `json:"BearCub-Desert"`
	BearCubRed              bool `json:"BearCub-Red"`
	BearCubShade            bool `json:"BearCub-Shade"`
	BearCubSkeleton         bool `json:"BearCub-Skeleton"`
	BearCubZombie           bool `json:"BearCub-Zombie"`
	BearCubCottonCandyPink  bool `json:"BearCub-CottonCandyPink"`
	BearCubCottonCandyBlue  bool `json:"BearCub-CottonCandyBlue"`
	CactusWhite             bool `json:"Cactus-White"`
	CactusRed               bool `json:"Cactus-Red"`
	CactusShade             bool `json:"Cactus-Shade"`
	CactusSkeleton          bool `json:"Cactus-Skeleton"`
}

// ListApiv3UserOkJSONResponseDataItemsPets defines a model
type ListApiv3UserOkJSONResponseDataItemsPets struct {
	WolfRoyalPurple          int `json:"Wolf-RoyalPurple"`
	PandaCubDesert           int `json:"PandaCub-Desert"`
	CactusDesert             int `json:"Cactus-Desert"`
	FoxRoyalPurple           int `json:"Fox-RoyalPurple"`
	WolfCottonCandyBlue      int `json:"Wolf-CottonCandyBlue"`
	DragonCottonCandyPink    int `json:"Dragon-CottonCandyPink"`
	DragonRed                int `json:"Dragon-Red"`
	FlyingPigCottonCandyPink int `json:"FlyingPig-CottonCandyPink"`
	DragonZombie             int `json:"Dragon-Zombie"`
	LionCubDesert            int `json:"LionCub-Desert"`
	BearCubDesert            int `json:"BearCub-Desert"`
	FoxRed                   int `json:"Fox-Red"`
	FlyingPigRed             int `json:"FlyingPig-Red"`
	PandaCubBase             int `json:"PandaCub-Base"`
	LionCubRoyalPurple       int `json:"LionCub-RoyalPurple"`
	DragonGolden             int `json:"Dragon-Golden"`
	BearCubBase              int `json:"BearCub-Base"`
	CactusCottonCandyBlue    int `json:"Cactus-CottonCandyBlue"`
	CactusCottonCandyPink    int `json:"Cactus-CottonCandyPink"`
	DragonRoyalPurple        int `json:"Dragon-RoyalPurple"`
	FlyingPigDesert          int `json:"FlyingPig-Desert"`
	FlyingPigRoyalPurple     int `json:"FlyingPig-RoyalPurple"`
	FoxCottonCandyBlue       int `json:"Fox-CottonCandyBlue"`
	LionCubCottonCandyBlue   int `json:"LionCub-CottonCandyBlue"`
	LionCubRed               int `json:"LionCub-Red"`
	PandaCubRed              int `json:"PandaCub-Red"`
	WolfRed                  int `json:"Wolf-Red"`
	WolfSkeleton             int `json:"Wolf-Skeleton"`
	WolfWhite                int `json:"Wolf-White"`
	TigerCubWhite            int `json:"TigerCub-White"`
	PandaCubWhite            int `json:"PandaCub-White"`
	TigerCubZombie           int `json:"TigerCub-Zombie"`
	PandaCubZombie           int `json:"PandaCub-Zombie"`
	TigerCubShade            int `json:"TigerCub-Shade"`
	PandaCubShade            int `json:"PandaCub-Shade"`
	TigerCubRoyalPurple      int `json:"TigerCub-RoyalPurple"`
	TigerCubSkeleton         int `json:"TigerCub-Skeleton"`
	TigerCubRed              int `json:"TigerCub-Red"`
	WolfVeteran              int `json:"Wolf-Veteran"`
	JackOLanternBase         int `json:"JackOLantern-Base"`
	TurkeyBase               int `json:"Turkey-Base"`
	HippogriffHopeful        int `json:"Hippogriff-Hopeful"`
	OrcaBase                 int `json:"Orca-Base"`
	GryphonRoyalPurple       int `json:"Gryphon-RoyalPurple"`
	TigerVeteran             int `json:"Tiger-Veteran"`
	PandaCubRoyalPurple      int `json:"PandaCub-RoyalPurple"`
	CactusRoyalPurple        int `json:"Cactus-RoyalPurple"`
	BearCubRoyalPurple       int `json:"BearCub-RoyalPurple"`
	WolfBase                 int `json:"Wolf-Base"`
	WolfDesert               int `json:"Wolf-Desert"`
	WolfShade                int `json:"Wolf-Shade"`
	WolfZombie               int `json:"Wolf-Zombie"`
	WolfCottonCandyPink      int `json:"Wolf-CottonCandyPink"`
	WolfGolden               int `json:"Wolf-Golden"`
	TigerCubBase             int `json:"TigerCub-Base"`
	BearCubWhite             int `json:"BearCub-White"`
	BearCubGolden            int `json:"BearCub-Golden"`
	PandaCubSkeleton         int `json:"PandaCub-Skeleton"`
	TigerCubDesert           int `json:"TigerCub-Desert"`
	TigerCubCottonCandyPink  int `json:"TigerCub-CottonCandyPink"`
	TigerCubCottonCandyBlue  int `json:"TigerCub-CottonCandyBlue"`
	TigerCubGolden           int `json:"TigerCub-Golden"`
	LionCubBase              int `json:"LionCub-Base"`
	FoxDesert                int `json:"Fox-Desert"`
	FlyingPigSkeleton        int `json:"FlyingPig-Skeleton"`
	DragonSkeleton           int `json:"Dragon-Skeleton"`
	FlyingPigWhite           int `json:"FlyingPig-White"`
	DragonDesert             int `json:"Dragon-Desert"`
	FoxShade                 int `json:"Fox-Shade"`
	LionCubZombie            int `json:"LionCub-Zombie"`
	FlyingPigZombie          int `json:"FlyingPig-Zombie"`
	CactusWhite              int `json:"Cactus-White"`
	FoxBase                  int `json:"Fox-Base"`
	FoxZombie                int `json:"Fox-Zombie"`
	DragonCottonCandyBlue    int `json:"Dragon-CottonCandyBlue"`
	FoxCottonCandyPink       int `json:"Fox-CottonCandyPink"`
	FlyingPigCottonCandyBlue int `json:"FlyingPig-CottonCandyBlue"`
	LionCubCottonCandyPink   int `json:"LionCub-CottonCandyPink"`
	FoxSkeleton              int `json:"Fox-Skeleton"`
	LionCubSkeleton          int `json:"LionCub-Skeleton"`
	LionCubShade             int `json:"LionCub-Shade"`
	FoxWhite                 int `json:"Fox-White"`
	LionCubWhite             int `json:"LionCub-White"`
	PandaCubCottonCandyPink  int `json:"PandaCub-CottonCandyPink"`
	FlyingPigShade           int `json:"FlyingPig-Shade"`
	FlyingPigBase            int `json:"FlyingPig-Base"`
	DragonBase               int `json:"Dragon-Base"`
	DragonWhite              int `json:"Dragon-White"`
	DragonShade              int `json:"Dragon-Shade"`
	PandaCubCottonCandyBlue  int `json:"PandaCub-CottonCandyBlue"`
	CactusBase               int `json:"Cactus-Base"`
	BearCubZombie            int `json:"BearCub-Zombie"`
	CactusShade              int `json:"Cactus-Shade"`
	CactusSkeleton           int `json:"Cactus-Skeleton"`
	CactusZombie             int `json:"Cactus-Zombie"`
	BearCubCottonCandyPink   int `json:"BearCub-CottonCandyPink"`
	CactusRed                int `json:"Cactus-Red"`
	BearCubSkeleton          int `json:"BearCub-Skeleton"`
	BearCubShade             int `json:"BearCub-Shade"`
	BearCubRed               int `json:"BearCub-Red"`
	BearCubCottonCandyBlue   int `json:"BearCub-CottonCandyBlue"`
	PandaCubGolden           int `json:"PandaCub-Golden"`
	JackOLanternGhost        int `json:"JackOLantern-Ghost"`
	TurkeyGilded             int `json:"Turkey-Gilded"`
	JackOLanternGlow         int `json:"JackOLantern-Glow"`
	JackOLanternRoyalPurple  int `json:"JackOLantern-RoyalPurple"`
	LionVeteran              int `json:"Lion-Veteran"`
	BearVeteran              int `json:"Bear-Veteran"`
	CactusGolden             int `json:"Cactus-Golden"`
}

// ListApiv3UserOkJSONResponseDataItemsQuests defines a model
type ListApiv3UserOkJSONResponseDataItemsQuests struct {
	Dustbunnies       int `json:"dustbunnies"`
	Moon1             int `json:"moon1"`
	Basilist          int `json:"basilist"`
	Moon2             int `json:"moon2"`
	Moon3             int `json:"moon3"`
	Atom1             int `json:"atom1"`
	DilatoryDistress1 int `json:"dilatoryDistress1"`
	Vice1             int `json:"vice1"`
	Vice2             int `json:"vice2"`
	Goldenknight1     int `json:"goldenknight1"`
	Vice3             int `json:"vice3"`
	Atom2             int `json:"atom2"`
	Atom3             int `json:"atom3"`
	Moonstone1        int `json:"moonstone1"`
}

// ListApiv3UserOkJSONResponseDataItemsSpecial defines a model
type ListApiv3UserOkJSONResponseDataItemsSpecial struct {
	BirthdayReceived  []struct{} `json:"birthdayReceived"`
	Birthday          int        `json:"birthday"`
	ThankyouReceived  []struct{} `json:"thankyouReceived"`
	Thankyou          int        `json:"thankyou"`
	GreetingReceived  []struct{} `json:"greetingReceived"`
	Greeting          int        `json:"greeting"`
	NyeReceived       []struct{} `json:"nyeReceived"`
	Nye               int        `json:"nye"`
	ValentineReceived []struct{} `json:"valentineReceived"`
	Valentine         int        `json:"valentine"`
	Seafoam           int        `json:"seafoam"`
	ShinySeed         int        `json:"shinySeed"`
	SpookySparkles    int        `json:"spookySparkles"`
	Snowball          int        `json:"snowball"`
	CongratsReceived  []struct{} `json:"congratsReceived"`
	GetwellReceived   []struct{} `json:"getwellReceived"`
	GoodluckReceived  []struct{} `json:"goodluckReceived"`
	Congrats          int        `json:"congrats"`
	Getwell           int        `json:"getwell"`
	Goodluck          int        `json:"goodluck"`
}

// ListApiv3UserOkJSONResponseDataParty defines a model
type ListApiv3UserOkJSONResponseDataParty struct {
	Quest          ListApiv3UserOkJSONResponseDataPartyQuest `json:"quest"`
	UnderscoreID   uuid.UUID                                 `json:"_id,omitzero"`
	Order          string                                    `json:"order,omitzero"`
	OrderAscending string                                    `json:"orderAscending,omitzero"`
}

// ListApiv3UserOkJSONResponseDataPartyQuest defines a model
type ListApiv3UserOkJSONResponseDataPartyQuest struct {
	Progress   ListApiv3UserOkJSONResponseDataPartyQuestProgress `json:"progress"`
	RsvpNeeded bool                                              `json:"RSVPNeeded"`
}

// ListApiv3UserOkJSONResponseDataPartyQuestProgress defines a model
type ListApiv3UserOkJSONResponseDataPartyQuestProgress struct {
	Up             float64  `json:"up"`
	Down           int      `json:"down"`
	CollectedItems int      `json:"collectedItems"`
	Collect        struct{} `json:"collect"`
}

// ListApiv3UserOkJSONResponseDataPinnedItems defines a model
type ListApiv3UserOkJSONResponseDataPinnedItems []ListApiv3UserOkJSONResponseDataPinnedItemsItem

// ListApiv3UserOkJSONResponseDataPinnedItemsItem defines a model
type ListApiv3UserOkJSONResponseDataPinnedItemsItem struct {
	Type string `json:"type,omitzero"`
	Path string `json:"path,omitzero"`
}

// ListApiv3UserOkJSONResponseDataPreferences defines a model
type ListApiv3UserOkJSONResponseDataPreferences struct {
	Hair                             ListApiv3UserOkJSONResponseDataPreferencesHair               `json:"hair"`
	EmailNotifications               ListApiv3UserOkJSONResponseDataPreferencesEmailNotifications `json:"emailNotifications"`
	PushNotifications                ListApiv3UserOkJSONResponseDataPreferencesPushNotifications  `json:"pushNotifications"`
	SuppressModals                   ListApiv3UserOkJSONResponseDataPreferencesSuppressModals     `json:"suppressModals"`
	Tasks                            ListApiv3UserOkJSONResponseDataPreferencesTasks              `json:"tasks"`
	DayStart                         int                                                          `json:"dayStart"`
	Size                             string                                                       `json:"size,omitzero"`
	HideHeader                       bool                                                         `json:"hideHeader"`
	Skin                             string                                                       `json:"skin,omitzero"`
	Shirt                            string                                                       `json:"shirt,omitzero"`
	TimezoneOffset                   int                                                          `json:"timezoneOffset"`
	Sound                            string                                                       `json:"sound,omitzero"`
	Chair                            string                                                       `json:"chair,omitzero"`
	AllocationMode                   string                                                       `json:"allocationMode,omitzero"`
	AutoEquip                        bool                                                         `json:"autoEquip"`
	Costume                          bool                                                         `json:"costume"`
	DateFormat                       string                                                       `json:"dateFormat,omitzero"`
	Sleep                            bool                                                         `json:"sleep"`
	StickyHeader                     bool                                                         `json:"stickyHeader"`
	DisableClasses                   bool                                                         `json:"disableClasses"`
	NewTaskEdit                      bool                                                         `json:"newTaskEdit"`
	DailyDueDefaultView              bool                                                         `json:"dailyDueDefaultView"`
	AdvancedCollapsed                bool                                                         `json:"advancedCollapsed"`
	ToolbarCollapsed                 bool                                                         `json:"toolbarCollapsed"`
	ReverseChatOrder                 bool                                                         `json:"reverseChatOrder"`
	DeveloperMode                    bool                                                         `json:"developerMode"`
	DisplayInviteToPartyWhenPartyIs1 bool                                                         `json:"displayInviteToPartyWhenPartyIs1"`
	ImprovementCategories            []struct{}                                                   `json:"improvementCategories"`
	AutomaticAllocation              bool                                                         `json:"automaticAllocation"`
	TimezoneOffsetAtLastCron         int                                                          `json:"timezoneOffsetAtLastCron"`
	Language                         string                                                       `json:"language,omitzero"`
	Webhooks                         struct{}                                                     `json:"webhooks"`
	AnalyticsConsent                 bool                                                         `json:"analyticsConsent"`
	Background                       string                                                       `json:"background,omitzero"`
}

// ListApiv3UserOkJSONResponseDataPreferencesEmailNotifications defines a model
type ListApiv3UserOkJSONResponseDataPreferencesEmailNotifications struct {
	UnsubscribeFromAll     bool `json:"unsubscribeFromAll"`
	NewPm                  bool `json:"newPM"`
	KickedGroup            bool `json:"kickedGroup"`
	WonChallenge           bool `json:"wonChallenge"`
	GiftedGems             bool `json:"giftedGems"`
	GiftedSubscription     bool `json:"giftedSubscription"`
	InvitedParty           bool `json:"invitedParty"`
	InvitedGuild           bool `json:"invitedGuild"`
	QuestStarted           bool `json:"questStarted"`
	InvitedQuest           bool `json:"invitedQuest"`
	ImportantAnnouncements bool `json:"importantAnnouncements"`
	WeeklyRecaps           bool `json:"weeklyRecaps"`
	Onboarding             bool `json:"onboarding"`
	MajorUpdates           bool `json:"majorUpdates"`
	SubscriptionReminders  bool `json:"subscriptionReminders"`
	ContentRelease         bool `json:"contentRelease"`
}

// ListApiv3UserOkJSONResponseDataPreferencesHair defines a model
type ListApiv3UserOkJSONResponseDataPreferencesHair struct {
	Color    string `json:"color,omitzero"`
	Base     int    `json:"base"`
	Bangs    int    `json:"bangs"`
	Beard    int    `json:"beard"`
	Mustache int    `json:"mustache"`
	Flower   int    `json:"flower"`
}

// ListApiv3UserOkJSONResponseDataPreferencesPushNotifications defines a model
type ListApiv3UserOkJSONResponseDataPreferencesPushNotifications struct {
	UnsubscribeFromAll   bool `json:"unsubscribeFromAll"`
	NewPm                bool `json:"newPM"`
	WonChallenge         bool `json:"wonChallenge"`
	GiftedGems           bool `json:"giftedGems"`
	GiftedSubscription   bool `json:"giftedSubscription"`
	InvitedParty         bool `json:"invitedParty"`
	InvitedGuild         bool `json:"invitedGuild"`
	QuestStarted         bool `json:"questStarted"`
	InvitedQuest         bool `json:"invitedQuest"`
	MajorUpdates         bool `json:"majorUpdates"`
	MentionParty         bool `json:"mentionParty"`
	MentionJoinedGuild   bool `json:"mentionJoinedGuild"`
	MentionUnjoinedGuild bool `json:"mentionUnjoinedGuild"`
	PartyActivity        bool `json:"partyActivity"`
	ContentRelease       bool `json:"contentRelease"`
}

// ListApiv3UserOkJSONResponseDataPreferencesSuppressModals defines a model
type ListApiv3UserOkJSONResponseDataPreferencesSuppressModals struct {
	LevelUp  bool `json:"levelUp"`
	HatchPet bool `json:"hatchPet"`
	RaisePet bool `json:"raisePet"`
	Streak   bool `json:"streak"`
}

// ListApiv3UserOkJSONResponseDataPreferencesTasks defines a model
type ListApiv3UserOkJSONResponseDataPreferencesTasks struct {
	ActiveFilter      ListApiv3UserOkJSONResponseDataPreferencesTasksActiveFilter `json:"activeFilter"`
	GroupByChallenge  bool                                                        `json:"groupByChallenge"`
	ConfirmScoreNotes bool                                                        `json:"confirmScoreNotes"`
	MirrorGroupTasks  []struct{}                                                  `json:"mirrorGroupTasks"`
}

// ListApiv3UserOkJSONResponseDataPreferencesTasksActiveFilter defines a model
type ListApiv3UserOkJSONResponseDataPreferencesTasksActiveFilter struct {
	Habit  string `json:"habit,omitzero"`
	Daily  string `json:"daily,omitzero"`
	Todo   string `json:"todo,omitzero"`
	Reward string `json:"reward,omitzero"`
}

// ListApiv3UserOkJSONResponseDataProfile defines a model
type ListApiv3UserOkJSONResponseDataProfile struct {
	Name string `json:"name,omitzero"`
}

// ListApiv3UserOkJSONResponseDataPurchased defines a model
type ListApiv3UserOkJSONResponseDataPurchased struct {
	Plan       ListApiv3UserOkJSONResponseDataPurchasedPlan       `json:"plan"`
	TxnCount   int                                                `json:"txnCount"`
	Background ListApiv3UserOkJSONResponseDataPurchasedBackground `json:"background"`
	Shirt      struct{}                                           `json:"shirt"`
	Hair       struct{}                                           `json:"hair"`
	Skin       struct{}                                           `json:"skin"`
	Ads        bool                                               `json:"ads"`
}

// ListApiv3UserOkJSONResponseDataPurchasedBackground defines a model
type ListApiv3UserOkJSONResponseDataPurchasedBackground struct {
	Yellow           bool `json:"yellow"`
	Red              bool `json:"red"`
	Purple           bool `json:"purple"`
	Green            bool `json:"green"`
	Blue             bool `json:"blue"`
	Violet           bool `json:"violet"`
	OnAStrangePlanet bool `json:"on_a_strange_planet"`
}

// ListApiv3UserOkJSONResponseDataPurchasedPlan defines a model
type ListApiv3UserOkJSONResponseDataPurchasedPlan struct {
	Consecutive     ListApiv3UserOkJSONResponseDataPurchasedPlanConsecutive `json:"consecutive"`
	MysteryItems    []struct{}                                              `json:"mysteryItems"`
	GemsBought      int                                                     `json:"gemsBought"`
	ExtraMonths     int                                                     `json:"extraMonths"`
	Quantity        int                                                     `json:"quantity"`
	DateUpdated     time.Time                                               `json:"dateUpdated,omitzero"`
	PerkMonthCount  int                                                     `json:"perkMonthCount"`
	CumulativeCount int                                                     `json:"cumulativeCount"`
}

// ListApiv3UserOkJSONResponseDataPurchasedPlanConsecutive defines a model
type ListApiv3UserOkJSONResponseDataPurchasedPlanConsecutive struct {
	Trinkets    int `json:"trinkets"`
	GemCapExtra int `json:"gemCapExtra"`
	Offset      int `json:"offset"`
	Count       int `json:"count"`
}

// ListApiv3UserOkJSONResponseDataPushDevices defines a model
type ListApiv3UserOkJSONResponseDataPushDevices []ListApiv3UserOkJSONResponseDataPushDevicesItem

// ListApiv3UserOkJSONResponseDataPushDevicesItem defines a model
type ListApiv3UserOkJSONResponseDataPushDevicesItem struct {
	RegID     string    `json:"regId,omitzero"`
	Type      string    `json:"type,omitzero"`
	UpdatedAt time.Time `json:"updatedAt,omitzero"`
	CreatedAt time.Time `json:"createdAt,omitzero"`
}

// ListApiv3UserOkJSONResponseDataStats defines a model
type ListApiv3UserOkJSONResponseDataStats struct {
	Buffs       ListApivUserDataStatsBuffs    `json:"buffs"`
	Training    ListApivUserDataStatsTraining `json:"training"`
	Per         int                           `json:"per"`
	Int         int                           `json:"int"`
	Con         int                           `json:"con"`
	Str         int                           `json:"str"`
	Points      int                           `json:"points"`
	Class       string                        `json:"class,omitzero"`
	Lvl         int                           `json:"lvl"`
	Gp          float64                       `json:"gp"`
	Exp         int                           `json:"exp"`
	Mp          float64                       `json:"mp"`
	Hp          float64                       `json:"hp"`
	ToNextLevel int                           `json:"toNextLevel"`
	MaxHealth   int                           `json:"maxHealth"`
	MaxMp       int                           `json:"maxMP"`
}

// ListApiv3UserOkJSONResponseDataTags defines a model
type ListApiv3UserOkJSONResponseDataTags []ListApiv3UserOkJSONResponseDataTagsItem

// ListApiv3UserOkJSONResponseDataTagsItem defines a model
type ListApiv3UserOkJSONResponseDataTagsItem struct {
	Name      string    `json:"name,omitzero"`
	ID        uuid.UUID `json:"id,omitzero"`
	Challenge bool      `json:"challenge,omitempty"`
}

// ListApiv3UserOkJSONResponseDataTasksOrder defines a model
type ListApiv3UserOkJSONResponseDataTasksOrder struct {
	Rewards []uuid.UUID `json:"rewards"`
	Todos   []uuid.UUID `json:"todos"`
	Dailys  []uuid.UUID `json:"dailys"`
	Habits  []uuid.UUID `json:"habits"`
}

// ListApivUserDataHistoryExp defines a model
type ListApivUserDataHistoryExp []ListApivUserDataHistoryExpItem

// ListApivUserDataHistoryExpItem defines a model
type ListApivUserDataHistoryExpItem struct {
	Date  time.Time `json:"date"`
	Value float64   `json:"value"`
}

// ListApivUserDataInboxMessagesfeffAcddbf defines a model
type ListApivUserDataInboxMessagesfeffAcddbf struct {
	UnderscoreID uuid.UUID `json:"_id,omitzero"`
	Sent         bool      `json:"sent"`
	FlagCount    int       `json:"flagCount"`
	User         string    `json:"user,omitzero"`
	Backer       struct{}  `json:"backer"`
	Contributor  struct{}  `json:"contributor"`
	UUID         uuid.UUID `json:"uuid,omitzero"`
	Flags        struct{}  `json:"flags"`
	Likes        struct{}  `json:"likes"`
	Timestamp    time.Time `json:"timestamp,omitzero"`
	Text         string    `json:"text,omitzero"`
	ID           uuid.UUID `json:"id,omitzero"`
	OwnerID      uuid.UUID `json:"ownerId,omitzero"`
}

// ListApivUserDataStatsBuffs defines a model
type ListApivUserDataStatsBuffs struct {
	Str            int  `json:"str"`
	Int            int  `json:"int"`
	Per            int  `json:"per"`
	Con            int  `json:"con"`
	Stealth        int  `json:"stealth"`
	Streaks        bool `json:"streaks"`
	Seafoam        bool `json:"seafoam"`
	ShinySeed      bool `json:"shinySeed"`
	Snowball       bool `json:"snowball"`
	SpookySparkles bool `json:"spookySparkles"`
}

// ListApivUserDataStatsTraining defines a model
type ListApivUserDataStatsTraining struct {
	Con int     `json:"con"`
	Str float64 `json:"str"`
	Per int     `json:"per"`
	Int int     `json:"int"`
}

// PostApiv3TaskScoreUpNotFoundJSONResponse defines a model
type PostApiv3TaskScoreUpNotFoundJSONResponse struct {
	Success bool   `json:"success"`
	Err     string `json:"error,omitzero"`
	Message string `json:"message,omitzero"`
}

// PostApiv3TaskScoreUpOkJSONResponse defines a model
type PostApiv3TaskScoreUpOkJSONResponse struct {
	Success       bool                                   `json:"success"`
	Data          PostApiv3TaskScoreUpOkJSONResponseData `json:"data"`
	Notifications []struct{}                             `json:"notifications"`
	UserV         *int                                   `json:"userV,omitempty"`
	AppVersion    string                                 `json:"appVersion,omitzero"`
}

// PostApiv3TaskScoreUpOkJSONResponseData defines a model
type PostApiv3TaskScoreUpOkJSONResponseData struct {
	Delta         float64                                   `json:"delta"`
	UnderscoreTmp PostApiv3TaskScoreUpOkJSONResponseDataTmp `json:"_tmp"`
	Hp            float64                                   `json:"hp"`
	Mp            float64                                   `json:"mp"`
	Exp           float64                                   `json:"exp"`
	Gp            float64                                   `json:"gp"`
	Lvl           int                                       `json:"lvl"`
	Class         string                                    `json:"class,omitzero"`
	Points        int                                       `json:"points"`
	Str           int                                       `json:"str"`
	Con           int                                       `json:"con"`
	Int           int                                       `json:"int"`
	Per           int                                       `json:"per"`
	Buffs         ListApivUserDataStatsBuffs                `json:"buffs"`
	Training      ListApivUserDataStatsTraining             `json:"training"`
}

// PostApiv3TaskScoreUpOkJSONResponseDataTmp defines a model
type PostApiv3TaskScoreUpOkJSONResponseDataTmp struct {
	Quest       PostApiv3TaskScoreUpOkJSONResponseDataTmpQuest `json:"quest"`
	Drop        PostApiv3TaskScoreUpOkJSONResponseDataTmpDrop  `json:"drop"`
	StreakBonus *float64                                       `json:"streakBonus,omitempty"`
}

// PostApiv3TaskScoreUpOkJSONResponseDataTmpDrop defines a model
type PostApiv3TaskScoreUpOkJSONResponseDataTmpDrop struct {
	Target  string `json:"target,omitzero"`
	CanDrop bool   `json:"canDrop"`
	Value   int    `json:"value"`
	Key     string `json:"key,omitzero"`
	Type    string `json:"type,omitzero"`
	Dialog  string `json:"dialog,omitzero"`
}

// PostApiv3TaskScoreUpOkJSONResponseDataTmpQuest defines a model
type PostApiv3TaskScoreUpOkJSONResponseDataTmpQuest struct {
	ProgressDelta float64 `json:"progressDelta"`
	Collection    int     `json:"collection"`
}
