// This file provides types for the API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package decoding

import (
	"bytes"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"fmt"
	"maps"
	"slices"
	"strconv"
)

var jsonOpts = json.JoinOptions(
	json.RejectUnknownMembers(true),
)

// jsonOptsLenient is jsonOpts accepting members the specification does not know, as debug mode decodes once a strict
// decoding failed, and as a caller's own type of a result is decoded.
var jsonOptsLenient = json.JoinOptions(jsonOpts, json.RejectUnknownMembers(false))

// Condition defines a model
type Condition struct {
	Equals       string `json:"equals,omitzero"`
	DoesNotEqual string `json:"does_not_equal,omitzero"`
}

// CoverResponse defines a model
type CoverResponse struct {
	Type     CoverResponseType `json:"type"`
	External *Link             `json:"external,omitzero"`
	File     *Link             `json:"file,omitzero"`
}

// CoverResponseType is a value of CoverResponse's type, naming the members it holds.
type CoverResponseType string

const (
	CoverResponseTypeExternal CoverResponseType = "external"
	CoverResponseTypeFile     CoverResponseType = "file"
)

// Valid indicates whether the value is a known member of the CoverResponseType enum.
func (e CoverResponseType) Valid() bool {
	_, ok := tagsOfCoverResponse[string(e)]
	return ok
}

// tagsOfCoverResponse holds, for each value of type, the members of its alternative's own, each with whether it is required.
var tagsOfCoverResponse = map[string]map[string]bool{
	"external": {"external": true},
	"file":     {"file": true},
}

// taggedMembers returns those of the members of an alternative's own that are set.
func (v *CoverResponse) taggedMembers() []string {
	var set []string
	if v.External != nil {
		set = append(set, "external")
	}
	if v.File != nil {
		set = append(set, "file")
	}

	return set
}

// UnmarshalJSONFrom implements [json.UnmarshalerFrom]. It decodes the members, then checks that of those of an
// alternative's own, only those of the one type names are set.
func (v *CoverResponse) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	type plain CoverResponse

	*v = CoverResponse{}
	if err := json.UnmarshalDecode(dec, (*plain)(v), jsonOptsOf(dec)); err != nil {
		return err
	}

	return jsonCheckTag("type", string(v.Type), tagsOfCoverResponse, v.taggedMembers(), jsonStrict(dec))
}

// MarshalJSONTo implements [json.MarshalerTo]. It checks the members as decoding does; with type left empty, it sends
// the value whose member is set.
func (v *CoverResponse) MarshalJSONTo(enc *jsontext.Encoder) error {
	type plain CoverResponse

	out, set := *v, v.taggedMembers()
	if tag, ok := jsonInferTag(tagsOfCoverResponse, set); ok && out.Type == "" {
		out.Type = CoverResponseType(tag)
	}

	if err := jsonCheckTag("type", string(out.Type), tagsOfCoverResponse, set, true); err != nil {
		return err
	}

	return json.MarshalEncode(enc, (*plain)(&out), jsonOpts)
}

// Emoji defines a model
type Emoji struct {
	Emoji string `json:"emoji"`
}

// IconResponse defines a model
// IconResponse is an untagged oneOf union: exactly one field is set after unmarshaling.
type IconResponse struct {
	Emoji *Emoji
	Link  *Link
}

// UnmarshalJSONFrom implements [json.UnmarshalerFrom].
func (v *IconResponse) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = IconResponse{}

	opts := jsonOptsOf(dec)
	strict := jsonStrict(dec)

	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}

	var matched int

	// leniently, more than one may match, and the first does
	if strict || matched == 0 {
		var vv Emoji
		if err := json.Unmarshal(raw, &vv, opts); err == nil {
			v.Emoji = &vv
			matched++
		}
	}

	// leniently, more than one may match, and the first does
	if strict || matched == 0 {
		var vv Link
		if err := json.Unmarshal(raw, &vv, opts); err == nil {
			v.Link = &vv
			matched++
		}
	}

	if matched != 1 {
		return &json.SemanticError{Err: fmt.Errorf("matches %d of its alternatives, want exactly one", matched)}
	}

	return nil
}

// MarshalJSONTo implements [json.MarshalerTo]. It emits the first non-nil variant.
func (v *IconResponse) MarshalJSONTo(enc *jsontext.Encoder) error {
	switch {
	case v.Emoji != nil:
		return json.MarshalEncode(enc, v.Emoji, jsonOpts)
	case v.Link != nil:
		return json.MarshalEncode(enc, v.Link, jsonOpts)
	}

	return &json.SemanticError{Err: errors.New("no alternative set")}
}

// Link defines a model
type Link struct {
	URL string `json:"url"`
}

// Page defines a model
type Page struct {
	Object   string         `json:"object"`
	ID       string         `json:"id"`
	Cover    *CoverResponse `json:"cover"`
	Icon     *IconResponse  `json:"icon"`
	Position Position       `json:"position"`
}

// PageOrPartial defines a model
// PageOrPartial is an untagged anyOf union: at least one field is set after unmarshaling.
type PageOrPartial struct {
	Page        *Page
	PartialPage *PartialPage
}

// UnmarshalJSONFrom implements [json.UnmarshalerFrom].
func (v *PageOrPartial) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = PageOrPartial{}

	opts := jsonOptsOf(dec)

	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}

	var matched int

	{
		var vv Page
		if err := json.Unmarshal(raw, &vv, opts); err == nil {
			v.Page = &vv
			matched++
		}
	}

	{
		var vv PartialPage
		if err := json.Unmarshal(raw, &vv, opts); err == nil {
			v.PartialPage = &vv
			matched++
		}
	}

	if matched == 0 {
		return &json.SemanticError{Err: errors.New("matches none of its alternatives")}
	}

	return nil
}

// MarshalJSONTo implements [json.MarshalerTo]. It emits the first non-nil variant.
func (v *PageOrPartial) MarshalJSONTo(enc *jsontext.Encoder) error {
	switch {
	case v.Page != nil:
		return json.MarshalEncode(enc, v.Page, jsonOpts)
	case v.PartialPage != nil:
		return json.MarshalEncode(enc, v.PartialPage, jsonOpts)
	}

	return &json.SemanticError{Err: errors.New("no alternative set")}
}

// Pair defines a model
type Pair struct {
	Item0 string
	Item1 int
}

func (a *Pair) Items(yield func(int, any) bool) {
	for i, v := range []any{&a.Item0, &a.Item1} {
		if !yield(i, v) {
			return
		}
	}
}

// UnmarshalJSONFrom implements [json.UnmarshalerFrom].
func (a *Pair) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if k := dec.PeekKind(); k != jsontext.KindBeginArray {
		return &json.SemanticError{JSONKind: k}
	}

	if _, err := dec.ReadToken(); err != nil {
		return err
	}

	for _, f := range a.Items {
		if dec.PeekKind() == jsontext.KindEndArray {
			return &json.SemanticError{Err: fmt.Errorf("array shorter than 2")}
		}

		if err := json.UnmarshalDecode(dec, f); err != nil {
			return err
		}
	}

	if k := dec.PeekKind(); k != jsontext.KindEndArray {
		return &json.SemanticError{JSONKind: k, Err: fmt.Errorf("array longer than 2")}
	}

	_, err := dec.ReadToken()
	return err
}

// MarshalJSONTo implements [json.MarshalerTo].
func (a Pair) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginArray); err != nil {
		return err
	}

	for _, v := range a.Items {
		if err := json.MarshalEncode(enc, v); err != nil {
			return err
		}
	}

	if err := enc.WriteToken(jsontext.EndArray); err != nil {
		return err
	}

	return nil
}

// PartialPage defines a model
type PartialPage struct {
	Object string `json:"object"`
	ID     string `json:"id"`
}

// Position defines a model
// Position is an untagged oneOf union: exactly one field is set after unmarshaling.
type Position struct {
	String []string
	Pair   *Pair
}

// UnmarshalJSONFrom implements [json.UnmarshalerFrom].
func (v *Position) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	*v = Position{}

	opts := jsonOptsOf(dec)
	strict := jsonStrict(dec)

	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}

	var matched int

	// leniently, more than one may match, and the first does
	if strict || matched == 0 {
		var vv []string
		if err := json.Unmarshal(raw, &vv, opts); err == nil {
			v.String = vv
			matched++
		}
	}

	// leniently, more than one may match, and the first does
	if strict || matched == 0 {
		var vv Pair
		if err := json.Unmarshal(raw, &vv, opts); err == nil {
			v.Pair = &vv
			matched++
		}
	}

	if matched != 1 {
		return &json.SemanticError{Err: fmt.Errorf("matches %d of its alternatives, want exactly one", matched)}
	}

	return nil
}

// MarshalJSONTo implements [json.MarshalerTo]. It emits the first non-nil variant.
func (v *Position) MarshalJSONTo(enc *jsontext.Encoder) error {
	switch {
	case v.String != nil:
		return json.MarshalEncode(enc, v.String, jsonOpts)
	case v.Pair != nil:
		return json.MarshalEncode(enc, v.Pair, jsonOpts)
	}

	return &json.SemanticError{Err: errors.New("no alternative set")}
}

// PropertyFilter defines a model
type PropertyFilter struct {
	Property string             `json:"property"`
	Type     PropertyFilterType `json:"type,omitzero"`
	Select   *Condition         `json:"select,omitzero"`
	Number   *Condition         `json:"number,omitzero"`
}

// PropertyFilterType is a value of PropertyFilter's type, naming the members it holds.
type PropertyFilterType string

const (
	PropertyFilterTypeSelect PropertyFilterType = "select"
	PropertyFilterTypeNumber PropertyFilterType = "number"
)

// Valid indicates whether the value is a known member of the PropertyFilterType enum.
func (e PropertyFilterType) Valid() bool {
	_, ok := tagsOfPropertyFilter[string(e)]
	return ok
}

// tagsOfPropertyFilter holds, for each value of type, the members of its alternative's own, each with whether it is required.
var tagsOfPropertyFilter = map[string]map[string]bool{
	"select": {"select": true},
	"number": {"number": true},
}

// taggedMembers returns those of the members of an alternative's own that are set.
func (v *PropertyFilter) taggedMembers() []string {
	var set []string
	if v.Select != nil {
		set = append(set, "select")
	}
	if v.Number != nil {
		set = append(set, "number")
	}

	return set
}

// UnmarshalJSONFrom implements [json.UnmarshalerFrom]. It decodes the members, then checks that of those of an
// alternative's own, only those of the one type names are set.
func (v *PropertyFilter) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	type plain PropertyFilter

	*v = PropertyFilter{}
	if err := json.UnmarshalDecode(dec, (*plain)(v), jsonOptsOf(dec)); err != nil {
		return err
	}

	// type may be left out, and is then the value whose member is set, as encoding infers it
	if tag, ok := jsonInferTag(tagsOfPropertyFilter, v.taggedMembers()); ok && v.Type == "" {
		v.Type = PropertyFilterType(tag)
	}

	return jsonCheckTag("type", string(v.Type), tagsOfPropertyFilter, v.taggedMembers(), jsonStrict(dec))
}

// MarshalJSONTo implements [json.MarshalerTo]. It checks the members as decoding does; with type left empty, it sends
// the value whose member is set.
func (v *PropertyFilter) MarshalJSONTo(enc *jsontext.Encoder) error {
	type plain PropertyFilter

	out, set := *v, v.taggedMembers()
	if tag, ok := jsonInferTag(tagsOfPropertyFilter, set); ok && out.Type == "" {
		out.Type = PropertyFilterType(tag)
	}

	if err := jsonCheckTag("type", string(out.Type), tagsOfPropertyFilter, set, true); err != nil {
		return err
	}

	return json.MarshalEncode(enc, (*plain)(&out), jsonOpts)
}

// jsonStrict reports whether dec rejects members the specification does not know, as it does unless told otherwise.
func jsonStrict(dec *jsontext.Decoder) bool {
	v, ok := json.GetOption(dec.Options(), json.RejectUnknownMembers)
	return v || !ok
}

// jsonOptsOf is jsonOpts, or jsonOptsLenient where dec accepts members the specification does not know.
func jsonOptsOf(dec *jsontext.Decoder) json.Options {
	if jsonStrict(dec) {
		return jsonOpts
	}

	return jsonOptsLenient
}

// jsonUnknownName reports a member no part of the type declares, as encoding/json reports one of a struct.
func jsonUnknownName(name string) error {
	return &json.SemanticError{JSONKind: jsontext.KindString, Err: fmt.Errorf("%w %q", json.ErrUnknownName, name)}
}

// jsonMissing reports a member the type needs and the object lacks.
func jsonMissing(name string) error {
	return &json.SemanticError{JSONKind: jsontext.KindBeginObject, Err: fmt.Errorf("missing object member name %q", name)}
}

// jsonUnknownValue reports a value of the discriminator that names no alternative.
func jsonUnknownValue(name, value string) error {
	return &json.SemanticError{JSONKind: jsontext.KindString, JSONValue: jsontext.Value(strconv.Quote(value)), Err: fmt.Errorf("unknown value of %q", name)}
}

// jsonFirstMember reads the opening of a JSON object and its member name, which must have a string value. It returns
// the string, the value as written, and the decoder to read the object's further members from: dec itself when name
// comes first, the fast way, and otherwise one over the object read whole, with name moved to the front.
func jsonFirstMember(dec *jsontext.Decoder, name string) (string, jsontext.Value, *jsontext.Decoder, error) {
	if tok, err := dec.ReadToken(); err != nil {
		return "", nil, nil, err
	} else if tok.Kind() != jsontext.KindBeginObject {
		return "", nil, nil, &json.SemanticError{JSONKind: tok.Kind(), Err: errors.New("want an object")}
	}

	if dec.PeekKind() == jsontext.KindEndObject {
		return "", nil, nil, jsonMissing(name)
	}

	tok, err := dec.ReadToken()
	if err != nil {
		return "", nil, nil, err
	}

	if got := tok.String(); got != name {
		// read the rest of the object, and start again with name first
		var buf bytes.Buffer
		enc := jsontext.NewEncoder(&buf)
		if err := enc.WriteToken(jsontext.BeginObject); err != nil {
			return "", nil, nil, err
		}

		if err := enc.WriteToken(jsontext.String(got)); err != nil {
			return "", nil, nil, err
		}

		for dec.PeekKind() != jsontext.KindEndObject {
			val, err := dec.ReadValue()
			if err != nil {
				return "", nil, nil, err
			}

			if err := enc.WriteValue(val); err != nil {
				return "", nil, nil, err
			}

			if dec.PeekKind() == jsontext.KindEndObject {
				break
			}

			tok, err := dec.ReadToken()
			if err != nil {
				return "", nil, nil, err
			}

			if err := enc.WriteToken(tok); err != nil {
				return "", nil, nil, err
			}
		}

		if _, err := dec.ReadToken(); err != nil { // the end of the object
			return "", nil, nil, err
		}

		if err := enc.WriteToken(jsontext.EndObject); err != nil {
			return "", nil, nil, err
		}

		ordered, err := jsonFirst(buf.Bytes(), name, "")
		if err != nil {
			return "", nil, nil, err
		}

		return jsonFirstMember(jsontext.NewDecoder(bytes.NewReader(ordered), dec.Options()), name)
	}

	val, err := dec.ReadValue()
	if err != nil {
		return "", nil, nil, err
	}

	var tag string
	if err := json.Unmarshal(val, &tag); err != nil {
		return "", nil, nil, &json.SemanticError{JSONKind: val.Kind(), Err: fmt.Errorf("member %q is not a string", name)}
	}

	return tag, val.Clone(), dec, nil
}

// jsonMembersFrom decodes the first member, already read, and every further member of the object dec is in, each
// into the field decode declares for it; a member it does not declare is an error, unless dec is lenient.
func jsonMembersFrom(dec *jsontext.Decoder, firstName string, first jsontext.Value, decode func(*jsontext.Decoder, string) (bool, error)) error {
	strict := jsonStrict(dec)

	if ok, err := decode(jsontext.NewDecoder(bytes.NewReader(first), dec.Options()), firstName); err != nil {
		return err
	} else if !ok && strict {
		return jsonUnknownName(firstName)
	}

	for dec.PeekKind() != jsontext.KindEndObject {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}

		name := tok.String() // a token is void once the decoder reads on

		if ok, err := decode(dec, name); err != nil {
			return err
		} else if !ok && strict {
			return jsonUnknownName(name)
		} else if !ok {
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}

	_, err := dec.ReadToken()
	return err
}

// jsonPart is one of the parts an object decodes into: the members it declares and how it decodes one of them.
type jsonPart struct {
	members map[string]bool
	decode  func(*jsontext.Decoder, string) (bool, error)
}

// jsonPartsFrom is jsonMembersFrom for an object that several parts declare members of. A member one part declares
// decodes straight from dec; one several declare is read once and decoded into each.
func jsonPartsFrom(dec *jsontext.Decoder, firstName string, first jsontext.Value, parts []jsonPart) error {
	member := func(name string, val jsontext.Value) error {
		var declaring []jsonPart
		for _, p := range parts {
			if p.members[name] {
				declaring = append(declaring, p)
			}
		}

		switch {
		case len(declaring) > 0:
		case jsonStrict(dec):
			return jsonUnknownName(name)
		case val == nil:
			return dec.SkipValue()
		default:
			return nil
		}

		if val == nil && len(declaring) == 1 {
			_, err := declaring[0].decode(dec, name)
			return err
		}

		if val == nil {
			v, err := dec.ReadValue()
			if err != nil {
				return err
			}

			val = v.Clone()
		}

		for _, p := range declaring {
			if _, err := p.decode(jsontext.NewDecoder(bytes.NewReader(val), dec.Options()), name); err != nil {
				return err
			}
		}

		return nil
	}

	if err := member(firstName, first); err != nil {
		return err
	}

	for dec.PeekKind() != jsontext.KindEndObject {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}

		if err := member(tok.String(), nil); err != nil {
			return err
		}
	}

	_, err := dec.ReadToken()
	return err
}

// jsonFirst returns the JSON object raw with its member name first, as decoding by a discriminator wants it. If value
// is known, the member must have it, and is written in if raw lacks it or leaves it empty. raw is returned as it is if
// all is in order.
func jsonFirst(raw jsontext.Value, name, value string) (jsontext.Value, error) {
	dec := jsontext.NewDecoder(bytes.NewReader(raw))
	if _, err := dec.ReadToken(); err != nil {
		return nil, err
	}

	if dec.PeekKind() != jsontext.KindEndObject {
		tok, err := dec.ReadToken()
		if err != nil {
			return nil, err
		}

		if tok.String() == name {
			if value == "" {
				return raw, nil
			}

			val, err := dec.ReadToken()
			if err != nil {
				return nil, err
			}

			switch got := val.String(); got {
			case value:
				return raw, nil
			case "": // left for the union to fill in, below
			default:
				return nil, &json.SemanticError{Err: fmt.Errorf("member %q is %q, want %q", name, got, value)}
			}
		}
	}

	names, err := jsonMembers(raw)
	if err != nil {
		return nil, err
	}

	var first jsontext.Value
	switch {
	case slices.Contains(names, name):
		if first, err = jsonSelect(raw, map[string]bool{name: true}); err != nil {
			return nil, err
		}

		if value == "" {
			break
		}

		got, err := jsonMemberString(first, name)
		switch {
		case err != nil:
			return nil, err
		case got == "": // left empty: the union knows what it holds
			rest := make(map[string]bool, len(names))
			for _, n := range names {
				rest[n] = n != name
			}

			if raw, err = jsonSelect(raw, rest); err != nil {
				return nil, err
			}

			if first, err = json.Marshal(map[string]string{name: value}); err != nil {
				return nil, err
			}
		case got != value:
			return nil, &json.SemanticError{Err: fmt.Errorf("member %q is %q, want %q", name, got, value)}
		}
	case value != "":
		member, err := json.Marshal(map[string]string{name: value})
		if err != nil {
			return nil, err
		}

		first = member
	default:
		return nil, jsonMissing(name)
	}

	return jsonMerge(first, raw)
}

// jsonMemberString returns the string value of the member name of the JSON object raw, reading no further than it.
func jsonMemberString(raw jsontext.Value, name string) (string, error) {
	dec := jsontext.NewDecoder(bytes.NewReader(raw))
	if tok, err := dec.ReadToken(); err != nil {
		return "", err
	} else if tok.Kind() != jsontext.KindBeginObject {
		return "", &json.SemanticError{JSONKind: tok.Kind(), Err: errors.New("want an object")}
	}

	for dec.PeekKind() != jsontext.KindEndObject {
		tok, err := dec.ReadToken()
		if err != nil {
			return "", err
		}

		if tok.String() != name {
			if err := dec.SkipValue(); err != nil {
				return "", err
			}

			continue
		}

		val, err := dec.ReadToken()
		if err != nil {
			return "", err
		}

		if val.Kind() != jsontext.KindString {
			return "", &json.SemanticError{JSONKind: val.Kind(), Err: fmt.Errorf("member %q is not a string", name)}
		}

		return val.String(), nil
	}

	return "", jsonMissing(name)
}

// jsonMembers returns the names of the members of the JSON object raw, in order.
func jsonMembers(raw jsontext.Value) ([]string, error) {
	dec := jsontext.NewDecoder(bytes.NewReader(raw))
	if tok, err := dec.ReadToken(); err != nil {
		return nil, err
	} else if tok.Kind() != jsontext.KindBeginObject {
		return nil, &json.SemanticError{JSONKind: tok.Kind(), Err: errors.New("want an object")}
	}

	var names []string
	for dec.PeekKind() != jsontext.KindEndObject {
		tok, err := dec.ReadToken()
		if err != nil {
			return nil, err
		}

		names = append(names, tok.String())

		if err := dec.SkipValue(); err != nil {
			return nil, err
		}
	}

	return names, nil
}

// jsonSelect returns the JSON object raw with only the members keep holds.
func jsonSelect(raw jsontext.Value, keep map[string]bool) (jsontext.Value, error) {
	dec := jsontext.NewDecoder(bytes.NewReader(raw))
	if _, err := dec.ReadToken(); err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	enc := jsontext.NewEncoder(&buf)
	if err := enc.WriteToken(jsontext.BeginObject); err != nil {
		return nil, err
	}

	for dec.PeekKind() != jsontext.KindEndObject {
		tok, err := dec.ReadToken()
		if err != nil {
			return nil, err
		}

		name := tok.String() // a token is void once the decoder reads on

		val, err := dec.ReadValue()
		if err != nil {
			return nil, err
		}

		if !keep[name] {
			continue
		}

		if err := enc.WriteToken(jsontext.String(name)); err != nil {
			return nil, err
		}

		if err := enc.WriteValue(val); err != nil {
			return nil, err
		}
	}

	if err := enc.WriteToken(jsontext.EndObject); err != nil {
		return nil, err
	}

	return bytes.TrimSpace(buf.Bytes()), nil
}

// jsonMerge returns the members of the JSON objects a and b in one object. A member both hold must have the same
// value in each.
func jsonMerge(a, b jsontext.Value) (jsontext.Value, error) {
	var buf bytes.Buffer
	enc := jsontext.NewEncoder(&buf)
	if err := enc.WriteToken(jsontext.BeginObject); err != nil {
		return nil, err
	}

	written := map[string]jsontext.Value{}
	for _, raw := range []jsontext.Value{a, b} {
		dec := jsontext.NewDecoder(bytes.NewReader(raw))
		if _, err := dec.ReadToken(); err != nil {
			return nil, err
		}

		for dec.PeekKind() != jsontext.KindEndObject {
			tok, err := dec.ReadToken()
			if err != nil {
				return nil, err
			}

			name := tok.String() // a token is void once the decoder reads on

			val, err := dec.ReadValue()
			if err != nil {
				return nil, err
			}
			if prev, ok := written[name]; ok {
				if err := prev.Canonicalize(); err != nil {
					return nil, err
				}

				cur := val.Clone()
				if err := cur.Canonicalize(); err != nil {
					return nil, err
				}

				if !bytes.Equal(prev, cur) {
					return nil, &json.SemanticError{Err: fmt.Errorf("member %q is %s in one part and %s in another", name, prev, cur)}
				}

				continue
			}

			written[name] = val.Clone()

			if err := enc.WriteToken(jsontext.String(name)); err != nil {
				return nil, err
			}

			if err := enc.WriteValue(val); err != nil {
				return nil, err
			}
		}
	}

	if err := enc.WriteToken(jsontext.EndObject); err != nil {
		return nil, err
	}

	return bytes.TrimSpace(buf.Bytes()), nil
}

// jsonVariant is an alternative of a union: its value of the discriminator, the members it declares and those it
// requires.
type jsonVariant struct {
	value    string
	members  map[string]bool
	required []string
}

// jsonChooseVariants returns the alternatives the JSON object raw is: the one its discriminator names, if there is
// one, else those whose required members it has and whose members it holds, besides those of plain. Every member
// must belong to plain or to a chosen alternative. Not strict, a member nothing declares is left out of the choice,
// and of several alternatives of a oneOf the first is chosen.
func jsonChooseVariants(raw jsontext.Value, discriminator string, variants []jsonVariant, plain map[string]bool, oneOf, strict bool) ([]int, error) {
	names, err := jsonMembers(raw)
	if err != nil {
		return nil, err
	}

	if !strict {
		names = slices.DeleteFunc(names, func(n string) bool {
			return !plain[n] && !slices.ContainsFunc(variants, func(v jsonVariant) bool { return v.members[n] })
		})
	}

	present := make(map[string]bool, len(names))
	for _, n := range names {
		present[n] = true
	}

	var chosen []int
	if discriminator != "" {
		tag, err := jsonMemberString(raw, discriminator)
		if err != nil {
			return nil, err
		}

		for i, v := range variants {
			if v.value == tag {
				chosen = append(chosen, i)
			}
		}

		if len(chosen) == 0 {
			return nil, jsonUnknownValue(discriminator, tag)
		}
	} else {
	variants:
		for i, v := range variants {
			for _, r := range v.required {
				if !present[r] {
					continue variants
				}
			}

			for _, n := range names {
				if !plain[n] && !v.members[n] {
					continue variants
				}
			}

			chosen = append(chosen, i)
		}

		switch {
		case len(chosen) == 0:
			return nil, &json.SemanticError{Err: errors.New("matches none of its alternatives")}
		case oneOf && len(chosen) > 1 && strict:
			return nil, &json.SemanticError{Err: fmt.Errorf("matches %d of its alternatives, want exactly one", len(chosen))}
		case oneOf:
			chosen = chosen[:1]
		}
	}

	for _, n := range names {
		if plain[n] {
			continue
		}

		known := false
		for _, i := range chosen {
			known = known || variants[i].members[n]
		}

		if !known {
			return nil, jsonUnknownName(n)
		}
	}

	return chosen, nil
}

// jsonCheckTag reports an error unless set, the members of an alternative's own that are set, holds only members of
// the alternative the value tag of the tag name names, and every one of them it requires. Not strict, set may hold
// others too.
func jsonCheckTag(name, tag string, tags map[string]map[string]bool, set []string, strict bool) error {
	members, ok := tags[tag]
	switch {
	case tag == "":
		return jsonMissing(name)
	case !ok:
		return jsonUnknownValue(name, tag)
	}

	for _, s := range set {
		if _, ok := members[s]; strict && !ok {
			return &json.SemanticError{JSONKind: jsontext.KindBeginObject, Err: fmt.Errorf("%s %q does not allow member %q", name, tag, s)}
		}
	}

	for _, m := range slices.Sorted(maps.Keys(members)) {
		if members[m] && !slices.Contains(set, m) {
			return jsonMissing(m)
		}
	}

	return nil
}

// jsonInferTag returns the value of a tag whose alternative is the one of tags that set, the members of an
// alternative's own that are set, names: the one set member is a value whose alternative allows all of set.
func jsonInferTag(tags map[string]map[string]bool, set []string) (string, bool) {
	tag := ""

	for _, s := range set {
		members, ok := tags[s]
		if !ok || !allIn(set, members) {
			continue
		}

		if tag != "" {
			return "", false
		}

		tag = s
	}

	return tag, tag != ""
}

// allIn reports whether every one of names is a key of m.
func allIn(names []string, m map[string]bool) bool {
	for _, n := range names {
		if _, ok := m[n]; !ok {
			return false
		}
	}

	return true
}
