// This file provides types for the API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package openskynetwork

import (
	"encoding/json/v2"
)

var jsonOpts = json.JoinOptions(
	json.RejectUnknownMembers(true),
)

// ListAPIStatesAllOk defines a model
type ListAPIStatesAllOk struct {
	Time   int                            `json:"time"`
	States []ListAPIStatesAllOkStatesItem `json:"states"`
}

// ListAPIStatesAllOkStatesItem defines a model
type ListAPIStatesAllOkStatesItem []any
