// This file provides types for the API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package petstore

import (
	"encoding/json/v2"
	"time"

	"github.com/google/uuid"
)

var jsonOpts = json.JoinOptions(
	json.RejectUnknownMembers(true),
)

// ListV1PetsOkJSONResponse defines a model
type ListV1PetsOkJSONResponse struct {
	Data       ListV1PetsOkJSONResponseData       `json:"data"`
	Pagination ListV1PetsOkJSONResponsePagination `json:"pagination"`
}

// ListV1PetsOkJSONResponseData defines a model
type ListV1PetsOkJSONResponseData []PetByPetID

// ListV1PetsOkJSONResponsePagination defines a model
type ListV1PetsOkJSONResponsePagination struct {
	Page       int `json:"page"`
	Limit      int `json:"limit"`
	TotalItems int `json:"totalItems"`
	TotalPages int `json:"totalPages"`
}

// PetByPetID defines a model
type PetByPetID struct {
	ID           uuid.UUID             `json:"id,omitzero"`
	Name         string                `json:"name,omitzero"`
	Species      string                `json:"species,omitzero"`
	Breed        string                `json:"breed,omitzero"`
	AgeMonths    int                   `json:"ageMonths"`
	Size         string                `json:"size,omitzero"`
	Status       string                `json:"status,omitzero"`
	Price        string                `json:"price,omitzero"`
	Currency     string                `json:"currency,omitzero"`
	GoodWithKids bool                  `json:"goodWithKids"`
	CreatedAt    time.Time             `json:"createdAt,omitzero"`
	UpdatedAt    time.Time             `json:"updatedAt,omitzero"`
	MedicalInfo  PetByPetIDMedicalInfo `json:"medicalInfo"`
}

// PetByPetIDMedicalInfo defines a model
type PetByPetIDMedicalInfo struct {
	Vaccinated     bool   `json:"vaccinated"`
	SpayedNeutered bool   `json:"spayedNeutered"`
	Microchipped   bool   `json:"microchipped"`
	SpecialNeeds   bool   `json:"specialNeeds"`
	HealthNotes    string `json:"healthNotes,omitzero"`
}
