// This file provides types for the API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package simple

import (
	"encoding/json/v2"
)

var jsonOpts = json.JoinOptions(
	json.RejectUnknownMembers(true),
)

// ListItemsParams holds the query parameters for ListItems.
type ListItemsParams struct {
	Limit int
}

// Item defines a model
type Item struct {
	ID int `json:"id,omitzero"`
	// This is a multiline
	// description.
	//
	// Foo.
	Name string `json:"name,omitzero"`
}

// ItemList defines a model
type ItemList []Item
