// This file provides a client with methods as well as functions to interact with the HTTP API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package golden

import (
	"context"
	"encoding/json/v2"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"

	"github.com/go-api-libs/api"
)

const defaultUserAgent = "Golden"

var defaultBaseURL = &url.URL{
	Scheme: "https",
	Host:   "api.example.com",
	Path:   "/v1",
}

// Client is an HTTP client for the golden API.
type Client struct {
	// The HTTP client to use for requests.
	cli *http.Client
	// The base URL
	baseURL *url.URL
	// The user agent
	userAgent string
}

// ClientOption configures a [Client].
type ClientOption func(*Client)

// WithBaseURL returns a [ClientOption] that overrides the default base URL.
// It will prefix a leading slash to the path if there is none.
func WithBaseURL(baseURL *url.URL) ClientOption {
	if !strings.HasPrefix(baseURL.Path, "/") {
		baseURL.Path = "/" + baseURL.Path
	}

	return func(c *Client) { c.baseURL = baseURL }
}

// WithHTTPClient returns a [ClientOption] that sets a custom HTTP client.
func WithHTTPClient(cli *http.Client) ClientOption {
	return func(c *Client) { c.cli = cli }
}

// NewClient creates a new Client.
func NewClient(opts ...ClientOption) (*Client, error) {
	c := &Client{
		cli:       http.DefaultClient,
		baseURL:   defaultBaseURL,
		userAgent: defaultUserAgent,
	}

	for _, opt := range opts {
		opt(c)
	}

	return c, nil
}

// Retrieve a page
//
//	GET /pages/{id}
func (c *Client) GetPage(ctx context.Context, id string) (*Page, error) {
	return c.GetPageWithResult[Page](ctx, id)
}

// Retrieve a page
// You can define a custom result to unmarshal the response into.
//
//	GET /pages/{id}
func (c *Client) GetPageWithResult[R any](ctx context.Context, id string) (*R, error) {
	u := c.baseURL.JoinPath("pages", id)
	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// ok
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R

			// a type of the caller's own declares only what it needs of the response, so it is decoded leniently
			opts := jsonOptsLenient
			if _, ok := any(&out).(*Page); ok {
				opts = jsonOpts
			}

			if err := json.UnmarshalRead(rsp.Body, &out, opts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// POST /search
func (c *Client) Search(ctx context.Context, body PropertyFilter) ([]PageOrPartial, error) {
	out, err := c.SearchWithResult[[]PageOrPartial](ctx, body)
	if err != nil {
		return nil, err
	}

	return *out, nil
}

// POST /search
func (c *Client) SearchWithResult[R any](ctx context.Context, body PropertyFilter) (*R, error) {
	u := c.baseURL.JoinPath("search")
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOptsRequest)) }()
	defer pr.Close()

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// ok
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R

			// a type of the caller's own declares only what it needs of the response, so it is decoded leniently
			opts := jsonOptsLenient
			if _, ok := any(&out).(*[]PageOrPartial); ok {
				opts = jsonOpts
			}

			if err := json.UnmarshalRead(rsp.Body, &out, opts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// PUT /users/{id}
func (c *Client) UpdateUser(ctx context.Context, id string, body User) (*User, error) {
	return c.UpdateUserWithResult[User](ctx, id, body)
}

// PUT /users/{id}
func (c *Client) UpdateUserWithResult[R any](ctx context.Context, id string, body User) (*R, error) {
	u := c.baseURL.JoinPath("users", id)
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPut,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOptsRequest)) }()
	defer pr.Close()

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// ok
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R

			// a type of the caller's own declares only what it needs of the response, so it is decoded leniently
			opts := jsonOptsLenient
			if _, ok := any(&out).(*User); ok {
				opts = jsonOpts
			}

			if err := json.UnmarshalRead(rsp.Body, &out, opts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// POST /entries
func (c *Client) CreateEntry(ctx context.Context, body Entry) (*Entry, error) {
	return c.CreateEntryWithResult[Entry](ctx, body)
}

// POST /entries
func (c *Client) CreateEntryWithResult[R any](ctx context.Context, body Entry) (*R, error) {
	u := c.baseURL.JoinPath("entries")
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOptsRequest)) }()
	defer pr.Close()

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// ok
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R

			// a type of the caller's own declares only what it needs of the response, so it is decoded leniently
			opts := jsonOptsLenient
			if _, ok := any(&out).(*Entry); ok {
				opts = jsonOpts
			}

			if err := json.UnmarshalRead(rsp.Body, &out, opts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

//	GET /values/{id}
//
// Deprecated.
func (c *Client) GetValue(ctx context.Context, id string) (*Value, error) {
	return c.GetValueWithResult[Value](ctx, id)
}

//	GET /values/{id}
//
// Deprecated.
func (c *Client) GetValueWithResult[R any](ctx context.Context, id string) (*R, error) {
	u := c.baseURL.JoinPath("values", id)
	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// ok
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R

			// a type of the caller's own declares only what it needs of the response, so it is decoded leniently
			opts := jsonOptsLenient
			if _, ok := any(&out).(*Value); ok {
				opts = jsonOpts
			}

			if err := json.UnmarshalRead(rsp.Body, &out, opts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// GET /blocks/{id}
func (c *Client) GetBlock(ctx context.Context, id string) (*Block, error) {
	return c.GetBlockWithResult[Block](ctx, id)
}

// GET /blocks/{id}
func (c *Client) GetBlockWithResult[R any](ctx context.Context, id string) (*R, error) {
	u := c.baseURL.JoinPath("blocks", id)
	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// ok
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R

			// a type of the caller's own declares only what it needs of the response, so it is decoded leniently
			opts := jsonOptsLenient
			if _, ok := any(&out).(*Block); ok {
				opts = jsonOpts
			}

			if err := json.UnmarshalRead(rsp.Body, &out, opts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// POST /databases
func (c *Client) CreateDatabase(ctx context.Context, body CreateDatabaseParent) (*AgentModel, error) {
	return c.CreateDatabaseWithResult[AgentModel](ctx, body)
}

// POST /databases
func (c *Client) CreateDatabaseWithResult[R any](ctx context.Context, body CreateDatabaseParent) (*R, error) {
	u := c.baseURL.JoinPath("databases")
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOptsRequest)) }()
	defer pr.Close()

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// ok
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R

			// a type of the caller's own declares only what it needs of the response, so it is decoded leniently
			opts := jsonOptsLenient
			if _, ok := any(&out).(*AgentModel); ok {
				opts = jsonOpts
			}

			if err := json.UnmarshalRead(rsp.Body, &out, opts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// GET /properties/{id}
func (c *Client) GetProperty(ctx context.Context, id string) (*NestedValue, error) {
	return c.GetPropertyWithResult[NestedValue](ctx, id)
}

// GET /properties/{id}
func (c *Client) GetPropertyWithResult[R any](ctx context.Context, id string) (*R, error) {
	u := c.baseURL.JoinPath("properties", id)
	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// ok
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R

			// a type of the caller's own declares only what it needs of the response, so it is decoded leniently
			opts := jsonOptsLenient
			if _, ok := any(&out).(*NestedValue); ok {
				opts = jsonOpts
			}

			if err := json.UnmarshalRead(rsp.Body, &out, opts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// GET /reports
func (c *Client) ListReports(ctx context.Context, params ListReportsParams) (Reports, error) {
	out, err := c.ListReportsWithResult[Reports](ctx, params)
	if err != nil {
		return nil, err
	}

	return *out, nil
}

// GET /reports
func (c *Client) ListReportsWithResult[R any](ctx context.Context, params ListReportsParams) (*R, error) {
	u := c.baseURL.JoinPath("reports")

	q := make(url.Values, 10)

	q["since"] = []string{params.Since.Format(time.RFC3339)}

	for _, v := range params.Ids {
		q.Add("ids", strconv.Itoa(v))
	}

	if params.Verbose {
		q["verbose"] = []string{strconv.FormatBool(params.Verbose)}
	}

	if params.Format != "" {
		q["format"] = []string{string(params.Format)}
	}

	for _, v := range params.Formats {
		q.Add("formats", string(v))
	}

	for _, v := range params.Tags {
		q.Add("tags", v)
	}

	if params.Cursor != "" {
		q["cursor"] = []string{params.Cursor}
	}

	if params.Order != "" {
		q["order"] = []string{params.Order}
	}

	if params.Limit != "" {
		q["limit"] = []string{params.Limit}
	}

	if params.Pairs != "" {
		q["pairs"] = []string{params.Pairs}
	}

	u.RawQuery = q.Encode()

	req := (&http.Request{
		Header: http.Header{
			"X-Version":  []string{params.XVersion},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// ok
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R

			// a type of the caller's own declares only what it needs of the response, so it is decoded leniently
			opts := jsonOptsLenient
			if _, ok := any(&out).(*Reports); ok {
				opts = jsonOpts
			}

			if err := json.UnmarshalRead(rsp.Body, &out, opts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// A person is a user, itself a union, or a group: the choices of a nested union.
//
//	GET /people
func (c *Client) ListPeople(ctx context.Context) (*ListPeopleOk, error) {
	return c.ListPeopleWithResult[ListPeopleOk](ctx)
}

// A person is a user, itself a union, or a group: the choices of a nested union.
// You can define a custom result to unmarshal the response into.
//
//	GET /people
func (c *Client) ListPeopleWithResult[R any](ctx context.Context) (*R, error) {
	u := c.baseURL.JoinPath("people")
	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// ok
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R

			// a type of the caller's own declares only what it needs of the response, so it is decoded leniently
			opts := jsonOptsLenient
			if _, ok := any(&out).(*ListPeopleOk); ok {
				opts = jsonOpts
			}

			if err := json.UnmarshalRead(rsp.Body, &out, opts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// POST /schedules
func (c *Client) CreateSchedule(ctx context.Context, body Schedule) (*CreateScheduleCreated, error) {
	return c.CreateScheduleWithResult[CreateScheduleCreated](ctx, body)
}

// POST /schedules
func (c *Client) CreateScheduleWithResult[R any](ctx context.Context, body Schedule) (*R, error) {
	u := c.baseURL.JoinPath("schedules")
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOptsRequest)) }()
	defer pr.Close()

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusCreated:
		// created
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R

			// a type of the caller's own declares only what it needs of the response, so it is decoded leniently
			opts := jsonOptsLenient
			if _, ok := any(&out).(*CreateScheduleCreated); ok {
				opts = jsonOpts
			}

			if err := json.UnmarshalRead(rsp.Body, &out, opts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case 529:
		// A status Go has no name for.
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out Overloaded
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return nil, api.NewErrCustom(rsp, &out)
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Anything but JSON is the bytes as they are.
//
//	GET /reports/{format}
func (c *Client) DownloadReport(ctx context.Context, format ScheduleFormat) (io.ReadCloser, error) {
	u := c.baseURL.JoinPath("reports", string(format))
	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}

	// the body is left open only when it is handed to the caller
	streaming := false
	defer func() {
		if !streaming {
			rsp.Body.Close()
		}
	}()

	switch rsp.StatusCode {
	case http.StatusOK:
		// ok
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/pdf":
			streaming = true

			return rsp.Body, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// The success is an empty object, decoded so that anything in it fails.
//
//	DELETE /schedules/{id}
func (c *Client) DeleteSchedule(ctx context.Context, id string) error {
	u := c.baseURL.JoinPath("schedules", id)
	req := (&http.Request{
		Header: http.Header{
			"Api-Version": []string{"2"},
			"User-Agent":  []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodDelete,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// ok
		return nil
	default:
		return api.NewErrUnknownStatusCode(rsp)
	}
}

// Text is read whole, as bytes.
//
//	GET /status
func (c *Client) GetStatus(ctx context.Context) ([]byte, error) {
	u := c.baseURL.JoinPath("status")
	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// ok
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "text/plain":
			out, err := io.ReadAll(rsp.Body)
			if err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}
