// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

/**
 * Retrodiffusion API Client
 * =========================
 *
 * Matches the OpenAPI specification. All functions are async and return
 * data or `null` on failure.
 *
 * Usage:
 *   import './api.js';        // or <script src="api.js"></script>
 *   const result = await window.API.listV1StylesSelector();
 *   const result = await window.API.postV1Inferences();
 **/

const API_BASE = "https://api.retrodiffusion.ai/v1";
const TIMEOUT = 4000;

// ====================== ENVIRONMENT ======================
window.ENV = "production";

// reportApiError broadcasts a failed API call as a "retrodiffusion:ws-message"
// CustomEvent, the same channel server-pushed notifications use, so a single
// listener can surface both origins uniformly.
function reportApiError(operationId, status, message) {
    window.dispatchEvent(new CustomEvent("retrodiffusion:ws-message", {
        detail: {
            level: "error",
            persistent: true,
            title: `${operationId} failed`,
            meta: [`Status ${status}`, message],
        },
    }));
}

async function apiFetch(path, options = {}) {
    const {
        method = "GET", operationId = "Request"
    } = options;
    const ctrl = new AbortController();
    const timeoutId = setTimeout(() => ctrl.abort(), TIMEOUT);

    try {
        const res = await fetch(API_BASE + path, {
            ...options,
            signal: ctrl.signal,
                headers: {
                    "Content-Type": "application/json",
                    ...options.headers,
                },
        });

        clearTimeout(timeoutId);

        if (!res.ok) {
            console.warn(`API Error: ${res.status} ${method} ${path}`);
            let message = res.statusText || "Request failed";
            try {
                const body = await res.clone().json();
                message = body?.message || body?.error || message;
            } catch {}
            reportApiError(operationId, res.status, message);
            return null;
        }

        return await res.json();
    } catch (err) {
        clearTimeout(timeoutId);
        if (err.name === "AbortError") {
            console.error(`Request timeout: ${path}`);
            reportApiError(operationId, "timeout", `${path} did not respond in time`);
        } else {
            console.error(`Request failed: ${path}`, err);
            reportApiError(operationId, "network", err.message || "Network error");
        }
        return null;
    }
}

// ====================== PUBLIC API ======================

window.API = {
    // GET /styles/selector
    listV1StylesSelector: (params = {}) => {
        const q = new URLSearchParams();
        if (params.model != null) q.set("model", String(params.model));
        return apiFetch(`/styles/selector?${q}`, {
            operationId: "ListV1StylesSelector",
        });
    },
    // POST /inferences
    postV1Inferences: (body) => apiFetch("/inferences", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "PostV1Inferences",
    }),
};
