// This file provides tests for the client.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package retrodiffusion

import (
	"bytes"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"fmt"
	"io"
	"maps"
	"net/http"
	"net/http/httptest"
	"net/url"
	"slices"
	"testing"

	"github.com/MarkRosemaker/openapi-enrich/cassette"
	"github.com/go-api-libs/api"
)

func newTestServer(t *testing.T, status int) *httptest.Server {
	t.Helper()
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(status)
	}))
	t.Cleanup(srv.Close)
	return srv
}

type roundTripFunc func(*http.Request) (*http.Response, error)

func (f roundTripFunc) RoundTrip(r *http.Request) (*http.Response, error) {
	return f(r)
}

func TestClient_Error(t *testing.T) {
	t.Run("ListV1StylesSelector", func(t *testing.T) {
		t.Setenv("API_KEY", "************************************************")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListV1StylesSelector(t.Context(), nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListV1StylesSelector(t.Context(), nil); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListV1StylesSelector(t.Context(), nil); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListV1StylesSelector(t.Context(), nil); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("PostV1Inferences", func(t *testing.T) {
		t.Setenv("API_KEY", "************************************************")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.PostV1Inferences(t.Context(), PostV1InferencesJSONRequestBody{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.PostV1Inferences(t.Context(), PostV1InferencesJSONRequestBody{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.PostV1Inferences(t.Context(), PostV1InferencesJSONRequestBody{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.PostV1Inferences(t.Context(), PostV1InferencesJSONRequestBody{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})
}

func replay(t *testing.T) http.RoundTripper {
	t.Helper()

	interactions, err := cassette.InteractionsReadFile("../../api/interactions.json")
	if err != nil {
		t.Fatal(err)
	}

	var idx int
	return roundTripFunc(func(req *http.Request) (*http.Response, error) {
		if idx >= len(interactions) {
			return nil, fmt.Errorf("unexpected request: %s %s", req.Method, req.URL)
		}

		ia := interactions[idx]

		r, err := cassette.NewRequest(req)
		if err != nil {
			return nil, err
		}

		if r.URL != ia.Request.URL {
			return nil, fmt.Errorf("interaction #%d: got URL %s, want %s", idx, r.URL, ia.Request.URL)
		}

		if r.Method != ia.Request.Method {
			return nil, fmt.Errorf("interaction #%d: got method %s, want %s", idx, r.Method, ia.Request.Method)
		}

		gotBody := jsontext.Value(r.Body)
		gotBody.Canonicalize()

		wantBody := jsontext.Value(ia.Request.Body)
		wantBody.Canonicalize()

		if !bytes.Equal(gotBody, wantBody) {
			return nil, fmt.Errorf("interaction #%d: got body %s, want %s", idx, string(gotBody), string(wantBody))
		}

		if ia.Request.Headers == nil {
			ia.Request.Headers = http.Header{}
		}

		ia.Request.Headers.Set("User-Agent", defaultUserAgent)

		if len(ia.Request.Body) == 0 {
			ia.Request.Headers.Del("Content-Type")
		}

		if !maps.EqualFunc(r.Headers, ia.Request.Headers, slices.Equal) {
			return nil, fmt.Errorf("interaction #%d: got headers %s, want %s", idx, r.Headers, ia.Request.Headers)
		}

		idx++
		return &http.Response{
			Status:     fmt.Sprintf("%d %s", ia.Response.StatusCode, http.StatusText(ia.Response.StatusCode)),
			StatusCode: ia.Response.StatusCode,
			Header:     ia.Response.Headers.Clone(),
			Body:       io.NopCloser(bytes.NewReader(ia.Response.Body)),
		}, nil
	})
}

// mustDecodeBody decodes data, the recorded request body of an interaction,
// into T so a replayed call carries the same body it was recorded with
// instead of a zero value.
func mustDecodeBody[T any](t *testing.T, data string) T {
	t.Helper()

	var v T
	if err := json.Unmarshal([]byte(data), &v, jsonOpts); err != nil {
		t.Fatalf("decoding request body fixture: %v", err)
	}

	return v
}

// mustDecodeBodyPtr is mustDecodeBody for an optional request body: an empty
// recording (the body was never sent) decodes to nil rather than a value.
func mustDecodeBodyPtr[T any](t *testing.T, data string) *T {
	if data == "" {
		return nil
	}

	v := mustDecodeBody[T](t, data)
	return &v
}

func TestClient_Interactions(t *testing.T) {
	ctx := t.Context()
	t.Setenv("API_KEY", "************************************************")

	c, err := NewClient(WithHTTPClient(&http.Client{Transport: replay(t)}))
	if err != nil {
		t.Fatal(err)
	}

	if _, err := c.ListV1StylesSelector(ctx, &ListV1StylesSelectorParams{
		Model: "rd_pro",
	}); err != nil {
		t.Fatalf("ListV1StylesSelector: %v", err)
	}

	if _, err := c.ListV1StylesSelector(ctx, &ListV1StylesSelectorParams{}); err != nil {
		t.Fatalf("ListV1StylesSelector: %v", err)
	}

	if _, err := c.PostV1Inferences(ctx, mustDecodeBody[PostV1InferencesJSONRequestBody](t, "{\"prompt\":\"security officer (a soldier). A 34-year-old male human. Lean and wiry, with a posture that suggests he's always expecting something to break. He wears the standard grey-blue security fatigues, kept meticulously clean despite the dust of the colony. A thin, jagged scar running through his left eyebrow. He has a habit of clicking his tongue when he's impatient.\",\"prompt_style\":\"rd_pro__topdown\",\"width\":128,\"height\":128,\"num_images\":1,\"remove_bg\":true,\"tile_x\":false,\"tile_y\":false,\"return_spritesheet\":false,\"bypass_prompt_expansion\":false,\"include_downloadable_data\":false,\"check_cost\":true,\"async\":false,\"upload_outputs\":false}")); err != nil {
		t.Fatalf("PostV1Inferences: %v", err)
	}
}
