// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package toggl

import (
	"context"
	"encoding/json/v2"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"strconv"
	"time"

	"github.com/go-api-libs/api/server"
)

// Service defines the operations the server must implement.
type Service interface {
	GetMe(ctx context.Context, params *GetMeParams) (*UserWithRelated, error)
	CreateTimeEntry(ctx context.Context, workspaceID int, body NewTimeEntry) (*TimeEntry, error)
	GetCurrentTimeEntry(ctx context.Context) (*TimeEntry, error)
	StopTimeEntry(ctx context.Context, workspaceID int, timeEntryID int) (*TimeEntry, error)
	ListTimeEntries(ctx context.Context, params *ListTimeEntriesParams) (*TimeEntries, error)
	CreateOrganization(ctx context.Context, body NewOrganization) (*SimpleOrganization, error)
	ListOrganizations(ctx context.Context) (*Organizations, error)
	GetOrganization(ctx context.Context, organizationID int) (*Organization, error)
	PostOrganizations9011051Workspaces(ctx context.Context, body PostOrganizations9011051WorkspacesJSONRequestBody) error
}

// RegisterService registers a [Service] with an [*http.ServeMux].
// Optionally, a path prefix may be provided.
func RegisterService(svc Service, mux *http.ServeMux, pathPrefix string) {
	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/me")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "GetMe"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			var params GetMeParams
			q := r.URL.Query()
			if s := q.Get("with_related_data"); s != "" {
				rawParam, err := strconv.ParseBool(s)
				if err != nil {
					msg := fmt.Sprintf("invalid with_related_data: %v", err)
					l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
					http.Error(w, msg, http.StatusBadRequest)
					return
				}
				params.WithRelatedData = rawParam
			}

			res, err := svc.GetMe(ctx, &params)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/workspaces/{workspace_id}/time_entries")
		l := slog.Default().With(slog.String("method", "POST"), slog.String("path", path), slog.String("function", "CreateTimeEntry"))

		mux.HandleFunc(fmt.Sprintf("POST %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("workspace_id")
			workspaceID, err := strconv.Atoi(s)
			if err != nil {
				msg := fmt.Sprintf("invalid workspace_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			var body NewTimeEntry
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.CreateTimeEntry(ctx, workspaceID, body)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/me/time_entries/current")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "GetCurrentTimeEntry"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			res, err := svc.GetCurrentTimeEntry(ctx)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/workspaces/{workspace_id}/time_entries/{time_entry_id}/stop")
		l := slog.Default().With(slog.String("method", "PATCH"), slog.String("path", path), slog.String("function", "StopTimeEntry"))

		mux.HandleFunc(fmt.Sprintf("PATCH %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("workspace_id")
			workspaceID, err := strconv.Atoi(s)
			if err != nil {
				msg := fmt.Sprintf("invalid workspace_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			s = r.PathValue("time_entry_id")
			timeEntryID, err := strconv.Atoi(s)
			if err != nil {
				msg := fmt.Sprintf("invalid time_entry_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.StopTimeEntry(ctx, workspaceID, timeEntryID)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/me/time_entries")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "ListTimeEntries"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			var params ListTimeEntriesParams
			q := r.URL.Query()
			if s := q.Get("since"); s != "" {
				rawParam, err := strconv.Atoi(s)
				if err != nil {
					msg := fmt.Sprintf("invalid since: %v", err)
					l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
					http.Error(w, msg, http.StatusBadRequest)
					return
				}
				params.Since = rawParam
			}
			if s := q.Get("before"); s != "" {
				rawParam, err := time.Parse(time.RFC3339, s)
				if err != nil {
					msg := fmt.Sprintf("invalid before: %v", err)
					l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
					http.Error(w, msg, http.StatusBadRequest)
					return
				}
				params.Before = rawParam
			}
			if s := q.Get("start_date"); s != "" {
				rawParam, err := time.Parse(time.RFC3339, s)
				if err != nil {
					msg := fmt.Sprintf("invalid start_date: %v", err)
					l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
					http.Error(w, msg, http.StatusBadRequest)
					return
				}
				params.StartDate = rawParam
			}
			if s := q.Get("end_date"); s != "" {
				rawParam, err := time.Parse(time.RFC3339, s)
				if err != nil {
					msg := fmt.Sprintf("invalid end_date: %v", err)
					l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
					http.Error(w, msg, http.StatusBadRequest)
					return
				}
				params.EndDate = rawParam
			}
			if s := q.Get("meta"); s != "" {
				rawParam, err := strconv.ParseBool(s)
				if err != nil {
					msg := fmt.Sprintf("invalid meta: %v", err)
					l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
					http.Error(w, msg, http.StatusBadRequest)
					return
				}
				params.Meta = rawParam
			}
			if s := q.Get("include_sharing"); s != "" {
				rawParam, err := strconv.ParseBool(s)
				if err != nil {
					msg := fmt.Sprintf("invalid include_sharing: %v", err)
					l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
					http.Error(w, msg, http.StatusBadRequest)
					return
				}
				params.IncludeSharing = rawParam
			}

			res, err := svc.ListTimeEntries(ctx, &params)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/organizations")
		l := slog.Default().With(slog.String("method", "POST"), slog.String("path", path), slog.String("function", "CreateOrganization"))

		mux.HandleFunc(fmt.Sprintf("POST %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			var body NewOrganization
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.CreateOrganization(ctx, body)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/me/organizations")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "ListOrganizations"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			res, err := svc.ListOrganizations(ctx)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/organizations/{organization_id}")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "GetOrganization"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("organization_id")
			organizationID, err := strconv.Atoi(s)
			if err != nil {
				msg := fmt.Sprintf("invalid organization_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.GetOrganization(ctx, organizationID)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/organizations/9011051/workspaces")
		l := slog.Default().With(slog.String("method", "POST"), slog.String("path", path), slog.String("function", "PostOrganizations9011051Workspaces"))

		mux.HandleFunc(fmt.Sprintf("POST %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			var body PostOrganizations9011051WorkspacesJSONRequestBody
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			if err := svc.PostOrganizations9011051Workspaces(ctx, body); err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.WriteHeader(http.StatusOK)

			l.DebugContext(ctx, "success")
		})
	}
}
