// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

/**
 * Pixel Lab API Client
 * =========================
 *
 * Matches the OpenAPI specification. All functions are async and return
 * data or `null` on failure.
 *
 * Usage:
 *   import './api.js';        // or <script src="api.js"></script>
 *   const result = await window.API.generateImageV2GenerateImageV2Post();
 *   const result = await window.API.generateWithStyleV2GenerateWithStyleV2Post();
 *   const result = await window.API.generateUiv2GenerateUiv2Post();
 *   const result = await window.API.generateImagePixfluxCreateImagePixfluxPost();
 *   const result = await window.API.createImagePixfluxBackgroundCreateImagePixfluxBackgroundPost();
 *   const result = await window.API.generateImagePixenCreateImagePixenPost();
 *   const result = await window.API.generateImageBitforgeCreateImageBitforgePost();
 *   const result = await window.API.imageToPixelartImageToPixelartPost();
 *   const result = await window.API.imageToPixelartProImageToPixelartProPost();
 *   const result = await window.API.resizeImageResizePost();
 *   const result = await window.API.removeBackgroundEndpointRemoveBackgroundPost();
 *   const result = await window.API.editAnimationV2EditAnimationV2Post();
 *   const result = await window.API.interpolationV2InterpolationV2Post();
 *   const result = await window.API.transferOutfitV2TransferOutfitV2Post();
 *   const result = await window.API.portraitCharacterProPortraitCharacterProPost();
 *   const result = await window.API.getPortraitCharacterPortraitCharacterProJobIDGet(jobID);
 *   const result = await window.API.setPortraitCharactersCharacterIDPortraitPost(characterID);
 *   const result = await window.API.createVocalAnimationVocalAnimationPost();
 *   const result = await window.API.getVocalAnimationVocalAnimationJobIDGet(jobID);
 *   const result = await window.API.createTalkingGifTalkingGifPost();
 *   const result = await window.API.getLipSyncLipSyncPost();
 *   const result = await window.API.generateFontProGenerateFontProPost();
 *   const result = await window.API.getFontGenerateFontProJobIDGet(jobID);
 *   const result = await window.API.animateWithSkeletonAnimateWithSkeletonPost();
 *   const result = await window.API.animateWithTextAnimateWithTextPost();
 *   const result = await window.API.animateWithTextV2AnimateWithTextV2Post();
 *   const result = await window.API.animateWithTextV3AnimateWithTextV3Post();
 *   const result = await window.API.estimateSkeletonEstimateSkeletonPost();
 *   const result = await window.API.generate8RotationsV2Generate8RotationsV2Post();
 *   const result = await window.API.generate8RotationsV3Generate8RotationsV3Post();
 *   const result = await window.API.generateRotationRotatePost();
 *   const result = await window.API.inpaintV3InpaintV3Post();
 *   const result = await window.API.generateInpaintingInpaintPost();
 *   const result = await window.API.editImagesV2EditImagesV2Post();
 *   const result = await window.API.editImageEditImagePost();
 *   const result = await window.API.listTilesetsTilesetsGet();
 *   const result = await window.API.generateTilesetTilesetsPost();
 *   const result = await window.API.generateTilesetCreateTilesetPost();
 *   const result = await window.API.getTilesetTilesetsTilesetIDGet(tilesetID);
 *   const result = await window.API.deleteTopdownTilesetTilesetsTilesetIDDelete(tilesetID);
 *   const result = await window.API.listSidescrollerTilesetsTilesetsSidescrollerGet();
 *   const result = await window.API.generateTilesetSidescrollerTilesetsSidescrollerPost();
 *   const result = await window.API.generateTilesetSidescrollerCreateTilesetSidescrollerPost();
 *   const result = await window.API.getSidescrollerTilesetTilesetsSidescrollerTilesetIDGet(tilesetID);
 *   const result = await window.API.deleteSidescrollerTilesetTilesetsSidescrollerTilesetIDDelete(tilesetID);
 *   const result = await window.API.generateIsometricTileCreateIsometricTilePost();
 *   const result = await window.API.getIsometricTileIsometricTilesTileIDGet(tileID);
 *   const result = await window.API.deleteIsometricTileIsometricTilesTileIDDelete(tileID);
 *   const result = await window.API.listIsometricTilesIsometricTilesGet();
 *   const result = await window.API.createTilesProCreateTilesProPost();
 *   const result = await window.API.getTilesProTilesProTileIDGet(tileID);
 *   const result = await window.API.deleteTilesProTilesProTileIDDelete(tileID);
 *   const result = await window.API.listTilesProTilesProGet();
 *   const result = await window.API.createMapObjectMapObjectsPost();
 *   const result = await window.API.getMapObjectMapObjectsObjectIDGet(objectID);
 *   const result = await window.API.createUIAssetCreateUIAssetPost();
 *   const result = await window.API.listUIAssetsUIAssetsGet();
 *   const result = await window.API.getUIAssetUIAssetsUIAssetIDGet(uiAssetID);
 *   const result = await window.API.deleteUIAssetUIAssetsUIAssetIDDelete(uiAssetID);
 *   const result = await window.API.getBalanceBalanceGet();
 *   const result = await window.API.createCharacterWith4DirectionsCreateCharacterWith4DirectionsPost();
 *   const result = await window.API.createCharacterWith8DirectionsCreateCharacterWith8DirectionsPost();
 *   const result = await window.API.createCharacterProCreateCharacterProPost();
 *   const result = await window.API.createCharacterV3CreateCharacterV3Post();
 *   const result = await window.API.createCharacterAnimationCharactersAnimationsPost();
 *   const result = await window.API.createCharacterAnimationAnimateCharacterPost();
 *   const result = await window.API.createCharacterStateCreateCharacterStatePost();
 *   const result = await window.API.listCharactersCharactersGet();
 *   const result = await window.API.getCharacterCharactersCharacterIDGet(characterID);
 *   const result = await window.API.deleteCharacterV2CharactersCharacterIDDelete(characterID);
 *   const result = await window.API.downloadCharacterCharactersCharacterIDZipGet(characterID);
 *   const result = await window.API.updateCharacterTagsCharactersCharacterIDTagsPatch(characterID);
 *   const result = await window.API.getBackgroundJobStatusBackgroundJobsJobIDGet(jobID);
 *   const result = await window.API.create1DirectionObjectCreate1DirectionObjectPost();
 *   const result = await window.API.create8DirectionObjectCreate8DirectionObjectPost();
 *   const result = await window.API.animateObjectObjectsObjectIDAnimationsPost(objectID);
 *   const result = await window.API.deleteObjectAnimationsObjectsObjectIDAnimationsDelete(objectID);
 *   const result = await window.API.createObjectStateObjectsObjectIDStatesPost(objectID);
 *   const result = await window.API.selectObjectFramesObjectsObjectIDSelectFramesPost(objectID);
 *   const result = await window.API.dismissReviewObjectsObjectIDDismissReviewPost(objectID);
 *   const result = await window.API.listObjectsObjectsGet();
 *   const result = await window.API.getObjectObjectsObjectIDGet(objectID);
 *   const result = await window.API.deleteObjectObjectsObjectIDDelete(objectID);
 *   const result = await window.API.updateObjectTagsObjectsObjectIDTagsPatch(objectID);
 *   const result = await window.API.deleteCharacterAnimationsCharactersCharacterIDAnimationsDelete(characterID);
 *   const result = await window.API.enhancePixenPromptEnhancePixenPromptPost();
 *   const result = await window.API.enhanceCharacterV3PromptEnhanceCharacterV3PromptPost();
 *   const result = await window.API.enhanceAnimationV3PromptEnhanceAnimationV3PromptPost();
 *   const result = await window.API.getLlmsTxtLlmsTxtGet();
 *
 * Environment:
 *   Set `window.ENV = 'development'` to enable mocking via /mocks.json.
 *   Set `window.ENV = 'production'` (or anything else) to use real API calls.
 */

const API_BASE = ":///v2";
const TIMEOUT = 4000;

// ====================== ENVIRONMENT ======================
// Change this to 'production' when connecting to a real backend
window.ENV = "production";

// Cache for mocks (loaded once)
let mocks = null;
let mocksPromise = null;

async function loadMocks() {
    if (mocks) return mocks;
    if (mocksPromise) return mocksPromise;

    mocksPromise = fetch("mocks.json")
        .then((res) => {
            if (!res.ok) throw new Error(`Failed to load mocks.json: ${res.status}`);
            return res.json();
        })
        .then((data) => {
            mocks = Array.isArray(data) ? data : [];
            console.log(
                `%c[Mock] Loaded ${mocks.length} mock(s)`,
                "color: #10b981; font-weight: bold",
            );
            return mocks;
        })
        .catch((err) => {
            console.error("[Mock] Failed to load mocks.json", err);
            mocks = [];
            return [];
        });

    return mocksPromise;
}

function matchesRequest(mockRequest, method, path) {
    if (!mockRequest) return false;

    const mockMethod = mockRequest.method?.toUpperCase();
    const mockUrl = mockRequest.url;

    if (mockMethod && mockMethod !== method) return false;

    if (mockUrl === path) return true;

    try {
        const mockPath = new URL(mockUrl).pathname;
        return mockPath === path || mockPath.endsWith(path);
    } catch {
        return mockUrl.endsWith(path) || mockUrl === path;
    }
}

// reportApiError broadcasts a failed API call as a "pixellab:ws-message"
// CustomEvent, the same channel server-pushed notifications use, so a single
// listener can surface both origins uniformly.
function reportApiError(operationId, status, message) {
    window.dispatchEvent(new CustomEvent("pixellab:ws-message", {
        detail: {
            level: "error",
            persistent: true,
            title: `${operationId} failed`,
            meta: [`Status ${status}`, message],
        },
    }));
}

async function apiFetch(path, options = {}) {
    const {
        method = "GET", operationId = "Request"
    } = options;

    // ====================== DEVELOPMENT MOCKING ======================
    if (window.ENV === "development") {
        await loadMocks();

        const mockEntry = mocks.find((m) =>
            matchesRequest(m.request, method, path),
        );

        if (mockEntry?.response) {
            const {
                statusCode = 200, body
            } = mockEntry.response;

            console.log(
                `%c[Mock] ${method} ${path} → ${statusCode}`,
                "color: #10b981; font-weight: 600",
            );

            if (statusCode >= 400) {
                console.warn(`[Mock] Error ${statusCode} for ${path}`);
                const message = (body && (body.message || body.error)) || "Request failed";
                reportApiError(operationId, statusCode, message);
                return null;
            }

            return typeof body === "object" && body !== null ? structuredClone(body) : body;
        }

        console.warn(
            `%c[Mock] No mock found for ${method} ${path}`,
            "color: #f59e0b",
        );
        return null;
    }

    // ====================== REAL API CALL ======================
    const ctrl = new AbortController();
    const timeoutId = setTimeout(() => ctrl.abort(), TIMEOUT);

    try {
        const res = await fetch(API_BASE + path, {
            ...options,
            signal: ctrl.signal,
                headers: {
                    "Content-Type": "application/json",
                    ...options.headers,
                },
        });

        clearTimeout(timeoutId);

        if (!res.ok) {
            console.warn(`API Error: ${res.status} ${path}`);
            let message = res.statusText || "Request failed";
            try {
                const body = await res.clone().json();
                message = body?.message || body?.error || message;
            } catch {}
            reportApiError(operationId, res.status, message);
            return null;
        }

        return await res.json();
    } catch (err) {
        clearTimeout(timeoutId);
        if (err.name === "AbortError") {
            console.error(`Request timeout: ${path}`);
            reportApiError(operationId, "timeout", `${path} did not respond in time`);
        } else {
            console.error(`Request failed: ${path}`, err);
            reportApiError(operationId, "network", err.message || "Network error");
        }
        return null;
    }
}

// ====================== PUBLIC API ======================

window.API = {
    // POST /generate-image-v2
    // Generate image (Pro)
    generateImageV2GenerateImageV2Post: (body) => apiFetch("/generate-image-v2", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "GenerateImageV2GenerateImageV2Post",
    }),
    // POST /generate-with-style-v2
    // Generate with style (Pro)
    generateWithStyleV2GenerateWithStyleV2Post: (body) => apiFetch("/generate-with-style-v2", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "GenerateWithStyleV2GenerateWithStyleV2Post",
    }),
    // POST /generate-ui-v2
    // Generate UI (Pro)
    generateUiv2GenerateUiv2Post: (body) => apiFetch("/generate-ui-v2", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "GenerateUiv2GenerateUiv2Post",
    }),
    // POST /create-image-pixflux
    // Create image (pixflux)
    generateImagePixfluxCreateImagePixfluxPost: (body) => apiFetch("/create-image-pixflux", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "GenerateImagePixfluxCreateImagePixfluxPost",
    }),
    // POST /create-image-pixflux-background
    // Create image (pixflux, background)
    createImagePixfluxBackgroundCreateImagePixfluxBackgroundPost: (body) => apiFetch("/create-image-pixflux-background", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateImagePixfluxBackgroundCreateImagePixfluxBackgroundPost",
    }),
    // POST /create-image-pixen
    // Create image (pixen)
    generateImagePixenCreateImagePixenPost: (body) => apiFetch("/create-image-pixen", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "GenerateImagePixenCreateImagePixenPost",
    }),
    // POST /create-image-bitforge
    // Create image (bitforge)
    generateImageBitforgeCreateImageBitforgePost: (body) => apiFetch("/create-image-bitforge", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "GenerateImageBitforgeCreateImageBitforgePost",
    }),
    // POST /image-to-pixelart
    // Convert image to pixel art
    imageToPixelartImageToPixelartPost: (body) => apiFetch("/image-to-pixelart", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "ImageToPixelartImageToPixelartPost",
    }),
    // POST /image-to-pixelart-pro
    // Convert image to pixel art (Pro)
    imageToPixelartProImageToPixelartProPost: (body) => apiFetch("/image-to-pixelart-pro", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "ImageToPixelartProImageToPixelartProPost",
    }),
    // POST /resize
    // Resize pixel art image
    resizeImageResizePost: (body) => apiFetch("/resize", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "ResizeImageResizePost",
    }),
    // POST /remove-background
    // Remove background
    removeBackgroundEndpointRemoveBackgroundPost: (body) => apiFetch("/remove-background", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "RemoveBackgroundEndpointRemoveBackgroundPost",
    }),
    // POST /edit-animation-v2
    // Edit animation (Pro)
    editAnimationV2EditAnimationV2Post: (body) => apiFetch("/edit-animation-v2", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "EditAnimationV2EditAnimationV2Post",
    }),
    // POST /interpolation-v2
    // Interpolate (Pro)
    interpolationV2InterpolationV2Post: (body) => apiFetch("/interpolation-v2", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "InterpolationV2InterpolationV2Post",
    }),
    // POST /transfer-outfit-v2
    // Transfer outfit (Pro)
    transferOutfitV2TransferOutfitV2Post: (body) => apiFetch("/transfer-outfit-v2", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "TransferOutfitV2TransferOutfitV2Post",
    }),
    // POST /portrait-character-pro
    // Portrait ↔ character (Pro)
    portraitCharacterProPortraitCharacterProPost: (body) => apiFetch("/portrait-character-pro", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "PortraitCharacterProPortraitCharacterProPost",
    }),
    // GET /portrait-character-pro/{job_id}
    // Get portrait ↔ character job status + result
    getPortraitCharacterPortraitCharacterProJobIDGet: (jobID) => apiFetch(`/portrait-character-pro/${jobID}`, {
        operationId: "GetPortraitCharacterPortraitCharacterProJobIDGet",
    }),
    // POST /characters/{character_id}/portrait
    // Set a character's portrait
    setPortraitCharactersCharacterIDPortraitPost: (characterID, body) => apiFetch(`/characters/${characterID}/portrait`, {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "SetPortraitCharactersCharacterIDPortraitPost",
    }),
    // POST /vocal-animation
    // Generate talking mouth positions for a portrait
    createVocalAnimationVocalAnimationPost: (body) => apiFetch("/vocal-animation", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateVocalAnimationVocalAnimationPost",
    }),
    // GET /vocal-animation/{job_id}
    // Get mouth-position job status + result
    getVocalAnimationVocalAnimationJobIDGet: (jobID) => apiFetch(`/vocal-animation/${jobID}`, {
        operationId: "GetVocalAnimationVocalAnimationJobIDGet",
    }),
    // POST /talking-gif
    // Lip-sync text to a talking GIF (free)
    createTalkingGifTalkingGifPost: (body) => apiFetch("/talking-gif", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateTalkingGifTalkingGifPost",
    }),
    // POST /lip-sync
    // Get the lip-sync frame plan for text (free)
    getLipSyncLipSyncPost: (body) => apiFetch("/lip-sync", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "GetLipSyncLipSyncPost",
    }),
    // POST /generate-font-pro
    // Generate pixel font (Pro)
    generateFontProGenerateFontProPost: (body) => apiFetch("/generate-font-pro", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "GenerateFontProGenerateFontProPost",
    }),
    // GET /generate-font-pro/{job_id}
    // Get font-pro job status + result
    getFontGenerateFontProJobIDGet: (jobID) => apiFetch(`/generate-font-pro/${jobID}`, {
        operationId: "GetFontGenerateFontProJobIDGet",
    }),
    // POST /animate-with-skeleton
    // Animate with skeleton
    animateWithSkeletonAnimateWithSkeletonPost: (body) => apiFetch("/animate-with-skeleton", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "AnimateWithSkeletonAnimateWithSkeletonPost",
    }),
    // POST /animate-with-text
    // Animate with text
    animateWithTextAnimateWithTextPost: (body) => apiFetch("/animate-with-text", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "AnimateWithTextAnimateWithTextPost",
    }),
    // POST /animate-with-text-v2
    // Animate with text (pro)
    animateWithTextV2AnimateWithTextV2Post: (body) => apiFetch("/animate-with-text-v2", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "AnimateWithTextV2AnimateWithTextV2Post",
    }),
    // POST /animate-with-text-v3
    // Animate with text v3
    animateWithTextV3AnimateWithTextV3Post: (body) => apiFetch("/animate-with-text-v3", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "AnimateWithTextV3AnimateWithTextV3Post",
    }),
    // POST /estimate-skeleton
    // Estimate skeleton
    estimateSkeletonEstimateSkeletonPost: (body) => apiFetch("/estimate-skeleton", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "EstimateSkeletonEstimateSkeletonPost",
    }),
    // POST /generate-8-rotations-v2
    // Generate 8 rotations (Pro)
    generate8RotationsV2Generate8RotationsV2Post: (body) => apiFetch("/generate-8-rotations-v2", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "Generate8RotationsV2Generate8RotationsV2Post",
    }),
    // POST /generate-8-rotations-v3
    // Generate 8 rotations v3
    generate8RotationsV3Generate8RotationsV3Post: (body) => apiFetch("/generate-8-rotations-v3", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "Generate8RotationsV3Generate8RotationsV3Post",
    }),
    // POST /rotate
    // Rotate character or object
    generateRotationRotatePost: (body) => apiFetch("/rotate", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "GenerateRotationRotatePost",
    }),
    // POST /inpaint-v3
    // Inpaint image (Pro)
    inpaintV3InpaintV3Post: (body) => apiFetch("/inpaint-v3", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "InpaintV3InpaintV3Post",
    }),
    // POST /inpaint
    // Inpaint image
    generateInpaintingInpaintPost: (body) => apiFetch("/inpaint", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "GenerateInpaintingInpaintPost",
    }),
    // POST /edit-images-v2
    // Edit images (Pro)
    editImagesV2EditImagesV2Post: (body) => apiFetch("/edit-images-v2", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "EditImagesV2EditImagesV2Post",
    }),
    // POST /edit-image
    // Edit image
    editImageEditImagePost: (body) => apiFetch("/edit-image", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "EditImageEditImagePost",
    }),
    // GET /tilesets
    // List user's tilesets
    listTilesetsTilesetsGet: (params = {}) => {
        const q = new URLSearchParams();
        if (params.limit != null) q.set("limit", String(params.limit));
        if (params.offset != null) q.set("offset", String(params.offset));
        return apiFetch(`/tilesets?${q}`, {
            operationId: "ListTilesetsTilesetsGet",
        });
    },
    // POST /tilesets
    // Create a tileset asynchronously
    generateTilesetTilesetsPost: (body) => apiFetch("/tilesets", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "GenerateTilesetTilesetsPost",
    }),
    // POST /create-tileset
    // Create top-down tileset (async processing)
    generateTilesetCreateTilesetPost: (body) => apiFetch("/create-tileset", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "GenerateTilesetCreateTilesetPost",
    }),
    // GET /tilesets/{tileset_id}
    // Get generated tileset by ID
    getTilesetTilesetsTilesetIDGet: (tilesetID) => apiFetch(`/tilesets/${tilesetID}`, {
        operationId: "GetTilesetTilesetsTilesetIDGet",
    }),
    // DELETE /tilesets/{tileset_id}
    // Delete a top-down tileset
    deleteTopdownTilesetTilesetsTilesetIDDelete: (tilesetID) => apiFetch(`/tilesets/${tilesetID}`, {
        method: "DELETE",
        operationId: "DeleteTopdownTilesetTilesetsTilesetIDDelete",
    }),
    // GET /tilesets-sidescroller
    // List your sidescroller tilesets
    listSidescrollerTilesetsTilesetsSidescrollerGet: (params = {}) => {
        const q = new URLSearchParams();
        if (params.limit != null) q.set("limit", String(params.limit));
        if (params.offset != null) q.set("offset", String(params.offset));
        return apiFetch(`/tilesets-sidescroller?${q}`, {
            operationId: "ListSidescrollerTilesetsTilesetsSidescrollerGet",
        });
    },
    // POST /tilesets-sidescroller
    // Create a sidescroller tileset asynchronously
    generateTilesetSidescrollerTilesetsSidescrollerPost: (body) => apiFetch("/tilesets-sidescroller", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "GenerateTilesetSidescrollerTilesetsSidescrollerPost",
    }),
    // POST /create-tileset-sidescroller
    // Create sidescroller tileset (async processing)
    generateTilesetSidescrollerCreateTilesetSidescrollerPost: (body) => apiFetch("/create-tileset-sidescroller", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "GenerateTilesetSidescrollerCreateTilesetSidescrollerPost",
    }),
    // GET /tilesets-sidescroller/{tileset_id}
    // Get a sidescroller tileset by ID
    getSidescrollerTilesetTilesetsSidescrollerTilesetIDGet: (tilesetID) => apiFetch(`/tilesets-sidescroller/${tilesetID}`, {
        operationId: "GetSidescrollerTilesetTilesetsSidescrollerTilesetIDGet",
    }),
    // DELETE /tilesets-sidescroller/{tileset_id}
    // Delete a sidescroller tileset
    deleteSidescrollerTilesetTilesetsSidescrollerTilesetIDDelete: (tilesetID) => apiFetch(`/tilesets-sidescroller/${tilesetID}`, {
        method: "DELETE",
        operationId: "DeleteSidescrollerTilesetTilesetsSidescrollerTilesetIDDelete",
    }),
    // POST /create-isometric-tile
    // Create isometric tile (async processing)
    generateIsometricTileCreateIsometricTilePost: (body) => apiFetch("/create-isometric-tile", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "GenerateIsometricTileCreateIsometricTilePost",
    }),
    // GET /isometric-tiles/{tile_id}
    // Get generated isometric tile by ID
    getIsometricTileIsometricTilesTileIDGet: (tileID) => apiFetch(`/isometric-tiles/${tileID}`, {
        operationId: "GetIsometricTileIsometricTilesTileIDGet",
    }),
    // DELETE /isometric-tiles/{tile_id}
    // Delete an isometric tile
    deleteIsometricTileIsometricTilesTileIDDelete: (tileID) => apiFetch(`/isometric-tiles/${tileID}`, {
        method: "DELETE",
        operationId: "DeleteIsometricTileIsometricTilesTileIDDelete",
    }),
    // GET /isometric-tiles
    // List user's isometric tiles
    listIsometricTilesIsometricTilesGet: (params = {}) => {
        const q = new URLSearchParams();
        if (params.limit != null) q.set("limit", String(params.limit));
        if (params.offset != null) q.set("offset", String(params.offset));
        return apiFetch(`/isometric-tiles?${q}`, {
            operationId: "ListIsometricTilesIsometricTilesGet",
        });
    },
    // POST /create-tiles-pro
    // Create tiles pro (async processing)
    createTilesProCreateTilesProPost: (body) => apiFetch("/create-tiles-pro", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateTilesProCreateTilesProPost",
    }),
    // GET /tiles-pro/{tile_id}
    // Get generated tiles pro by ID
    getTilesProTilesProTileIDGet: (tileID) => apiFetch(`/tiles-pro/${tileID}`, {
        operationId: "GetTilesProTilesProTileIDGet",
    }),
    // DELETE /tiles-pro/{tile_id}
    // Delete a tiles-pro tile
    deleteTilesProTilesProTileIDDelete: (tileID) => apiFetch(`/tiles-pro/${tileID}`, {
        method: "DELETE",
        operationId: "DeleteTilesProTilesProTileIDDelete",
    }),
    // GET /tiles-pro
    // List your tiles-pro tiles
    listTilesProTilesProGet: (params = {}) => {
        const q = new URLSearchParams();
        if (params.limit != null) q.set("limit", String(params.limit));
        if (params.offset != null) q.set("offset", String(params.offset));
        return apiFetch(`/tiles-pro?${q}`, {
            operationId: "ListTilesProTilesProGet",
        });
    },
    // POST /map-objects
    // Create map object
    createMapObjectMapObjectsPost: (body) => apiFetch("/map-objects", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateMapObjectMapObjectsPost",
    }),
    // GET /map-objects/{object_id}
    // Get map object status + metadata
    getMapObjectMapObjectsObjectIDGet: (objectID) => apiFetch(`/map-objects/${objectID}`, {
        operationId: "GetMapObjectMapObjectsObjectIDGet",
    }),
    // POST /create-ui-asset
    // Create UI panel (Pro)
    createUIAssetCreateUIAssetPost: (body) => apiFetch("/create-ui-asset", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateUIAssetCreateUIAssetPost",
    }),
    // GET /ui-assets
    // List UI assets
    listUIAssetsUIAssetsGet: (params = {}) => {
        const q = new URLSearchParams();
        if (params.limit != null) q.set("limit", String(params.limit));
        if (params.offset != null) q.set("offset", String(params.offset));
        return apiFetch(`/ui-assets?${q}`, {
            operationId: "ListUIAssetsUIAssetsGet",
        });
    },
    // GET /ui-assets/{ui_asset_id}
    // Get UI asset
    getUIAssetUIAssetsUIAssetIDGet: (uiAssetID) => apiFetch(`/ui-assets/${uiAssetID}`, {
        operationId: "GetUIAssetUIAssetsUIAssetIDGet",
    }),
    // DELETE /ui-assets/{ui_asset_id}
    // Delete UI asset
    deleteUIAssetUIAssetsUIAssetIDDelete: (uiAssetID) => apiFetch(`/ui-assets/${uiAssetID}`, {
        method: "DELETE",
        operationId: "DeleteUIAssetUIAssetsUIAssetIDDelete",
    }),
    // GET /balance
    // Get balance
    getBalanceBalanceGet: () => apiFetch("/balance", {
        operationId: "GetBalanceBalanceGet",
    }),
    // POST /create-character-with-4-directions
    // Create character with 4 directions
    createCharacterWith4DirectionsCreateCharacterWith4DirectionsPost: (body) => apiFetch("/create-character-with-4-directions", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateCharacterWith4DirectionsCreateCharacterWith4DirectionsPost",
    }),
    // POST /create-character-with-8-directions
    // Create character with 8 directions
    createCharacterWith8DirectionsCreateCharacterWith8DirectionsPost: (body) => apiFetch("/create-character-with-8-directions", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateCharacterWith8DirectionsCreateCharacterWith8DirectionsPost",
    }),
    // POST /create-character-pro
    // Create character with Pro mode (8 directions)
    createCharacterProCreateCharacterProPost: (body) => apiFetch("/create-character-pro", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateCharacterProCreateCharacterProPost",
    }),
    // POST /create-character-v3
    // Create character with v3 model (8 rotations)
    createCharacterV3CreateCharacterV3Post: (body) => apiFetch("/create-character-v3", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateCharacterV3CreateCharacterV3Post",
    }),
    // POST /characters/animations
    // Create Character Animation
    createCharacterAnimationCharactersAnimationsPost: (body) => apiFetch("/characters/animations", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateCharacterAnimationCharactersAnimationsPost",
    }),
    // POST /animate-character
    // Animate character
    createCharacterAnimationAnimateCharacterPost: (body) => apiFetch("/animate-character", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateCharacterAnimationAnimateCharacterPost",
    }),
    // POST /create-character-state
    // Create a state of an existing character
    createCharacterStateCreateCharacterStatePost: (body) => apiFetch("/create-character-state", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateCharacterStateCreateCharacterStatePost",
    }),
    // GET /characters
    // List user's characters
    listCharactersCharactersGet: (params = {}) => {
        const q = new URLSearchParams();
        if (params.limit != null) q.set("limit", String(params.limit));
        if (params.offset != null) q.set("offset", String(params.offset));
        return apiFetch(`/characters?${q}`, {
            operationId: "ListCharactersCharactersGet",
        });
    },
    // GET /characters/{character_id}
    // Get character details
    getCharacterCharactersCharacterIDGet: (characterID) => apiFetch(`/characters/${characterID}`, {
        operationId: "GetCharacterCharactersCharacterIDGet",
    }),
    // DELETE /characters/{character_id}
    // Delete a character and all associated data
    deleteCharacterV2CharactersCharacterIDDelete: (characterID) => apiFetch(`/characters/${characterID}`, {
        method: "DELETE",
        operationId: "DeleteCharacterV2CharactersCharacterIDDelete",
    }),
    // GET /characters/{character_id}/zip
    // Export character as ZIP
    downloadCharacterCharactersCharacterIDZipGet: (characterID, params = {}) => {
        const q = new URLSearchParams();
        if (params.states != null) q.set("states", String(params.states));
        return apiFetch(`/characters/${characterID}/zip?${q}`, {
            operationId: "DownloadCharacterCharactersCharacterIDZipGet",
        });
    },
    // PATCH /characters/{character_id}/tags
    // Update character tags
    updateCharacterTagsCharactersCharacterIDTagsPatch: (characterID, body) => apiFetch(`/characters/${characterID}/tags`, {
        method: "PATCH",
        body: JSON.stringify(body),
        operationId: "UpdateCharacterTagsCharactersCharacterIDTagsPatch",
    }),
    // GET /background-jobs/{job_id}
    // Get background job status
    getBackgroundJobStatusBackgroundJobsJobIDGet: (jobID) => apiFetch(`/background-jobs/${jobID}`, {
        operationId: "GetBackgroundJobStatusBackgroundJobsJobIDGet",
    }),
    // POST /create-1-direction-object
    // Create a 1-direction object
    create1DirectionObjectCreate1DirectionObjectPost: (body) => apiFetch("/create-1-direction-object", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "Create1DirectionObjectCreate1DirectionObjectPost",
    }),
    // POST /create-8-direction-object
    // Create an 8-direction object
    create8DirectionObjectCreate8DirectionObjectPost: (body) => apiFetch("/create-8-direction-object", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "Create8DirectionObjectCreate8DirectionObjectPost",
    }),
    // POST /objects/{object_id}/animations
    // Add an animation to an existing object
    animateObjectObjectsObjectIDAnimationsPost: (objectID, body) => apiFetch(`/objects/${objectID}/animations`, {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "AnimateObjectObjectsObjectIDAnimationsPost",
    }),
    // DELETE /objects/{object_id}/animations
    // Delete animations from an object
    deleteObjectAnimationsObjectsObjectIDAnimationsDelete: (objectID, params = {}) => {
        const q = new URLSearchParams();
        if (params.animationType != null) q.set("animation_type", String(params.animationType));
        if (params.animationGroupID != null) q.set("animation_group_id", String(params.animationGroupID));
        if (params.direction != null) q.set("direction", String(params.direction));
        return apiFetch(`/objects/${objectID}/animations?${q}`, {
            method: "DELETE",
            operationId: "DeleteObjectAnimationsObjectsObjectIDAnimationsDelete",
        });
    },
    // POST /objects/{object_id}/states
    // Create a state of an existing object
    createObjectStateObjectsObjectIDStatesPost: (objectID, body) => apiFetch(`/objects/${objectID}/states`, {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateObjectStateObjectsObjectIDStatesPost",
    }),
    // POST /objects/{object_id}/select-frames
    // Promote selected frames of a review object to completed objects
    selectObjectFramesObjectsObjectIDSelectFramesPost: (objectID, body) => apiFetch(`/objects/${objectID}/select-frames`, {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "SelectObjectFramesObjectsObjectIDSelectFramesPost",
    }),
    // POST /objects/{object_id}/dismiss-review
    // Dismiss a review object without saving any frames
    dismissReviewObjectsObjectIDDismissReviewPost: (objectID) => apiFetch(`/objects/${objectID}/dismiss-review`, {
        method: "POST",
        operationId: "DismissReviewObjectsObjectIDDismissReviewPost",
    }),
    // GET /objects
    // List user's objects
    listObjectsObjectsGet: (params = {}) => {
        const q = new URLSearchParams();
        if (params.limit != null) q.set("limit", String(params.limit));
        if (params.offset != null) q.set("offset", String(params.offset));
        return apiFetch(`/objects?${q}`, {
            operationId: "ListObjectsObjectsGet",
        });
    },
    // GET /objects/{object_id}
    // Get object details
    getObjectObjectsObjectIDGet: (objectID) => apiFetch(`/objects/${objectID}`, {
        operationId: "GetObjectObjectsObjectIDGet",
    }),
    // DELETE /objects/{object_id}
    // Delete an object and all associated data
    deleteObjectObjectsObjectIDDelete: (objectID) => apiFetch(`/objects/${objectID}`, {
        method: "DELETE",
        operationId: "DeleteObjectObjectsObjectIDDelete",
    }),
    // PATCH /objects/{object_id}/tags
    // Update object tags
    updateObjectTagsObjectsObjectIDTagsPatch: (objectID, body) => apiFetch(`/objects/${objectID}/tags`, {
        method: "PATCH",
        body: JSON.stringify(body),
        operationId: "UpdateObjectTagsObjectsObjectIDTagsPatch",
    }),
    // DELETE /characters/{character_id}/animations
    // Delete animations from a character
    deleteCharacterAnimationsCharactersCharacterIDAnimationsDelete: (characterID, params = {}) => {
        const q = new URLSearchParams();
        if (params.animationType != null) q.set("animation_type", String(params.animationType));
        if (params.animationGroupID != null) q.set("animation_group_id", String(params.animationGroupID));
        if (params.direction != null) q.set("direction", String(params.direction));
        return apiFetch(`/characters/${characterID}/animations?${q}`, {
            method: "DELETE",
            operationId: "DeleteCharacterAnimationsCharactersCharacterIDAnimationsDelete",
        });
    },
    // POST /enhance-pixen-prompt
    // Enhance pixen prompt
    enhancePixenPromptEnhancePixenPromptPost: (body) => apiFetch("/enhance-pixen-prompt", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "EnhancePixenPromptEnhancePixenPromptPost",
    }),
    // POST /enhance-character-v3-prompt
    // Enhance character v3 prompt
    enhanceCharacterV3PromptEnhanceCharacterV3PromptPost: (body) => apiFetch("/enhance-character-v3-prompt", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "EnhanceCharacterV3PromptEnhanceCharacterV3PromptPost",
    }),
    // POST /enhance-animation-v3-prompt
    // Enhance animation v3 prompt
    enhanceAnimationV3PromptEnhanceAnimationV3PromptPost: (body) => apiFetch("/enhance-animation-v3-prompt", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "EnhanceAnimationV3PromptEnhanceAnimationV3PromptPost",
    }),
    // GET /llms.txt
    // Get LLM-friendly API documentation
    getLlmsTxtLlmsTxtGet: () => apiFetch("/llms.txt", {
        operationId: "GetLlmsTxtLlmsTxtGet",
    }),
};
