// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

/**
 * Notion Admin API Client
 * =========================
 *
 * Matches the OpenAPI specification. All functions are async and return
 * data or `null` on failure.
 *
 * Usage:
 *   import './api.js';        // or <script src="api.js"></script>
 *   const result = await window.API.exportLegalHold(legalHoldID);
 *   const result = await window.API.getLegalHold(legalHoldID);
 *   const result = await window.API.updateLegalHold(legalHoldID);
 *   const result = await window.API.listLegalHoldUsers(legalHoldID);
 *   const result = await window.API.addLegalHoldUsers(legalHoldID);
 *   const result = await window.API.listLegalHolds();
 *   const result = await window.API.createLegalHold();
 *   const result = await window.API.listLegalHoldWorkspaces(legalHoldID);
 *   const result = await window.API.releaseLegalHold(legalHoldID);
 *   const result = await window.API.removeLegalHoldUser(legalHoldID, userID);
 *   const result = await window.API.enqueueSpaceExport(spaceID);
 *   const result = await window.API.getSpaceExportStatus(exportJobID, spaceID);
 *   const result = await window.API.listLegalHoldPages(legalHoldID, spaceID);
 *   const result = await window.API.revokeUserSession();
 *   const result = await window.API.listMcpClientConnections();
 *   const result = await window.API.updateMcpClientConnectionEnterpriseManagedAccess();
 *   const result = await window.API.revokeMcpClientConnection();
 *   const result = await window.API.retrievePermissionGroup(groupID, spaceID);
 *   const result = await window.API.deletePermissionGroup(groupID, spaceID);
 *   const result = await window.API.updatePermissionGroup(groupID, spaceID);
 *   const result = await window.API.listPermissionGroups(spaceID);
 *   const result = await window.API.createPermissionGroup(spaceID);
 *   const result = await window.API.listUsers(spaceID);
 *   const result = await window.API.listPermissionGroupMembers(groupID, spaceID);
 *   const result = await window.API.addPermissionGroupMember(groupID, spaceID);
 *   const result = await window.API.removePermissionGroupMember(groupID, userID, spaceID);
 *   const result = await window.API.updatePermissionGroupMember(groupID, userID, spaceID);
 *   const result = await window.API.listPersonalAccessTokens(spaceID);
 *   window.API.revokePersonalAccessToken(botID, spaceID);
 *   const result = await window.API.updateAgentCreationPolicy(spaceID);
 *   const result = await window.API.updateWorkspaceCreditLimit(spaceID);
 *   const result = await window.API.updateAgentStatus(agentID, spaceID);
 *   window.API.deleteAgent(agentID, spaceID);
 *   const result = await window.API.getWorkflowsMetadataForSpace(spaceID);
 *   const result = await window.API.getAgentCreditUsage(agentID, spaceID);
 *   const result = await window.API.getAgentPermissions(spaceID, agentID);
 *   const result = await window.API.updateAgentPermissions(spaceID, agentID);
 *   const result = await window.API.getAgentsCreditUsage(spaceID);
 *   const result = await window.API.updateAgentCreditLimit(agentID, spaceID);
 *   const result = await window.API.listCreditLimitPolicies(spaceID);
 *   const result = await window.API.createCreditLimitPolicy(spaceID);
 *   const result = await window.API.expireCreditLimitPolicy(spaceID, policyID);
 *   const result = await window.API.updateCreditLimitPolicy(spaceID, policyID);
 **/

const API_BASE = "https://api.notion.com/admin/v1";
const TIMEOUT = 4000;

// ====================== ENVIRONMENT ======================
window.ENV = "production";

// reportApiError broadcasts a failed API call as a "notionadmin:ws-message"
// CustomEvent, the same channel server-pushed notifications use, so a single
// listener can surface both origins uniformly.
function reportApiError(operationId, status, message) {
    window.dispatchEvent(new CustomEvent("notionadmin:ws-message", {
        detail: {
            level: "error",
            persistent: true,
            title: `${operationId} failed`,
            meta: [`Status ${status}`, message],
        },
    }));
}

async function apiFetch(path, options = {}) {
    const {
        method = "GET", operationId = "Request"
    } = options;
    const ctrl = new AbortController();
    const timeoutId = setTimeout(() => ctrl.abort(), TIMEOUT);

    try {
        const res = await fetch(API_BASE + path, {
            ...options,
            signal: ctrl.signal,
                headers: {
                    "Content-Type": "application/json",
                    ...options.headers,
                },
        });

        clearTimeout(timeoutId);

        if (!res.ok) {
            console.warn(`API Error: ${res.status} ${method} ${path}`);
            let message = res.statusText || "Request failed";
            try {
                const body = await res.clone().json();
                message = body?.message || body?.error || message;
            } catch {}
            reportApiError(operationId, res.status, message);
            return null;
        }

        // JSON is parsed, text is returned as it is, and anything else, such as a zip or an image, as a Blob
        const type = res.headers.get("Content-Type") || "";
        if (type.includes("json")) return await res.json();
        if (type.startsWith("text/")) return await res.text();
        return await res.blob();
    } catch (err) {
        clearTimeout(timeoutId);
        if (err.name === "AbortError") {
            console.error(`Request timeout: ${path}`);
            reportApiError(operationId, "timeout", `${path} did not respond in time`);
        } else {
            console.error(`Request failed: ${path}`, err);
            reportApiError(operationId, "network", err.message || "Network error");
        }
        return null;
    }
}

// ====================== PUBLIC API ======================

window.API = {
    // POST /legal_holds/{legal_hold_id}/export
    // Export a legal hold
    exportLegalHold: (legalHoldID, body) => apiFetch(`/legal_holds/${legalHoldID}/export`, {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "ExportLegalHold",
    }),
    // GET /legal_holds/{legal_hold_id}
    // Retrieve a legal hold
    getLegalHold: (legalHoldID) => apiFetch(`/legal_holds/${legalHoldID}`, {
        operationId: "GetLegalHold",
    }),
    // PATCH /legal_holds/{legal_hold_id}
    // Update a legal hold
    updateLegalHold: (legalHoldID, body) => apiFetch(`/legal_holds/${legalHoldID}`, {
        method: "PATCH",
        body: JSON.stringify(body),
        operationId: "UpdateLegalHold",
    }),
    // GET /legal_holds/{legal_hold_id}/users
    // List users on a legal hold
    listLegalHoldUsers: (legalHoldID, params = {}) => {
        const q = new URLSearchParams();
        if (params.startCursor != null) q.set("start_cursor", String(params.startCursor));
        return apiFetch(`/legal_holds/${legalHoldID}/users?${q}`, {
            operationId: "ListLegalHoldUsers",
        });
    },
    // POST /legal_holds/{legal_hold_id}/users
    // Add users to a legal hold
    addLegalHoldUsers: (legalHoldID, body) => apiFetch(`/legal_holds/${legalHoldID}/users`, {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "AddLegalHoldUsers",
    }),
    // GET /legal_holds
    // List legal holds
    listLegalHolds: (params = {}) => {
        const q = new URLSearchParams();
        if (params.startCursor != null) q.set("start_cursor", String(params.startCursor));
        if (params.userID != null) q.set("user_id", String(params.userID));
        return apiFetch(`/legal_holds?${q}`, {
            operationId: "ListLegalHolds",
        });
    },
    // POST /legal_holds
    // Create a legal hold
    createLegalHold: (body) => apiFetch("/legal_holds", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateLegalHold",
    }),
    // GET /legal_holds/{legal_hold_id}/workspaces
    // List workspaces on a legal hold
    listLegalHoldWorkspaces: (legalHoldID, params = {}) => {
        const q = new URLSearchParams();
        if (params.startCursor != null) q.set("start_cursor", String(params.startCursor));
        return apiFetch(`/legal_holds/${legalHoldID}/workspaces?${q}`, {
            operationId: "ListLegalHoldWorkspaces",
        });
    },
    // POST /legal_holds/{legal_hold_id}/release
    // Release a legal hold
    releaseLegalHold: (legalHoldID) => apiFetch(`/legal_holds/${legalHoldID}/release`, {
        method: "POST",
        operationId: "ReleaseLegalHold",
    }),
    // DELETE /legal_holds/{legal_hold_id}/users/{user_id}
    // Remove a user from a legal hold
    removeLegalHoldUser: (legalHoldID, userID) => apiFetch(`/legal_holds/${legalHoldID}/users/${userID}`, {
        method: "DELETE",
        operationId: "RemoveLegalHoldUser",
    }),
    // POST /spaces/{space_id}/exports
    // Enqueue a workspace export
    enqueueSpaceExport: (spaceID, body) => apiFetch(`/spaces/${spaceID}/exports`, {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "EnqueueSpaceExport",
    }),
    // GET /spaces/{space_id}/exports/{export_job_id}
    // Get workspace export status
    getSpaceExportStatus: (exportJobID, spaceID) => apiFetch(`/spaces/${spaceID}/exports/${exportJobID}`, {
        operationId: "GetSpaceExportStatus",
    }),
    // GET /legal_holds/{legal_hold_id}/spaces/{space_id}/pages
    // List pages on a legal hold
    listLegalHoldPages: (legalHoldID, spaceID, params = {}) => {
        const q = new URLSearchParams();
        if (params.startCursor != null) q.set("start_cursor", String(params.startCursor));
        return apiFetch(`/legal_holds/${legalHoldID}/spaces/${spaceID}/pages?${q}`, {
            operationId: "ListLegalHoldPages",
        });
    },
    // POST /managed_users/revoke_session
    // Revoke a managed user's sessions
    revokeUserSession: (body) => apiFetch("/managed_users/revoke_session", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "RevokeUserSession",
    }),
    // GET /mcp_client_connections
    // List MCP client connections in an organization
    listMcpClientConnections: (params = {}) => {
        const q = new URLSearchParams();
        if (params.cursor != null) q.set("cursor", String(params.cursor));
        if (params.pageSize != null) q.set("page_size", String(params.pageSize));
        for (const v of params.userIds ?? []) q.append("user_ids", String(v));
        for (const v of params.workspaceIds ?? []) q.append("workspace_ids", String(v));
        return apiFetch(`/mcp_client_connections?${q}`, {
            operationId: "ListMcpClientConnections",
        });
    },
    // PUT /mcp_client_connections/enterprise_managed_access
    // Deny or restore enterprise-managed MCP client access
    updateMcpClientConnectionEnterpriseManagedAccess: (body) => apiFetch("/mcp_client_connections/enterprise_managed_access", {
        method: "PUT",
        body: JSON.stringify(body),
        operationId: "UpdateMcpClientConnectionEnterpriseManagedAccess",
    }),
    // POST /mcp_client_connections/revoke
    // Revoke an MCP client connection
    revokeMcpClientConnection: (body) => apiFetch("/mcp_client_connections/revoke", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "RevokeMcpClientConnection",
    }),
    // GET /spaces/{space_id}/groups/{group_id}
    // Retrieve a group
    retrievePermissionGroup: (groupID, spaceID) => apiFetch(`/spaces/${spaceID}/groups/${groupID}`, {
        operationId: "RetrievePermissionGroup",
    }),
    // DELETE /spaces/{space_id}/groups/{group_id}
    // Delete a group
    deletePermissionGroup: (groupID, spaceID, params = {}) => {
        const q = new URLSearchParams();
        if (params.transferToOwnerID != null) q.set("transfer_to_owner_id", String(params.transferToOwnerID));
        return apiFetch(`/spaces/${spaceID}/groups/${groupID}?${q}`, {
            method: "DELETE",
            operationId: "DeletePermissionGroup",
        });
    },
    // PATCH /spaces/{space_id}/groups/{group_id}
    // Update a group
    updatePermissionGroup: (groupID, spaceID, body) => apiFetch(`/spaces/${spaceID}/groups/${groupID}`, {
        method: "PATCH",
        body: JSON.stringify(body),
        operationId: "UpdatePermissionGroup",
    }),
    // GET /spaces/{space_id}/groups
    // List groups
    listPermissionGroups: (spaceID, params = {}) => {
        const q = new URLSearchParams();
        if (params.pageSize != null) q.set("page_size", String(params.pageSize));
        if (params.startCursor != null) q.set("start_cursor", String(params.startCursor));
        return apiFetch(`/spaces/${spaceID}/groups?${q}`, {
            operationId: "ListPermissionGroups",
        });
    },
    // POST /spaces/{space_id}/groups
    // Create a group
    createPermissionGroup: (spaceID, body) => apiFetch(`/spaces/${spaceID}/groups`, {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreatePermissionGroup",
    }),
    // GET /spaces/{space_id}/users
    // List users
    listUsers: (spaceID, params = {}) => {
        const q = new URLSearchParams();
        if (params.startCursor != null) q.set("start_cursor", String(params.startCursor));
        if (params.pageSize != null) q.set("page_size", String(params.pageSize));
        return apiFetch(`/spaces/${spaceID}/users?${q}`, {
            operationId: "ListUsers",
        });
    },
    // GET /spaces/{space_id}/groups/{group_id}/members
    // List group members
    listPermissionGroupMembers: (groupID, spaceID, params = {}) => {
        const q = new URLSearchParams();
        if (params.pageSize != null) q.set("page_size", String(params.pageSize));
        if (params.startCursor != null) q.set("start_cursor", String(params.startCursor));
        return apiFetch(`/spaces/${spaceID}/groups/${groupID}/members?${q}`, {
            operationId: "ListPermissionGroupMembers",
        });
    },
    // POST /spaces/{space_id}/groups/{group_id}/members
    // Add a group member
    addPermissionGroupMember: (groupID, spaceID, body) => apiFetch(`/spaces/${spaceID}/groups/${groupID}/members`, {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "AddPermissionGroupMember",
    }),
    // DELETE /spaces/{space_id}/groups/{group_id}/members/users/{user_id}
    // Remove a group member
    removePermissionGroupMember: (groupID, userID, spaceID) => apiFetch(`/spaces/${spaceID}/groups/${groupID}/members/users/${userID}`, {
        method: "DELETE",
        operationId: "RemovePermissionGroupMember",
    }),
    // PATCH /spaces/{space_id}/groups/{group_id}/members/users/{user_id}
    // Update a group member
    updatePermissionGroupMember: (groupID, userID, spaceID, body) => apiFetch(`/spaces/${spaceID}/groups/${groupID}/members/users/${userID}`, {
        method: "PATCH",
        body: JSON.stringify(body),
        operationId: "UpdatePermissionGroupMember",
    }),
    // GET /spaces/{space_id}/personal_access_tokens
    // List personal access tokens in a workspace
    listPersonalAccessTokens: (spaceID, params = {}) => {
        const q = new URLSearchParams();
        if (params.cursor != null) q.set("cursor", String(params.cursor));
        if (params.pageSize != null) q.set("page_size", String(params.pageSize));
        for (const v of params.status ?? []) q.append("status", String(v));
        for (const v of params.creatorIds ?? []) q.append("creator_ids", String(v));
        if (params.search != null) q.set("search", String(params.search));
        return apiFetch(`/spaces/${spaceID}/personal_access_tokens?${q}`, {
            operationId: "ListPersonalAccessTokens",
        });
    },
    // DELETE /spaces/{space_id}/personal_access_tokens/{bot_id}
    // Revoke a personal access token in a workspace
    revokePersonalAccessToken: (botID, spaceID) => apiFetch(`/spaces/${spaceID}/personal_access_tokens/${botID}`, {
        method: "DELETE",
        operationId: "RevokePersonalAccessToken",
    }),
    // PATCH /spaces/{space_id}/agents/creation_policy
    // Update who can create agents in a space
    updateAgentCreationPolicy: (spaceID, body) => apiFetch(`/spaces/${spaceID}/agents/creation_policy`, {
        method: "PATCH",
        body: JSON.stringify(body),
        operationId: "UpdateAgentCreationPolicy",
    }),
    // PATCH /spaces/{space_id}/credit_limit
    // Update the default agent credit limit for a workspace
    updateWorkspaceCreditLimit: (spaceID, body) => apiFetch(`/spaces/${spaceID}/credit_limit`, {
        method: "PATCH",
        body: JSON.stringify(body),
        operationId: "UpdateWorkspaceCreditLimit",
    }),
    // PATCH /spaces/{space_id}/agents/{agent_id}/status
    // Disable or re-enable an agent in a space
    updateAgentStatus: (agentID, spaceID, body) => apiFetch(`/spaces/${spaceID}/agents/${agentID}/status`, {
        method: "PATCH",
        body: JSON.stringify(body),
        operationId: "UpdateAgentStatus",
    }),
    // DELETE /spaces/{space_id}/agents/{agent_id}
    // Delete an agent in a space
    deleteAgent: (agentID, spaceID) => apiFetch(`/spaces/${spaceID}/agents/${agentID}`, {
        method: "DELETE",
        operationId: "DeleteAgent",
    }),
    // GET /spaces/{space_id}/agents
    // Get agents in a space
    getWorkflowsMetadataForSpace: (spaceID, params = {}) => {
        const q = new URLSearchParams();
        if (params.name != null) q.set("name", String(params.name));
        for (const v of params.createdByIds ?? []) q.append("created_by_ids", String(v));
        if (params.createdTimeFrom != null) q.set("created_time_from", String(params.createdTimeFrom));
        if (params.createdTimeTo != null) q.set("created_time_to", String(params.createdTimeTo));
        if (params.lastEditedTimeFrom != null) q.set("last_edited_time_from", String(params.lastEditedTimeFrom));
        if (params.lastEditedTimeTo != null) q.set("last_edited_time_to", String(params.lastEditedTimeTo));
        if (params.creditUsageTimeFrom != null) q.set("credit_usage_time_from", String(params.creditUsageTimeFrom));
        if (params.creditUsageTimeTo != null) q.set("credit_usage_time_to", String(params.creditUsageTimeTo));
        for (const v of params.status ?? []) q.append("status", String(v));
        for (const v of params.integrationTypes ?? []) q.append("integration_types", String(v));
        for (const v of params.mcpServerNames ?? []) q.append("mcp_server_names", String(v));
        for (const v of params.models ?? []) q.append("models", String(v));
        for (const v of params.sharedWithUserIds ?? []) q.append("shared_with_user_ids", String(v));
        for (const v of params.sharedWithGroupIds ?? []) q.append("shared_with_group_ids", String(v));
        if (params.cursor != null) q.set("cursor", String(params.cursor));
        if (params.pageSize != null) q.set("page_size", String(params.pageSize));
        return apiFetch(`/spaces/${spaceID}/agents?${q}`, {
            operationId: "GetWorkflowsMetadataForSpace",
        });
    },
    // GET /spaces/{space_id}/agents/{agent_id}/credit_usage
    // Get credit usage for an agent in a space
    getAgentCreditUsage: (agentID, spaceID, params = {}) => {
        const q = new URLSearchParams();
        if (params.startCursor != null) q.set("start_cursor", String(params.startCursor));
        return apiFetch(`/spaces/${spaceID}/agents/${agentID}/credit_usage?${q}`, {
            operationId: "GetAgentCreditUsage",
        });
    },
    // GET /spaces/{space_id}/agents/{agent_id}/permissions
    // Get a custom agent's sharing permissions
    getAgentPermissions: (spaceID, agentID, params = {}) => {
        const q = new URLSearchParams();
        if (params.cursor != null) q.set("cursor", String(params.cursor));
        return apiFetch(`/spaces/${spaceID}/agents/${agentID}/permissions?${q}`, {
            operationId: "GetAgentPermissions",
        });
    },
    // PATCH /spaces/{space_id}/agents/{agent_id}/permissions
    // Update a custom agent's sharing permissions
    updateAgentPermissions: (spaceID, agentID, body) => apiFetch(`/spaces/${spaceID}/agents/${agentID}/permissions`, {
        method: "PATCH",
        body: JSON.stringify(body),
        operationId: "UpdateAgentPermissions",
    }),
    // GET /spaces/{space_id}/agents/credit_usage
    // Get credit usage for agents in a space
    getAgentsCreditUsage: (spaceID, params = {}) => {
        const q = new URLSearchParams();
        if (params.cursor != null) q.set("cursor", String(params.cursor));
        if (params.pageSize != null) q.set("page_size", String(params.pageSize));
        if (params.includeDeleted != null) q.set("include_deleted", String(params.includeDeleted));
        if (params.creditUsageTimeFrom != null) q.set("credit_usage_time_from", String(params.creditUsageTimeFrom));
        if (params.creditUsageTimeTo != null) q.set("credit_usage_time_to", String(params.creditUsageTimeTo));
        return apiFetch(`/spaces/${spaceID}/agents/credit_usage?${q}`, {
            operationId: "GetAgentsCreditUsage",
        });
    },
    // PUT /spaces/{space_id}/agents/{agent_id}/credit_limit
    // Update credit limit for an agent in a space
    updateAgentCreditLimit: (agentID, spaceID, body) => apiFetch(`/spaces/${spaceID}/agents/${agentID}/credit_limit`, {
        method: "PUT",
        body: JSON.stringify(body),
        operationId: "UpdateAgentCreditLimit",
    }),
    // GET /spaces/{space_id}/credit_limit_policies
    // List credit limit policies
    listCreditLimitPolicies: (spaceID, params = {}) => {
        const q = new URLSearchParams();
        if (params.pageSize != null) q.set("page_size", String(params.pageSize));
        if (params.startCursor != null) q.set("start_cursor", String(params.startCursor));
        return apiFetch(`/spaces/${spaceID}/credit_limit_policies?${q}`, {
            operationId: "ListCreditLimitPolicies",
        });
    },
    // POST /spaces/{space_id}/credit_limit_policies
    // Create a credit limit policy
    createCreditLimitPolicy: (spaceID, body) => apiFetch(`/spaces/${spaceID}/credit_limit_policies`, {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateCreditLimitPolicy",
    }),
    // DELETE /spaces/{space_id}/credit_limit_policies/{policy_id}
    // Expire a credit limit policy
    expireCreditLimitPolicy: (spaceID, policyID) => apiFetch(`/spaces/${spaceID}/credit_limit_policies/${policyID}`, {
        method: "DELETE",
        operationId: "ExpireCreditLimitPolicy",
    }),
    // PATCH /spaces/{space_id}/credit_limit_policies/{policy_id}
    // Update a credit limit policy
    updateCreditLimitPolicy: (spaceID, policyID, body) => apiFetch(`/spaces/${spaceID}/credit_limit_policies/${policyID}`, {
        method: "PATCH",
        body: JSON.stringify(body),
        operationId: "UpdateCreditLimitPolicy",
    }),
};
