// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package notionadmin

import (
	"context"
	"encoding/json/v2"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"strconv"
	"uuid"

	"github.com/go-api-libs/api/server"
)

// Service defines the operations the server must implement.
type Service interface {
	ExportLegalHold(ctx context.Context, legalHoldID uuid.UUID, body ExportLegalHold) (*ExportLegalHoldOk, error)
	GetLegalHold(ctx context.Context, legalHoldID uuid.UUID) (*LegalHold, error)
	UpdateLegalHold(ctx context.Context, legalHoldID uuid.UUID, body UpdateLegalHold) (*LegalHold, error)
	ListLegalHoldUsers(ctx context.Context, legalHoldID uuid.UUID, params *ListLegalHoldUsersParams) (*ListLegalHoldUsersOk, error)
	AddLegalHoldUsers(ctx context.Context, legalHoldID uuid.UUID, body AddLegalHoldUsers) (*LegalHold, error)
	ListLegalHolds(ctx context.Context, params *ListLegalHoldsParams) (*ListLegalHoldsOk, error)
	CreateLegalHold(ctx context.Context, body CreateLegalHold) (*LegalHold, error)
	ListLegalHoldWorkspaces(ctx context.Context, legalHoldID uuid.UUID, params *ListLegalHoldWorkspacesParams) (*ListLegalHoldWorkspacesOk, error)
	ReleaseLegalHold(ctx context.Context, legalHoldID uuid.UUID) (*LegalHold, error)
	RemoveLegalHoldUser(ctx context.Context, legalHoldID uuid.UUID, userID uuid.UUID) (*LegalHold, error)
	EnqueueSpaceExport(ctx context.Context, spaceID string, body EnqueueSpaceExport) (*EnqueueSpaceExportOk, error)
	GetSpaceExportStatus(ctx context.Context, exportJobID string, spaceID string) (*GetSpaceExportStatusOk, error)
	ListLegalHoldPages(ctx context.Context, legalHoldID uuid.UUID, spaceID uuid.UUID, params *ListLegalHoldPagesParams) (*ListLegalHoldPagesOk, error)
	RevokeUserSession(ctx context.Context, body RevokeUserSession) (*RevokeUserSessionOk, error)
	ListMcpClientConnections(ctx context.Context, params *ListMcpClientConnectionsParams) (*ListMcpClientConnectionsOk, error)
	UpdateMcpClientConnectionEnterpriseManagedAccess(ctx context.Context, body UpdateMcpClientConnectionEnterpriseManagedAccess) (*UpdateMcpClientConnectionEnterpriseManagedAccessOk, error)
	RevokeMcpClientConnection(ctx context.Context, body RevokeMcpClientConnection) (*RevokeMcpClientConnectionOk, error)
	RetrievePermissionGroup(ctx context.Context, groupID IDRequest, spaceID uuid.UUID) (*CreatePermissionGroup2, error)
	DeletePermissionGroup(ctx context.Context, groupID IDRequest, spaceID uuid.UUID, params *DeletePermissionGroupParams) (*CreatePermissionGroup2, error)
	UpdatePermissionGroup(ctx context.Context, groupID IDRequest, spaceID uuid.UUID, body CreatePermissionGroup) (*CreatePermissionGroup2, error)
	ListPermissionGroups(ctx context.Context, spaceID uuid.UUID, params *ListPermissionGroupsParams) (*ListPermissionGroupsOk, error)
	CreatePermissionGroup(ctx context.Context, spaceID uuid.UUID, body CreatePermissionGroup) (*CreatePermissionGroup2, error)
	ListUsers(ctx context.Context, spaceID uuid.UUID, params *ListUsersParams) (*ListUsersOk, error)
	ListPermissionGroupMembers(ctx context.Context, groupID IDRequest, spaceID uuid.UUID, params *ListPermissionGroupMembersParams) (*ListPermissionGroupMembersOk, error)
	AddPermissionGroupMember(ctx context.Context, groupID IDRequest, spaceID uuid.UUID, body AddPermissionGroupMember) (*AddPermissionGroupMember2, error)
	RemovePermissionGroupMember(ctx context.Context, groupID IDRequest, userID IDRequest, spaceID uuid.UUID) (*AddPermissionGroupMember2, error)
	UpdatePermissionGroupMember(ctx context.Context, groupID IDRequest, userID IDRequest, spaceID uuid.UUID, body UpdatePermissionGroupMember) (*AddPermissionGroupMember2, error)
	ListPersonalAccessTokens(ctx context.Context, spaceID uuid.UUID, params *ListPersonalAccessTokensParams) (*ListPersonalAccessTokensOk, error)
	RevokePersonalAccessToken(ctx context.Context, botID uuid.UUID, spaceID uuid.UUID) error
	UpdateAgentCreationPolicy(ctx context.Context, spaceID uuid.UUID, body UpdateAgentCreationPolicy) (*UpdateAgentCreationPolicyOk, error)
	UpdateWorkspaceCreditLimit(ctx context.Context, spaceID uuid.UUID, body UpdateWorkspaceCreditLimit) (*UpdateWorkspaceCreditLimitOk, error)
	UpdateAgentStatus(ctx context.Context, agentID uuid.UUID, spaceID uuid.UUID, body UpdateAgentStatus) (*UpdateAgentStatusOk, error)
	DeleteAgent(ctx context.Context, agentID uuid.UUID, spaceID uuid.UUID) error
	GetWorkflowsMetadataForSpace(ctx context.Context, spaceID uuid.UUID, params *GetWorkflowsMetadataForSpaceParams) (*GetWorkflowsMetadataForSpaceOk, error)
	GetAgentCreditUsage(ctx context.Context, agentID uuid.UUID, spaceID uuid.UUID, params *GetAgentCreditUsageParams) (*AgentCreditUsage, error)
	GetAgentPermissions(ctx context.Context, spaceID uuid.UUID, agentID uuid.UUID, params *GetAgentPermissionsParams) (*GetAgentPermissionsOk, error)
	UpdateAgentPermissions(ctx context.Context, spaceID uuid.UUID, agentID uuid.UUID, body UpdateAgentPermissions) (*UpdateAgentPermissionsOk, error)
	GetAgentsCreditUsage(ctx context.Context, spaceID uuid.UUID, params *GetAgentsCreditUsageParams) (*GetAgentsCreditUsageOk, error)
	UpdateAgentCreditLimit(ctx context.Context, agentID uuid.UUID, spaceID uuid.UUID, body UpdateAgentCreditLimit) (*UpdateAgentCreditLimitOk, error)
	ListCreditLimitPolicies(ctx context.Context, spaceID uuid.UUID, params *ListCreditLimitPoliciesParams) (*ListCreditLimitPoliciesOk, error)
	CreateCreditLimitPolicy(ctx context.Context, spaceID uuid.UUID, body CreateCreditLimitPolicy) (*CreateCreditLimitPolicy2, error)
	ExpireCreditLimitPolicy(ctx context.Context, spaceID uuid.UUID, policyID uuid.UUID) (*CreateCreditLimitPolicy2, error)
	UpdateCreditLimitPolicy(ctx context.Context, spaceID uuid.UUID, policyID uuid.UUID, body UpdateCreditLimitPolicy) (*CreateCreditLimitPolicy2, error)
}

// RegisterService registers a [Service] with an [*http.ServeMux].
// Optionally, a path prefix may be provided.
func RegisterService(svc Service, mux *http.ServeMux, pathPrefix string) {
	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/legal_holds/{legal_hold_id}/export")
		l := slog.Default().With(slog.String("method", "POST"), slog.String("path", path), slog.String("function", "ExportLegalHold"))

		mux.HandleFunc(fmt.Sprintf("POST %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("legal_hold_id")
			legalHoldID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid legal_hold_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			var body ExportLegalHold
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.ExportLegalHold(ctx, legalHoldID, body)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/legal_holds/{legal_hold_id}")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "GetLegalHold"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("legal_hold_id")
			legalHoldID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid legal_hold_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.GetLegalHold(ctx, legalHoldID)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/legal_holds/{legal_hold_id}")
		l := slog.Default().With(slog.String("method", "PATCH"), slog.String("path", path), slog.String("function", "UpdateLegalHold"))

		mux.HandleFunc(fmt.Sprintf("PATCH %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("legal_hold_id")
			legalHoldID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid legal_hold_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			var body UpdateLegalHold
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.UpdateLegalHold(ctx, legalHoldID, body)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/legal_holds/{legal_hold_id}/users")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "ListLegalHoldUsers"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("legal_hold_id")
			legalHoldID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid legal_hold_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			var params ListLegalHoldUsersParams
			q := r.URL.Query()
			if s := q.Get("start_cursor"); s != "" {
				params.StartCursor = s
			}

			res, err := svc.ListLegalHoldUsers(ctx, legalHoldID, &params)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/legal_holds/{legal_hold_id}/users")
		l := slog.Default().With(slog.String("method", "POST"), slog.String("path", path), slog.String("function", "AddLegalHoldUsers"))

		mux.HandleFunc(fmt.Sprintf("POST %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("legal_hold_id")
			legalHoldID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid legal_hold_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			var body AddLegalHoldUsers
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.AddLegalHoldUsers(ctx, legalHoldID, body)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/legal_holds")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "ListLegalHolds"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			var params ListLegalHoldsParams
			q := r.URL.Query()
			if s := q.Get("start_cursor"); s != "" {
				params.StartCursor = s
			}
			if s := q.Get("user_id"); s != "" {
				rawParam, err := uuid.Parse(s)
				if err != nil {
					msg := fmt.Sprintf("invalid user_id: %v", err)
					l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
					http.Error(w, msg, http.StatusBadRequest)
					return
				}
				params.UserID = rawParam
			}

			res, err := svc.ListLegalHolds(ctx, &params)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/legal_holds")
		l := slog.Default().With(slog.String("method", "POST"), slog.String("path", path), slog.String("function", "CreateLegalHold"))

		mux.HandleFunc(fmt.Sprintf("POST %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			var body CreateLegalHold
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.CreateLegalHold(ctx, body)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/legal_holds/{legal_hold_id}/workspaces")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "ListLegalHoldWorkspaces"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("legal_hold_id")
			legalHoldID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid legal_hold_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			var params ListLegalHoldWorkspacesParams
			q := r.URL.Query()
			if s := q.Get("start_cursor"); s != "" {
				params.StartCursor = s
			}

			res, err := svc.ListLegalHoldWorkspaces(ctx, legalHoldID, &params)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/legal_holds/{legal_hold_id}/release")
		l := slog.Default().With(slog.String("method", "POST"), slog.String("path", path), slog.String("function", "ReleaseLegalHold"))

		mux.HandleFunc(fmt.Sprintf("POST %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("legal_hold_id")
			legalHoldID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid legal_hold_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.ReleaseLegalHold(ctx, legalHoldID)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/legal_holds/{legal_hold_id}/users/{user_id}")
		l := slog.Default().With(slog.String("method", "DELETE"), slog.String("path", path), slog.String("function", "RemoveLegalHoldUser"))

		mux.HandleFunc(fmt.Sprintf("DELETE %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("legal_hold_id")
			legalHoldID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid legal_hold_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			s = r.PathValue("user_id")
			userID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid user_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.RemoveLegalHoldUser(ctx, legalHoldID, userID)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/exports")
		l := slog.Default().With(slog.String("method", "POST"), slog.String("path", path), slog.String("function", "EnqueueSpaceExport"))

		mux.HandleFunc(fmt.Sprintf("POST %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			spaceID := r.PathValue("space_id")
			var body EnqueueSpaceExport
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.EnqueueSpaceExport(ctx, spaceID, body)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/exports/{export_job_id}")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "GetSpaceExportStatus"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			exportJobID := r.PathValue("export_job_id")
			spaceID := r.PathValue("space_id")

			res, err := svc.GetSpaceExportStatus(ctx, exportJobID, spaceID)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/legal_holds/{legal_hold_id}/spaces/{space_id}/pages")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "ListLegalHoldPages"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("legal_hold_id")
			legalHoldID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid legal_hold_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			s = r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			var params ListLegalHoldPagesParams
			q := r.URL.Query()
			if s := q.Get("start_cursor"); s != "" {
				params.StartCursor = s
			}

			res, err := svc.ListLegalHoldPages(ctx, legalHoldID, spaceID, &params)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/managed_users/revoke_session")
		l := slog.Default().With(slog.String("method", "POST"), slog.String("path", path), slog.String("function", "RevokeUserSession"))

		mux.HandleFunc(fmt.Sprintf("POST %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			var body RevokeUserSession
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.RevokeUserSession(ctx, body)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/mcp_client_connections")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "ListMcpClientConnections"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			var params ListMcpClientConnectionsParams
			q := r.URL.Query()
			if s := q.Get("cursor"); s != "" {
				params.Cursor = s
			}
			if s := q.Get("page_size"); s != "" {
				params.PageSize = s
			}
			for _, s := range q["user_ids"] {
				rawParam, err := uuid.Parse(s)
				if err != nil {
					msg := fmt.Sprintf("invalid user_ids: %v", err)
					l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
					http.Error(w, msg, http.StatusBadRequest)
					return
				}

				params.UserIds = append(params.UserIds, rawParam)
			}
			for _, s := range q["workspace_ids"] {
				rawParam, err := uuid.Parse(s)
				if err != nil {
					msg := fmt.Sprintf("invalid workspace_ids: %v", err)
					l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
					http.Error(w, msg, http.StatusBadRequest)
					return
				}

				params.WorkspaceIds = append(params.WorkspaceIds, rawParam)
			}

			res, err := svc.ListMcpClientConnections(ctx, &params)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/mcp_client_connections/enterprise_managed_access")
		l := slog.Default().With(slog.String("method", "PUT"), slog.String("path", path), slog.String("function", "UpdateMcpClientConnectionEnterpriseManagedAccess"))

		mux.HandleFunc(fmt.Sprintf("PUT %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			var body UpdateMcpClientConnectionEnterpriseManagedAccess
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.UpdateMcpClientConnectionEnterpriseManagedAccess(ctx, body)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/mcp_client_connections/revoke")
		l := slog.Default().With(slog.String("method", "POST"), slog.String("path", path), slog.String("function", "RevokeMcpClientConnection"))

		mux.HandleFunc(fmt.Sprintf("POST %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			var body RevokeMcpClientConnection
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.RevokeMcpClientConnection(ctx, body)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/groups/{group_id}")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "RetrievePermissionGroup"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("group_id")
			groupID := IDRequest(s)
			s = r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.RetrievePermissionGroup(ctx, groupID, spaceID)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/groups/{group_id}")
		l := slog.Default().With(slog.String("method", "DELETE"), slog.String("path", path), slog.String("function", "DeletePermissionGroup"))

		mux.HandleFunc(fmt.Sprintf("DELETE %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("group_id")
			groupID := IDRequest(s)
			s = r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			var params DeletePermissionGroupParams
			q := r.URL.Query()
			if s := q.Get("transfer_to_owner_id"); s != "" {
				params.TransferToOwnerID = IDRequest(s)
			}

			res, err := svc.DeletePermissionGroup(ctx, groupID, spaceID, &params)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/groups/{group_id}")
		l := slog.Default().With(slog.String("method", "PATCH"), slog.String("path", path), slog.String("function", "UpdatePermissionGroup"))

		mux.HandleFunc(fmt.Sprintf("PATCH %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("group_id")
			groupID := IDRequest(s)
			s = r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			var body CreatePermissionGroup
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.UpdatePermissionGroup(ctx, groupID, spaceID, body)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/groups")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "ListPermissionGroups"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			var params ListPermissionGroupsParams
			q := r.URL.Query()
			if s := q.Get("page_size"); s != "" {
				rawParam, err := strconv.Atoi(s)
				if err != nil {
					msg := fmt.Sprintf("invalid page_size: %v", err)
					l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
					http.Error(w, msg, http.StatusBadRequest)
					return
				}
				params.PageSize = rawParam
			}
			if s := q.Get("start_cursor"); s != "" {
				params.StartCursor = s
			}

			res, err := svc.ListPermissionGroups(ctx, spaceID, &params)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/groups")
		l := slog.Default().With(slog.String("method", "POST"), slog.String("path", path), slog.String("function", "CreatePermissionGroup"))

		mux.HandleFunc(fmt.Sprintf("POST %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			var body CreatePermissionGroup
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.CreatePermissionGroup(ctx, spaceID, body)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/users")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "ListUsers"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			var params ListUsersParams
			q := r.URL.Query()
			if s := q.Get("start_cursor"); s != "" {
				params.StartCursor = s
			}
			if s := q.Get("page_size"); s != "" {
				rawParam, err := strconv.Atoi(s)
				if err != nil {
					msg := fmt.Sprintf("invalid page_size: %v", err)
					l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
					http.Error(w, msg, http.StatusBadRequest)
					return
				}
				params.PageSize = rawParam
			}

			res, err := svc.ListUsers(ctx, spaceID, &params)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/groups/{group_id}/members")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "ListPermissionGroupMembers"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("group_id")
			groupID := IDRequest(s)
			s = r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			var params ListPermissionGroupMembersParams
			q := r.URL.Query()
			if s := q.Get("page_size"); s != "" {
				rawParam, err := strconv.Atoi(s)
				if err != nil {
					msg := fmt.Sprintf("invalid page_size: %v", err)
					l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
					http.Error(w, msg, http.StatusBadRequest)
					return
				}
				params.PageSize = rawParam
			}
			if s := q.Get("start_cursor"); s != "" {
				params.StartCursor = s
			}

			res, err := svc.ListPermissionGroupMembers(ctx, groupID, spaceID, &params)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/groups/{group_id}/members")
		l := slog.Default().With(slog.String("method", "POST"), slog.String("path", path), slog.String("function", "AddPermissionGroupMember"))

		mux.HandleFunc(fmt.Sprintf("POST %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("group_id")
			groupID := IDRequest(s)
			s = r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			var body AddPermissionGroupMember
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.AddPermissionGroupMember(ctx, groupID, spaceID, body)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/groups/{group_id}/members/users/{user_id}")
		l := slog.Default().With(slog.String("method", "DELETE"), slog.String("path", path), slog.String("function", "RemovePermissionGroupMember"))

		mux.HandleFunc(fmt.Sprintf("DELETE %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("group_id")
			groupID := IDRequest(s)
			s = r.PathValue("user_id")
			userID := IDRequest(s)
			s = r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.RemovePermissionGroupMember(ctx, groupID, userID, spaceID)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/groups/{group_id}/members/users/{user_id}")
		l := slog.Default().With(slog.String("method", "PATCH"), slog.String("path", path), slog.String("function", "UpdatePermissionGroupMember"))

		mux.HandleFunc(fmt.Sprintf("PATCH %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("group_id")
			groupID := IDRequest(s)
			s = r.PathValue("user_id")
			userID := IDRequest(s)
			s = r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			var body UpdatePermissionGroupMember
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.UpdatePermissionGroupMember(ctx, groupID, userID, spaceID, body)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/personal_access_tokens")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "ListPersonalAccessTokens"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			var params ListPersonalAccessTokensParams
			q := r.URL.Query()
			if s := q.Get("cursor"); s != "" {
				params.Cursor = s
			}
			if s := q.Get("page_size"); s != "" {
				params.PageSize = s
			}
			for _, s := range q["status"] {
				params.Status = append(params.Status, StatusOneOfItem(s))
			}
			for _, s := range q["creator_ids"] {
				rawParam, err := uuid.Parse(s)
				if err != nil {
					msg := fmt.Sprintf("invalid creator_ids: %v", err)
					l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
					http.Error(w, msg, http.StatusBadRequest)
					return
				}

				params.CreatorIds = append(params.CreatorIds, rawParam)
			}
			if s := q.Get("search"); s != "" {
				params.Search = s
			}

			res, err := svc.ListPersonalAccessTokens(ctx, spaceID, &params)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/personal_access_tokens/{bot_id}")
		l := slog.Default().With(slog.String("method", "DELETE"), slog.String("path", path), slog.String("function", "RevokePersonalAccessToken"))

		mux.HandleFunc(fmt.Sprintf("DELETE %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("bot_id")
			botID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid bot_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			s = r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			if err := svc.RevokePersonalAccessToken(ctx, botID, spaceID); err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if _, err := io.WriteString(w, "{}"); err != nil {
				l.ErrorContext(ctx, "write error", slog.String("error", err.Error()))
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/agents/creation_policy")
		l := slog.Default().With(slog.String("method", "PATCH"), slog.String("path", path), slog.String("function", "UpdateAgentCreationPolicy"))

		mux.HandleFunc(fmt.Sprintf("PATCH %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			var body UpdateAgentCreationPolicy
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.UpdateAgentCreationPolicy(ctx, spaceID, body)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/credit_limit")
		l := slog.Default().With(slog.String("method", "PATCH"), slog.String("path", path), slog.String("function", "UpdateWorkspaceCreditLimit"))

		mux.HandleFunc(fmt.Sprintf("PATCH %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			var body UpdateWorkspaceCreditLimit
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.UpdateWorkspaceCreditLimit(ctx, spaceID, body)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/agents/{agent_id}/status")
		l := slog.Default().With(slog.String("method", "PATCH"), slog.String("path", path), slog.String("function", "UpdateAgentStatus"))

		mux.HandleFunc(fmt.Sprintf("PATCH %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("agent_id")
			agentID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid agent_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			s = r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			var body UpdateAgentStatus
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.UpdateAgentStatus(ctx, agentID, spaceID, body)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/agents/{agent_id}")
		l := slog.Default().With(slog.String("method", "DELETE"), slog.String("path", path), slog.String("function", "DeleteAgent"))

		mux.HandleFunc(fmt.Sprintf("DELETE %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("agent_id")
			agentID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid agent_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			s = r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			if err := svc.DeleteAgent(ctx, agentID, spaceID); err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if _, err := io.WriteString(w, "{}"); err != nil {
				l.ErrorContext(ctx, "write error", slog.String("error", err.Error()))
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/agents")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "GetWorkflowsMetadataForSpace"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			var params GetWorkflowsMetadataForSpaceParams
			q := r.URL.Query()
			if s := q.Get("name"); s != "" {
				params.Name = s
			}
			for _, s := range q["created_by_ids"] {
				rawParam, err := uuid.Parse(s)
				if err != nil {
					msg := fmt.Sprintf("invalid created_by_ids: %v", err)
					l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
					http.Error(w, msg, http.StatusBadRequest)
					return
				}

				params.CreatedByIds = append(params.CreatedByIds, rawParam)
			}
			if s := q.Get("created_time_from"); s != "" {
				params.CreatedTimeFrom = s
			}
			if s := q.Get("created_time_to"); s != "" {
				params.CreatedTimeTo = s
			}
			if s := q.Get("last_edited_time_from"); s != "" {
				params.LastEditedTimeFrom = s
			}
			if s := q.Get("last_edited_time_to"); s != "" {
				params.LastEditedTimeTo = s
			}
			if s := q.Get("credit_usage_time_from"); s != "" {
				params.CreditUsageTimeFrom = s
			}
			if s := q.Get("credit_usage_time_to"); s != "" {
				params.CreditUsageTimeTo = s
			}
			for _, s := range q["status"] {
				params.Status = append(params.Status, StatusItem(s))
			}
			for _, s := range q["integration_types"] {
				params.IntegrationTypes = append(params.IntegrationTypes, s)
			}
			for _, s := range q["mcp_server_names"] {
				params.McpServerNames = append(params.McpServerNames, s)
			}
			for _, s := range q["models"] {
				params.Models = append(params.Models, s)
			}
			for _, s := range q["shared_with_user_ids"] {
				rawParam, err := uuid.Parse(s)
				if err != nil {
					msg := fmt.Sprintf("invalid shared_with_user_ids: %v", err)
					l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
					http.Error(w, msg, http.StatusBadRequest)
					return
				}

				params.SharedWithUserIds = append(params.SharedWithUserIds, rawParam)
			}
			for _, s := range q["shared_with_group_ids"] {
				rawParam, err := uuid.Parse(s)
				if err != nil {
					msg := fmt.Sprintf("invalid shared_with_group_ids: %v", err)
					l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
					http.Error(w, msg, http.StatusBadRequest)
					return
				}

				params.SharedWithGroupIds = append(params.SharedWithGroupIds, rawParam)
			}
			if s := q.Get("cursor"); s != "" {
				params.Cursor = s
			}
			if s := q.Get("page_size"); s != "" {
				rawParam, err := strconv.Atoi(s)
				if err != nil {
					msg := fmt.Sprintf("invalid page_size: %v", err)
					l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
					http.Error(w, msg, http.StatusBadRequest)
					return
				}
				params.PageSize = rawParam
			}

			res, err := svc.GetWorkflowsMetadataForSpace(ctx, spaceID, &params)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/agents/{agent_id}/credit_usage")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "GetAgentCreditUsage"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("agent_id")
			agentID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid agent_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			s = r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			var params GetAgentCreditUsageParams
			q := r.URL.Query()
			if s := q.Get("start_cursor"); s != "" {
				params.StartCursor = s
			}

			res, err := svc.GetAgentCreditUsage(ctx, agentID, spaceID, &params)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/agents/{agent_id}/permissions")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "GetAgentPermissions"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			s = r.PathValue("agent_id")
			agentID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid agent_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			var params GetAgentPermissionsParams
			q := r.URL.Query()
			if s := q.Get("cursor"); s != "" {
				params.Cursor = s
			}

			res, err := svc.GetAgentPermissions(ctx, spaceID, agentID, &params)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/agents/{agent_id}/permissions")
		l := slog.Default().With(slog.String("method", "PATCH"), slog.String("path", path), slog.String("function", "UpdateAgentPermissions"))

		mux.HandleFunc(fmt.Sprintf("PATCH %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			s = r.PathValue("agent_id")
			agentID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid agent_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			var body UpdateAgentPermissions
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.UpdateAgentPermissions(ctx, spaceID, agentID, body)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/agents/credit_usage")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "GetAgentsCreditUsage"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			var params GetAgentsCreditUsageParams
			q := r.URL.Query()
			if s := q.Get("cursor"); s != "" {
				params.Cursor = s
			}
			if s := q.Get("page_size"); s != "" {
				rawParam, err := strconv.Atoi(s)
				if err != nil {
					msg := fmt.Sprintf("invalid page_size: %v", err)
					l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
					http.Error(w, msg, http.StatusBadRequest)
					return
				}
				params.PageSize = rawParam
			}
			if s := q.Get("include_deleted"); s != "" {
				params.IncludeDeleted = IncludeDeleted(s)
			}
			if s := q.Get("credit_usage_time_from"); s != "" {
				params.CreditUsageTimeFrom = s
			}
			if s := q.Get("credit_usage_time_to"); s != "" {
				params.CreditUsageTimeTo = s
			}

			res, err := svc.GetAgentsCreditUsage(ctx, spaceID, &params)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/agents/{agent_id}/credit_limit")
		l := slog.Default().With(slog.String("method", "PUT"), slog.String("path", path), slog.String("function", "UpdateAgentCreditLimit"))

		mux.HandleFunc(fmt.Sprintf("PUT %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("agent_id")
			agentID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid agent_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			s = r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			var body UpdateAgentCreditLimit
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.UpdateAgentCreditLimit(ctx, agentID, spaceID, body)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/credit_limit_policies")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "ListCreditLimitPolicies"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			var params ListCreditLimitPoliciesParams
			q := r.URL.Query()
			if s := q.Get("page_size"); s != "" {
				rawParam, err := strconv.Atoi(s)
				if err != nil {
					msg := fmt.Sprintf("invalid page_size: %v", err)
					l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
					http.Error(w, msg, http.StatusBadRequest)
					return
				}
				params.PageSize = rawParam
			}
			if s := q.Get("start_cursor"); s != "" {
				params.StartCursor = s
			}

			res, err := svc.ListCreditLimitPolicies(ctx, spaceID, &params)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/credit_limit_policies")
		l := slog.Default().With(slog.String("method", "POST"), slog.String("path", path), slog.String("function", "CreateCreditLimitPolicy"))

		mux.HandleFunc(fmt.Sprintf("POST %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			var body CreateCreditLimitPolicy
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.CreateCreditLimitPolicy(ctx, spaceID, body)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/credit_limit_policies/{policy_id}")
		l := slog.Default().With(slog.String("method", "DELETE"), slog.String("path", path), slog.String("function", "ExpireCreditLimitPolicy"))

		mux.HandleFunc(fmt.Sprintf("DELETE %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			s = r.PathValue("policy_id")
			policyID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid policy_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.ExpireCreditLimitPolicy(ctx, spaceID, policyID)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}

	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/spaces/{space_id}/credit_limit_policies/{policy_id}")
		l := slog.Default().With(slog.String("method", "PATCH"), slog.String("path", path), slog.String("function", "UpdateCreditLimitPolicy"))

		mux.HandleFunc(fmt.Sprintf("PATCH %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			s := r.PathValue("space_id")
			spaceID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid space_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			s = r.PathValue("policy_id")
			policyID, err := uuid.Parse(s)
			if err != nil {
				msg := fmt.Sprintf("invalid policy_id: %v", err)
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}
			var body UpdateCreditLimitPolicy
			if err := json.UnmarshalRead(r.Body, &body, jsonOpts); err != nil {
				msg := err.Error()
				l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
				http.Error(w, msg, http.StatusBadRequest)
				return
			}

			res, err := svc.UpdateCreditLimitPolicy(ctx, spaceID, policyID, body)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}
}
