// This file provides a client with methods as well as functions to interact with the HTTP API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package example

import (
	"context"
	"encoding/json/v2"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"strings"

	"github.com/go-api-libs/api"
)

const defaultUserAgent = "My Example API"

var defaultBaseURL = &url.URL{
	Scheme: "https",
	Host:   "api.retrodiffusion.ai",
	Path:   "/v1/styles",
}

// Client is an HTTP client for the example API.
type Client struct {
	// The HTTP client to use for requests.
	cli *http.Client
	// The API key
	apiKey string
	// The base URL
	baseURL *url.URL
	// The user agent
	userAgent string
}

// ClientOption configures a [Client].
type ClientOption func(*Client)

// WithBaseURL returns a [ClientOption] that overrides the default base URL.
// It will prefix a leading slash to the path if there is none.
func WithBaseURL(baseURL *url.URL) ClientOption {
	if !strings.HasPrefix(baseURL.Path, "/") {
		baseURL.Path = "/" + baseURL.Path
	}

	return func(c *Client) { c.baseURL = baseURL }
}

// WithHTTPClient returns a [ClientOption] that sets a custom HTTP client.
func WithHTTPClient(cli *http.Client) ClientOption {
	return func(c *Client) { c.cli = cli }
}

// WithAPIKey returns a [ClientOption] that sets a custom API key.
func WithAPIKey(apiKey string) ClientOption {
	return func(c *Client) { c.apiKey = apiKey }
}

// NewClient creates a new Client.
func NewClient(opts ...ClientOption) (*Client, error) {
	c := &Client{
		cli:       http.DefaultClient,
		baseURL:   defaultBaseURL,
		userAgent: defaultUserAgent,
	}

	c.apiKey = os.Getenv("MY_EXAMPLE_API_KEY")

	for _, opt := range opts {
		opt(c)
	}

	if c.apiKey == "" {
		return nil, errors.New("api key MY_EXAMPLE_API_KEY not provided")
	}

	return c, nil
}

// Live style catalog with limits
//
//	GET /selector
func (c *Client) ListAvailableStyles(ctx context.Context, params *ListAvailableStylesParams) (*StyleDescriptors, error) {
	return c.ListAvailableStylesWithResult[StyleDescriptors](ctx, params)
}

// Live style catalog with limits
// You can define a custom result to unmarshal the response into.
//
//	GET /selector
func (c *Client) ListAvailableStylesWithResult[R any](ctx context.Context, params *ListAvailableStylesParams) (*R, error) {
	u := c.baseURL.JoinPath("selector")
	if params != nil {
		q := make(url.Values, 2)

		if params.Model != "" {
			q["model"] = []string{params.Model}
		}

		if params.Tab != 0 {
			q["tab"] = []string{fmt.Sprint(params.Tab)}
		}

		u.RawQuery = q.Encode()
	}

	req := (&http.Request{
		Header: http.Header{
			"X-Rd-Token": []string{c.apiKey},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Array of style descriptors
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Delete user style
//
//	DELETE /{style_id}
func (c *Client) DeleteUserStyle(ctx context.Context, styleID PromptStyle) (*DeleteUserStyleOkJSONResponse, error) {
	return c.DeleteUserStyleWithResult[DeleteUserStyleOkJSONResponse](ctx, styleID)
}

// Delete user style
// You can define a custom result to unmarshal the response into.
//
//	DELETE /{style_id}
func (c *Client) DeleteUserStyleWithResult[R any](ctx context.Context, styleID PromptStyle) (*R, error) {
	u := c.baseURL.JoinPath(fmt.Sprint(styleID))
	req := (&http.Request{
		Header: http.Header{
			"X-Rd-Token": []string{c.apiKey},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodDelete,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Deleted
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}
