// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package example

import (
	"context"
	"encoding/json/v2"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"time"

	"github.com/go-api-libs/api/server"
)

// Service defines the operations the server must implement.
type Service interface {
	ListAllStateVectors(ctx context.Context, params *ListAllStateVectorsParams) (*CurrentStates, error)
}

// RegisterService registers a [Service] with an [*http.ServeMux].
// Optionally, a path prefix may be provided.
func RegisterService(svc Service, mux *http.ServeMux, pathPrefix string) {
	{
		path := fmt.Sprintf("%s%s", pathPrefix, "/api/states/all")
		l := slog.Default().With(slog.String("method", "GET"), slog.String("path", path), slog.String("function", "ListAllStateVectors"))

		mux.HandleFunc(fmt.Sprintf("GET %s", path), func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()
			l.DebugContext(ctx, "called")

			var params ListAllStateVectorsParams
			q := r.URL.Query()
			if s := q.Get("begin"); s != "" {
				rawParam, err := time.Parse(time.RFC3339, s)
				if err != nil {
					msg := fmt.Sprintf("invalid begin: %v", err)
					l.DebugContext(ctx, "Bad Request", slog.String("msg", msg))
					http.Error(w, msg, http.StatusBadRequest)
					return
				}
				params.Begin = rawParam
			}

			res, err := svc.ListAllStateVectors(ctx, &params)
			if err != nil {
				sErr, ok := errors.AsType[*server.Error](err)
				if !ok {
					l.ErrorContext(ctx, "Internal Server Error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
					return
				}

				l.DebugContext(ctx, "graceful error", slog.String("error", err.Error()))

				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(sErr.Code)

				if err := json.MarshalWrite(w, err); err != nil {
					l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
					http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				}
				return
			}

			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)

			if err := json.MarshalWrite(w, res, jsonOpts); err != nil {
				l.ErrorContext(ctx, "marshal error", slog.String("error", err.Error()))
				http.Error(w, "Internal Server Error", http.StatusInternalServerError)
				return
			}

			l.DebugContext(ctx, "success")
		})
	}
}
