// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

/**
 * Notion API Client
 * =========================
 *
 * Matches the OpenAPI specification. All functions are async and return
 * data or `null` on failure.
 *
 * Usage:
 *   import './api.js';        // or <script src="api.js"></script>
 *   const result = await window.API.getSelf();
 *   const result = await window.API.getUser(userID);
 *   const result = await window.API.getUsers();
 *   const result = await window.API.postPage();
 *   const result = await window.API.retrieveAPage(pageID);
 *   const result = await window.API.patchPage(pageID);
 *   const result = await window.API.movePage(pageID);
 *   const result = await window.API.retrieveAPageProperty(pageID, propertyID);
 *   const result = await window.API.retrievePageMarkdown(pageID);
 *   const result = await window.API.updatePageMarkdown(pageID);
 *   const result = await window.API.retrieveAsyncTask(taskID);
 *   const result = await window.API.retrieveABlock(blockID);
 *   const result = await window.API.deleteABlock(blockID);
 *   const result = await window.API.updateABlock(blockID);
 *   const result = await window.API.getBlockChildren(blockID);
 *   const result = await window.API.patchBlockChildren(blockID);
 *   const result = await window.API.retrieveADataSource(dataSourceID);
 *   const result = await window.API.updateADataSource(dataSourceID);
 *   const result = await window.API.postDatabaseQuery(dataSourceID);
 *   const result = await window.API.createADatabase();
 *   const result = await window.API.listDataSourceTemplates(dataSourceID);
 *   const result = await window.API.retrieveDatabase(databaseID);
 *   const result = await window.API.updateDatabase(databaseID);
 *   const result = await window.API.createDatabase();
 *   const result = await window.API.postSearch();
 *   const result = await window.API.listComments();
 *   const result = await window.API.createAComment();
 *   const result = await window.API.retrieveComment(commentID);
 *   const result = await window.API.deleteAComment(commentID);
 *   const result = await window.API.updateAComment(commentID);
 *   const result = await window.API.listFileUploads();
 *   const result = await window.API.createFile();
 *   const result = await window.API.uploadFile(fileUploadID);
 *   const result = await window.API.completeFileUpload(fileUploadID);
 *   const result = await window.API.retrieveFileUpload(fileUploadID);
 *   const result = await window.API.listCustomEmojis();
 *   const result = await window.API.listViews();
 *   const result = await window.API.createView();
 *   const result = await window.API.retrieveAView(viewID);
 *   const result = await window.API.deleteView(viewID);
 *   const result = await window.API.updateAView(viewID);
 *   const result = await window.API.createViewQuery(viewID);
 *   const result = await window.API.getViewQueryResults(viewID, queryID);
 *   const result = await window.API.deleteViewQuery(viewID, queryID);
 *   const result = await window.API.createMeetingNote();
 *   const result = await window.API.queryMeetingNotes();
 *   const result = await window.API.queryAgents();
 *   const result = await window.API.getAgent(agentID);
 *   const result = await window.API.deleteAgent(agentID);
 *   const result = await window.API.getAgentInsights(agentID);
 *   const result = await window.API.updateAgentStatus(agentID);
 *   const result = await window.API.updateAgentCreditLimit(agentID);
 *   const result = await window.API.agentBatch();
 *   const result = await window.API.listSkillsPlugins();
 *   const result = await window.API.getPluginDirectory(id);
 *   const result = await window.API.getSkillDirectory(id);
 *   const result = await window.API.updateSession();
 *   const result = await window.API.retrieveSession(sessionID);
 *   const result = await window.API.querySessions();
 *   const result = await window.API.querySessionEvents(sessionID);
 *   const result = await window.API.cancelSession(sessionID);
 *   const result = await window.API.createAToken();
 *   const result = await window.API.revokeToken();
 *   const result = await window.API.introspectToken();
 **/

const API_BASE = "https://api.notion.com/v1";
const TIMEOUT = 4000;

// ====================== ENVIRONMENT ======================
window.ENV = "production";

// reportApiError broadcasts a failed API call as a "notionofficial:ws-message"
// CustomEvent, the same channel server-pushed notifications use, so a single
// listener can surface both origins uniformly.
function reportApiError(operationId, status, message) {
    window.dispatchEvent(new CustomEvent("notionofficial:ws-message", {
        detail: {
            level: "error",
            persistent: true,
            title: `${operationId} failed`,
            meta: [`Status ${status}`, message],
        },
    }));
}

async function apiFetch(path, options = {}) {
    const {
        method = "GET", operationId = "Request"
    } = options;
    const ctrl = new AbortController();
    const timeoutId = setTimeout(() => ctrl.abort(), TIMEOUT);

    try {
        const res = await fetch(API_BASE + path, {
            ...options,
            signal: ctrl.signal,
                headers: {
                    "Content-Type": "application/json",
                    ...options.headers,
                },
        });

        clearTimeout(timeoutId);

        if (!res.ok) {
            console.warn(`API Error: ${res.status} ${method} ${path}`);
            let message = res.statusText || "Request failed";
            try {
                const body = await res.clone().json();
                message = body?.message || body?.error || message;
            } catch {}
            reportApiError(operationId, res.status, message);
            return null;
        }

        // JSON is parsed, text is returned as it is, and anything else, such as a zip or an image, as a Blob
        const type = res.headers.get("Content-Type") || "";
        if (type.includes("json")) return await res.json();
        if (type.startsWith("text/")) return await res.text();
        return await res.blob();
    } catch (err) {
        clearTimeout(timeoutId);
        if (err.name === "AbortError") {
            console.error(`Request timeout: ${path}`);
            reportApiError(operationId, "timeout", `${path} did not respond in time`);
        } else {
            console.error(`Request failed: ${path}`, err);
            reportApiError(operationId, "network", err.message || "Network error");
        }
        return null;
    }
}

// ====================== PUBLIC API ======================

window.API = {
    // GET /users/me
    // Retrieve your token's bot user
    getSelf: () => apiFetch("/users/me", {
        operationId: "GetSelf",
    }),
    // GET /users/{user_id}
    // Retrieve a user
    getUser: (userID) => apiFetch(`/users/${userID}`, {
        operationId: "GetUser",
    }),
    // GET /users
    // List all users
    getUsers: (params = {}) => {
        const q = new URLSearchParams();
        if (params.startCursor != null) q.set("start_cursor", String(params.startCursor));
        if (params.pageSize != null) q.set("page_size", String(params.pageSize));
        return apiFetch(`/users?${q}`, {
            operationId: "GetUsers",
        });
    },
    // POST /pages
    // Create a page
    postPage: (params = {}, body) => {
        const q = new URLSearchParams();
        for (const v of params.filterProperties ?? []) q.append("filter_properties", String(v));
        return apiFetch(`/pages?${q}`, {
            method: "POST",
            body: JSON.stringify(body),
            operationId: "PostPage",
        });
    },
    // GET /pages/{page_id}
    // Retrieve a page
    retrieveAPage: (pageID, params = {}) => {
        const q = new URLSearchParams();
        for (const v of params.filterProperties ?? []) q.append("filter_properties", String(v));
        return apiFetch(`/pages/${pageID}?${q}`, {
            operationId: "RetrieveAPage",
        });
    },
    // PATCH /pages/{page_id}
    // Update page
    patchPage: (pageID, params = {}, body) => {
        const q = new URLSearchParams();
        for (const v of params.filterProperties ?? []) q.append("filter_properties", String(v));
        return apiFetch(`/pages/${pageID}?${q}`, {
            method: "PATCH",
            body: JSON.stringify(body),
            operationId: "PatchPage",
        });
    },
    // POST /pages/{page_id}/move
    // Move a page
    movePage: (pageID, body) => apiFetch(`/pages/${pageID}/move`, {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "MovePage",
    }),
    // GET /pages/{page_id}/properties/{property_id}
    // Retrieve a page property item
    retrieveAPageProperty: (pageID, propertyID, params = {}) => {
        const q = new URLSearchParams();
        if (params.startCursor != null) q.set("start_cursor", String(params.startCursor));
        if (params.pageSize != null) q.set("page_size", String(params.pageSize));
        return apiFetch(`/pages/${pageID}/properties/${propertyID}?${q}`, {
            operationId: "RetrieveAPageProperty",
        });
    },
    // GET /pages/{page_id}/markdown
    // Retrieve a page as markdown
    retrievePageMarkdown: (pageID, params = {}) => {
        const q = new URLSearchParams();
        if (params.includeTranscript != null) q.set("include_transcript", String(params.includeTranscript));
        return apiFetch(`/pages/${pageID}/markdown?${q}`, {
            operationId: "RetrievePageMarkdown",
        });
    },
    // PATCH /pages/{page_id}/markdown
    // Update a page's content as markdown
    updatePageMarkdown: (pageID, body) => apiFetch(`/pages/${pageID}/markdown`, {
        method: "PATCH",
        body: JSON.stringify(body),
        operationId: "UpdatePageMarkdown",
    }),
    // GET /async_tasks/{task_id}
    // Retrieve an async task
    retrieveAsyncTask: (taskID) => apiFetch(`/async_tasks/${taskID}`, {
        operationId: "RetrieveAsyncTask",
    }),
    // GET /blocks/{block_id}
    // Retrieve a block
    retrieveABlock: (blockID) => apiFetch(`/blocks/${blockID}`, {
        operationId: "RetrieveABlock",
    }),
    // DELETE /blocks/{block_id}
    // Delete a block
    deleteABlock: (blockID) => apiFetch(`/blocks/${blockID}`, {
        method: "DELETE",
        operationId: "DeleteABlock",
    }),
    // PATCH /blocks/{block_id}
    // Update a block
    updateABlock: (blockID, body) => apiFetch(`/blocks/${blockID}`, {
        method: "PATCH",
        body: JSON.stringify(body),
        operationId: "UpdateABlock",
    }),
    // GET /blocks/{block_id}/children
    // Retrieve block children
    getBlockChildren: (blockID, params = {}) => {
        const q = new URLSearchParams();
        if (params.startCursor != null) q.set("start_cursor", String(params.startCursor));
        if (params.pageSize != null) q.set("page_size", String(params.pageSize));
        return apiFetch(`/blocks/${blockID}/children?${q}`, {
            operationId: "GetBlockChildren",
        });
    },
    // PATCH /blocks/{block_id}/children
    // Append block children
    patchBlockChildren: (blockID, body) => apiFetch(`/blocks/${blockID}/children`, {
        method: "PATCH",
        body: JSON.stringify(body),
        operationId: "PatchBlockChildren",
    }),
    // GET /data_sources/{data_source_id}
    // Retrieve a data source
    retrieveADataSource: (dataSourceID) => apiFetch(`/data_sources/${dataSourceID}`, {
        operationId: "RetrieveADataSource",
    }),
    // PATCH /data_sources/{data_source_id}
    // Update a data source
    updateADataSource: (dataSourceID, body) => apiFetch(`/data_sources/${dataSourceID}`, {
        method: "PATCH",
        body: JSON.stringify(body),
        operationId: "UpdateADataSource",
    }),
    // POST /data_sources/{data_source_id}/query
    // Query a data source
    postDatabaseQuery: (dataSourceID, params = {}, body) => {
        const q = new URLSearchParams();
        for (const v of params.filterProperties ?? []) q.append("filter_properties", String(v));
        return apiFetch(`/data_sources/${dataSourceID}/query?${q}`, {
            method: "POST",
            body: JSON.stringify(body),
            operationId: "PostDatabaseQuery",
        });
    },
    // POST /data_sources
    // Create a data source
    createADatabase: (body) => apiFetch("/data_sources", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateADatabase",
    }),
    // GET /data_sources/{data_source_id}/templates
    // List templates in a data source
    listDataSourceTemplates: (dataSourceID, params = {}) => {
        const q = new URLSearchParams();
        if (params.name != null) q.set("name", String(params.name));
        if (params.startCursor != null) q.set("start_cursor", String(params.startCursor));
        if (params.pageSize != null) q.set("page_size", String(params.pageSize));
        return apiFetch(`/data_sources/${dataSourceID}/templates?${q}`, {
            operationId: "ListDataSourceTemplates",
        });
    },
    // GET /databases/{database_id}
    // Retrieve a database
    retrieveDatabase: (databaseID) => apiFetch(`/databases/${databaseID}`, {
        operationId: "RetrieveDatabase",
    }),
    // PATCH /databases/{database_id}
    // Update a database
    updateDatabase: (databaseID, body) => apiFetch(`/databases/${databaseID}`, {
        method: "PATCH",
        body: JSON.stringify(body),
        operationId: "UpdateDatabase",
    }),
    // POST /databases
    // Create a database
    createDatabase: (body) => apiFetch("/databases", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateDatabase",
    }),
    // POST /search
    // Search by title
    postSearch: (body) => apiFetch("/search", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "PostSearch",
    }),
    // GET /comments
    // List comments
    listComments: (params = {}) => {
        const q = new URLSearchParams();
        if (params.blockID != null) q.set("block_id", String(params.blockID));
        if (params.startCursor != null) q.set("start_cursor", String(params.startCursor));
        if (params.pageSize != null) q.set("page_size", String(params.pageSize));
        return apiFetch(`/comments?${q}`, {
            operationId: "ListComments",
        });
    },
    // POST /comments
    // Create a comment
    createAComment: (body) => apiFetch("/comments", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateAComment",
    }),
    // GET /comments/{comment_id}
    // Retrieve a comment
    retrieveComment: (commentID) => apiFetch(`/comments/${commentID}`, {
        operationId: "RetrieveComment",
    }),
    // DELETE /comments/{comment_id}
    // Delete a comment
    deleteAComment: (commentID) => apiFetch(`/comments/${commentID}`, {
        method: "DELETE",
        operationId: "DeleteAComment",
    }),
    // PATCH /comments/{comment_id}
    // Update a comment
    updateAComment: (commentID, body) => apiFetch(`/comments/${commentID}`, {
        method: "PATCH",
        body: JSON.stringify(body),
        operationId: "UpdateAComment",
    }),
    // GET /file_uploads
    // List file uploads
    listFileUploads: (params = {}) => {
        const q = new URLSearchParams();
        if (params.status != null) q.set("status", String(params.status));
        if (params.startCursor != null) q.set("start_cursor", String(params.startCursor));
        if (params.pageSize != null) q.set("page_size", String(params.pageSize));
        return apiFetch(`/file_uploads?${q}`, {
            operationId: "ListFileUploads",
        });
    },
    // POST /file_uploads
    // Create a file upload
    createFile: (body) => apiFetch("/file_uploads", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateFile",
    }),
    // POST /file_uploads/{file_upload_id}/send
    // Upload a file
    uploadFile: (fileUploadID, body) => apiFetch(`/file_uploads/${fileUploadID}/send`, {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "UploadFile",
    }),
    // POST /file_uploads/{file_upload_id}/complete
    // Complete a multi-part file upload
    completeFileUpload: (fileUploadID) => apiFetch(`/file_uploads/${fileUploadID}/complete`, {
        method: "POST",
        operationId: "CompleteFileUpload",
    }),
    // GET /file_uploads/{file_upload_id}
    // Retrieve a file upload
    retrieveFileUpload: (fileUploadID) => apiFetch(`/file_uploads/${fileUploadID}`, {
        operationId: "RetrieveFileUpload",
    }),
    // GET /custom_emojis
    // List custom emojis
    listCustomEmojis: (params = {}) => {
        const q = new URLSearchParams();
        if (params.startCursor != null) q.set("start_cursor", String(params.startCursor));
        if (params.pageSize != null) q.set("page_size", String(params.pageSize));
        if (params.name != null) q.set("name", String(params.name));
        return apiFetch(`/custom_emojis?${q}`, {
            operationId: "ListCustomEmojis",
        });
    },
    // GET /views
    // List views
    listViews: (params = {}) => {
        const q = new URLSearchParams();
        if (params.databaseID != null) q.set("database_id", String(params.databaseID));
        if (params.dataSourceID != null) q.set("data_source_id", String(params.dataSourceID));
        if (params.startCursor != null) q.set("start_cursor", String(params.startCursor));
        if (params.pageSize != null) q.set("page_size", String(params.pageSize));
        return apiFetch(`/views?${q}`, {
            operationId: "ListViews",
        });
    },
    // POST /views
    // Create a view
    createView: (body) => apiFetch("/views", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateView",
    }),
    // GET /views/{view_id}
    // Retrieve a view
    retrieveAView: (viewID) => apiFetch(`/views/${viewID}`, {
        operationId: "RetrieveAView",
    }),
    // DELETE /views/{view_id}
    // Delete a view
    deleteView: (viewID) => apiFetch(`/views/${viewID}`, {
        method: "DELETE",
        operationId: "DeleteView",
    }),
    // PATCH /views/{view_id}
    // Update a view
    updateAView: (viewID, body) => apiFetch(`/views/${viewID}`, {
        method: "PATCH",
        body: JSON.stringify(body),
        operationId: "UpdateAView",
    }),
    // POST /views/{view_id}/queries
    // Create a view query
    createViewQuery: (viewID, body) => apiFetch(`/views/${viewID}/queries`, {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateViewQuery",
    }),
    // GET /views/{view_id}/queries/{query_id}
    // Get view query results
    getViewQueryResults: (viewID, queryID, params = {}) => {
        const q = new URLSearchParams();
        if (params.startCursor != null) q.set("start_cursor", String(params.startCursor));
        if (params.pageSize != null) q.set("page_size", String(params.pageSize));
        return apiFetch(`/views/${viewID}/queries/${queryID}?${q}`, {
            operationId: "GetViewQueryResults",
        });
    },
    // DELETE /views/{view_id}/queries/{query_id}
    // Delete a view query
    deleteViewQuery: (viewID, queryID) => apiFetch(`/views/${viewID}/queries/${queryID}`, {
        method: "DELETE",
        operationId: "DeleteViewQuery",
    }),
    // POST /blocks/meeting_notes
    // Create a meeting note
    createMeetingNote: (body) => apiFetch("/blocks/meeting_notes", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateMeetingNote",
    }),
    // POST /blocks/meeting_notes/query
    // Query meeting notes
    queryMeetingNotes: (body) => apiFetch("/blocks/meeting_notes/query", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "QueryMeetingNotes",
    }),
    // POST /agents/query
    // Query agents
    queryAgents: (body) => apiFetch("/agents/query", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "QueryAgents",
    }),
    // GET /agents/{agent_id}
    // Get agent
    getAgent: (agentID, params = {}) => {
        const q = new URLSearchParams();
        if (params.verbose != null) q.set("verbose", String(params.verbose));
        return apiFetch(`/agents/${agentID}?${q}`, {
            operationId: "GetAgent",
        });
    },
    // DELETE /agents/{agent_id}
    // Delete agent
    deleteAgent: (agentID) => apiFetch(`/agents/${agentID}`, {
        method: "DELETE",
        operationId: "DeleteAgent",
    }),
    // GET /agents/{agent_id}/insights
    // Get agent insights
    getAgentInsights: (agentID, params = {}) => {
        const q = new URLSearchParams();
        if (params.startTime != null) q.set("start_time", String(params.startTime));
        if (params.endTime != null) q.set("end_time", String(params.endTime));
        return apiFetch(`/agents/${agentID}/insights?${q}`, {
            operationId: "GetAgentInsights",
        });
    },
    // PATCH /agents/{agent_id}/status
    // Update agent status
    updateAgentStatus: (agentID, body) => apiFetch(`/agents/${agentID}/status`, {
        method: "PATCH",
        body: JSON.stringify(body),
        operationId: "UpdateAgentStatus",
    }),
    // PATCH /agents/{agent_id}/credit_limit
    // Update agent credit limit
    updateAgentCreditLimit: (agentID, body) => apiFetch(`/agents/${agentID}/credit_limit`, {
        method: "PATCH",
        body: JSON.stringify(body),
        operationId: "UpdateAgentCreditLimit",
    }),
    // POST /agents/batch
    // Apply many agent operations
    agentBatch: (body) => apiFetch("/agents/batch", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "AgentBatch",
    }),
    // GET /ai/plugins
    // List skills plugins
    listSkillsPlugins: (params = {}) => {
        const q = new URLSearchParams();
        if (params.pageSize != null) q.set("page_size", String(params.pageSize));
        if (params.startCursor != null) q.set("start_cursor", String(params.startCursor));
        return apiFetch(`/ai/plugins?${q}`, {
            operationId: "ListSkillsPlugins",
        });
    },
    // GET /ai/plugins/{id}
    // Get a plugin directory
    getPluginDirectory: (id) => apiFetch(`/ai/plugins/${id}`, {
        operationId: "GetPluginDirectory",
    }),
    // GET /ai/skills/{id}
    // Get a skill directory
    getSkillDirectory: (id) => apiFetch(`/ai/skills/${id}`, {
        operationId: "GetSkillDirectory",
    }),
    // POST /sessions
    // Update a session
    updateSession: (body) => apiFetch("/sessions", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "UpdateSession",
    }),
    // GET /sessions/{session_id}
    // Retrieve a session
    retrieveSession: (sessionID) => apiFetch(`/sessions/${sessionID}`, {
        operationId: "RetrieveSession",
    }),
    // POST /sessions/query
    // Query sessions
    querySessions: (body) => apiFetch("/sessions/query", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "QuerySessions",
    }),
    // POST /sessions/{session_id}/events/query
    // Query session events
    querySessionEvents: (sessionID, body) => apiFetch(`/sessions/${sessionID}/events/query`, {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "QuerySessionEvents",
    }),
    // POST /sessions/{session_id}/cancel
    // Cancel a session
    cancelSession: (sessionID, body) => apiFetch(`/sessions/${sessionID}/cancel`, {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CancelSession",
    }),
    // POST /oauth/token
    // Exchange an authorization code for an access and refresh token
    createAToken: (body) => apiFetch("/oauth/token", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "CreateAToken",
    }),
    // POST /oauth/revoke
    // Revoke a token
    revokeToken: (body) => apiFetch("/oauth/revoke", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "RevokeToken",
    }),
    // POST /oauth/introspect
    // Introspect a token
    introspectToken: (body) => apiFetch("/oauth/introspect", {
        method: "POST",
        body: JSON.stringify(body),
        operationId: "IntrospectToken",
    }),
};
