// This file provides types for the API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package freepublicapis

import (
	"encoding/json/v2"
	"net/url"

	"github.com/MarkRosemaker/jsonutil"
)

var jsonOpts = json.JoinOptions(
	json.RejectUnknownMembers(true),
	json.WithMarshalers(json.JoinMarshalers(
		json.MarshalToFunc(jsonutil.URLMarshal),
	)),
	json.WithUnmarshalers(json.JoinUnmarshalers(
		json.UnmarshalFromFunc(jsonutil.URLUnmarshal),
	)),
)

// GetApiapiByApiidOk defines a model
type GetApiapiByApiidOk struct {
	ID            int     `json:"id"`
	Emoji         string  `json:"emoji"`
	Title         string  `json:"title"`
	Description   string  `json:"description"`
	Documentation url.URL `json:"documentation"`
	Methods       int     `json:"methods"`
	Health        int     `json:"health"`
	Source        url.URL `json:"source"`
}
