// This file provides types for the API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package petapi

import (
	"encoding/json/v2"
)

var jsonOpts = json.JoinOptions(
	json.RejectUnknownMembers(true),
)

// ListPetsParams holds the query parameters for ListPets.
type ListPetsParams struct {
	Limit int
}

// A pet in the store
type Pet struct {
	ID   int    `json:"id,omitzero"`
	Name string `json:"name"`
	Tag  string `json:"tag"`
}

type Status string

const (
	StatusActive   Status = "active"
	StatusInactive Status = "inactive"
)

// Valid indicates whether the value is a known member of the Status enum.
func (e Status) Valid() bool {
	switch e {
	case StatusActive, StatusInactive:
		return true
	default:
		return false
	}
}

type Tags []string
