// This file provides a client with methods as well as functions to interact with the HTTP API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package debug

import (
	"context"
	"encoding/json/v2"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"strings"

	"github.com/MarkRosemaker/openapi-enrich/cassette"
	"github.com/go-api-libs/api"
)

const defaultUserAgent = "Debug"

var defaultBaseURL = &url.URL{
	Scheme: "https",
	Host:   "api.example.com",
	Path:   "/",
}

// Client is an HTTP client for the debug API.
type Client struct {
	// The HTTP client to use for requests.
	cli *http.Client
	// The bearer token
	bearer string
	// The base URL
	baseURL *url.URL
	// The user agent
	userAgent string
	// Enable debug mode
	debug bool
}

// ClientOption configures a [Client].
type ClientOption func(*Client)

// WithBaseURL returns a [ClientOption] that overrides the default base URL.
// It will prefix a leading slash to the path if there is none.
func WithBaseURL(baseURL *url.URL) ClientOption {
	if !strings.HasPrefix(baseURL.Path, "/") {
		baseURL.Path = "/" + baseURL.Path
	}

	return func(c *Client) { c.baseURL = baseURL }
}

// WithHTTPClient returns a [ClientOption] that sets a custom HTTP client.
func WithHTTPClient(cli *http.Client) ClientOption {
	return func(c *Client) { c.cli = cli }
}

// WithBearer returns a [ClientOption] that sets a custom bearer.
func WithBearer(bearer string) ClientOption {
	return func(c *Client) {
		if bearer != "" {
			c.bearer = "Bearer " + strings.TrimPrefix(bearer, "Bearer ")
		}
	}
}

// WithDebug is a [ClientOption] that sets the debug mode to true.
func WithDebug(c *Client) { c.debug = true }

// NewClient creates a new Client, reading the bearer token from [os.Getenv]("DEBUG_TOKEN").
func NewClient(opts ...ClientOption) (*Client, error) {
	c := &Client{
		cli:       http.DefaultClient,
		baseURL:   defaultBaseURL,
		userAgent: defaultUserAgent,
	}

	WithBearer(os.Getenv("DEBUG_TOKEN"))(c)

	for _, opt := range opts {
		opt(c)
	}

	if c.bearer == "" {
		return nil, errors.New("bearer token DEBUG_TOKEN not provided")
	}

	return c, nil
}

// GET /item
func (c *Client) GetItem(ctx context.Context) (*Item, error) {
	return c.GetItemWithResult[Item](ctx)
}

// GET /item
func (c *Client) GetItemWithResult[R any](ctx context.Context) (*R, error) {
	u := c.baseURL.JoinPath("item")
	req := (&http.Request{
		Header: http.Header{
			"Authorization": []string{c.bearer},
			"User-Agent":    []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	var (
		ia  cassette.Interaction
		err error
	)
	if c.debug {
		ia.Request, err = cassette.NewRequest(req)
		if err != nil {
			return nil, fmt.Errorf("recording request: %w", err)
		}
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	if c.debug {
		ia.Response, err = cassette.NewResponse(rsp)
		if err != nil {
			return nil, fmt.Errorf("recording response: %w", err)
		}
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// ok
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R

			// a type of the caller's own declares only what it needs of the response, so it is decoded leniently
			opts := jsonOptsLenient
			if _, ok := any(&out).(*Item); ok {
				opts = jsonOpts
			}

			if err := json.UnmarshalRead(rsp.Body, &out, opts); err != nil {
				if !c.debug {
					return nil, api.WrapDecodingError(rsp, err)
				}

				if err2 := cassette.AddInteraction("api/interactions.json", &ia); err2 != nil {
					return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
				}

				out = *new(R)
				if err := json.Unmarshal(ia.Response.Body, &out, jsonOptsLenient); err != nil {
					return nil, api.WrapDecodingError(rsp, err)
				}
			}

			return &out, nil
		default:
			if c.debug {
				if err := cassette.AddInteraction("api/interactions.json", &ia); err != nil {
					return nil, errors.Join(api.NewErrUnknownContentType(rsp), err)
				}
			}

			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		if c.debug {
			if err := cassette.AddInteraction("api/interactions.json", &ia); err != nil {
				return nil, errors.Join(api.NewErrUnknownStatusCode(rsp), err)
			}
		}

		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// GET /block
func (c *Client) GetBlock(ctx context.Context) (*Block, error) {
	return c.GetBlockWithResult[Block](ctx)
}

// GET /block
func (c *Client) GetBlockWithResult[R any](ctx context.Context) (*R, error) {
	u := c.baseURL.JoinPath("block")
	req := (&http.Request{
		Header: http.Header{
			"Authorization": []string{c.bearer},
			"User-Agent":    []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	var (
		ia  cassette.Interaction
		err error
	)
	if c.debug {
		ia.Request, err = cassette.NewRequest(req)
		if err != nil {
			return nil, fmt.Errorf("recording request: %w", err)
		}
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	if c.debug {
		ia.Response, err = cassette.NewResponse(rsp)
		if err != nil {
			return nil, fmt.Errorf("recording response: %w", err)
		}
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// ok
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R

			// a type of the caller's own declares only what it needs of the response, so it is decoded leniently
			opts := jsonOptsLenient
			if _, ok := any(&out).(*Block); ok {
				opts = jsonOpts
			}

			if err := json.UnmarshalRead(rsp.Body, &out, opts); err != nil {
				if !c.debug {
					return nil, api.WrapDecodingError(rsp, err)
				}

				if err2 := cassette.AddInteraction("api/interactions.json", &ia); err2 != nil {
					return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
				}

				out = *new(R)
				if err := json.Unmarshal(ia.Response.Body, &out, jsonOptsLenient); err != nil {
					return nil, api.WrapDecodingError(rsp, err)
				}
			}

			return &out, nil
		default:
			if c.debug {
				if err := cassette.AddInteraction("api/interactions.json", &ia); err != nil {
					return nil, errors.Join(api.NewErrUnknownContentType(rsp), err)
				}
			}

			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		if c.debug {
			if err := cassette.AddInteraction("api/interactions.json", &ia); err != nil {
				return nil, errors.Join(api.NewErrUnknownStatusCode(rsp), err)
			}
		}

		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// GET /pet
func (c *Client) GetPet(ctx context.Context) (*Pet, error) {
	return c.GetPetWithResult[Pet](ctx)
}

// GET /pet
func (c *Client) GetPetWithResult[R any](ctx context.Context) (*R, error) {
	u := c.baseURL.JoinPath("pet")
	req := (&http.Request{
		Header: http.Header{
			"Authorization": []string{c.bearer},
			"User-Agent":    []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	var (
		ia  cassette.Interaction
		err error
	)
	if c.debug {
		ia.Request, err = cassette.NewRequest(req)
		if err != nil {
			return nil, fmt.Errorf("recording request: %w", err)
		}
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	if c.debug {
		ia.Response, err = cassette.NewResponse(rsp)
		if err != nil {
			return nil, fmt.Errorf("recording response: %w", err)
		}
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// ok
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R

			// a type of the caller's own declares only what it needs of the response, so it is decoded leniently
			opts := jsonOptsLenient
			if _, ok := any(&out).(*Pet); ok {
				opts = jsonOpts
			}

			if err := json.UnmarshalRead(rsp.Body, &out, opts); err != nil {
				if !c.debug {
					return nil, api.WrapDecodingError(rsp, err)
				}

				if err2 := cassette.AddInteraction("api/interactions.json", &ia); err2 != nil {
					return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
				}

				out = *new(R)
				if err := json.Unmarshal(ia.Response.Body, &out, jsonOptsLenient); err != nil {
					return nil, api.WrapDecodingError(rsp, err)
				}
			}

			return &out, nil
		default:
			if c.debug {
				if err := cassette.AddInteraction("api/interactions.json", &ia); err != nil {
					return nil, errors.Join(api.NewErrUnknownContentType(rsp), err)
				}
			}

			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		if c.debug {
			if err := cassette.AddInteraction("api/interactions.json", &ia); err != nil {
				return nil, errors.Join(api.NewErrUnknownStatusCode(rsp), err)
			}
		}

		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}
