// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

/**
 * LSO Trader API Client
 * =========================
 *
 * Matches the OpenAPI specification. All functions are async and return
 * data or `null` on failure.
 *
 * Usage:
 *   import './api.js';        // or <script src="api.js"></script>
 *   const result = await window.API.listAccounts();
 *   const result = await window.API.getPositions(accountID);
 *   const result = await window.API.getCash(accountID);
 *   const result = await window.API.getAccountSummary(accountID);
 *   const result = await window.API.getFundamentals(cik);
 *   const result = await window.API.getCompanyBySymbol(symbol);
 *   const result = await window.API.getIncomeStatement(cik);
 *   const result = await window.API.getBalanceSheet(cik);
 *   const result = await window.API.getWatchlist();
 *   const result = await window.API.getMarketStatus();
 **/

const API_BASE = "http://localhost:8081/api";
const TIMEOUT = 4000;

// ====================== ENVIRONMENT ======================
window.ENV = "production";

// reportApiError broadcasts a failed API call as a "lso:ws-message"
// CustomEvent, the same channel server-pushed notifications use, so a single
// listener can surface both origins uniformly.
function reportApiError(operationId, status, message) {
    window.dispatchEvent(new CustomEvent("lso:ws-message", {
        detail: {
            level: "error",
            persistent: true,
            title: `${operationId} failed`,
            meta: [`Status ${status}`, message],
        },
    }));
}

async function apiFetch(path, options = {}) {
    const {
        method = "GET", operationId = "Request"
    } = options;
    const ctrl = new AbortController();
    const timeoutId = setTimeout(() => ctrl.abort(), TIMEOUT);

    try {
        const res = await fetch(API_BASE + path, {
            ...options,
            signal: ctrl.signal,
                headers: {
                    "Content-Type": "application/json",
                    ...options.headers,
                },
        });

        clearTimeout(timeoutId);

        if (!res.ok) {
            console.warn(`API Error: ${res.status} ${method} ${path}`);
            let message = res.statusText || "Request failed";
            try {
                const body = await res.clone().json();
                message = body?.message || body?.error || message;
            } catch {}
            reportApiError(operationId, res.status, message);
            return null;
        }

        return await res.json();
    } catch (err) {
        clearTimeout(timeoutId);
        if (err.name === "AbortError") {
            console.error(`Request timeout: ${path}`);
            reportApiError(operationId, "timeout", `${path} did not respond in time`);
        } else {
            console.error(`Request failed: ${path}`, err);
            reportApiError(operationId, "network", err.message || "Network error");
        }
        return null;
    }
}

// ====================== PUBLIC API ======================

window.API = {
    // GET /accounts
    // List all brokerage accounts
    listAccounts: () => apiFetch("/accounts", {
        operationId: "ListAccounts",
    }),
    // GET /accounts/{account_id}/positions
    // Get all holdings for an account
    getPositions: (accountID) => apiFetch(`/accounts/${accountID}/positions`, {
        operationId: "GetPositions",
    }),
    // GET /accounts/{account_id}/cash
    // Get cash balances for an account
    getCash: (accountID) => apiFetch(`/accounts/${accountID}/cash`, {
        operationId: "GetCash",
    }),
    // GET /accounts/{account_id}/summary
    // Get a combined view of positions and cash for an account
    getAccountSummary: (accountID) => apiFetch(`/accounts/${accountID}/summary`, {
        operationId: "GetAccountSummary",
    }),
    // GET /fundamentals/{cik}
    // Get fundamentals analysis for a company
    getFundamentals: (cik) => apiFetch(`/fundamentals/${cik}`, {
        operationId: "GetFundamentals",
    }),
    // GET /fundamentals/{symbol}/company
    // Get company info for a ticker
    getCompanyBySymbol: (symbol) => apiFetch(`/fundamentals/${symbol}/company`, {
        operationId: "GetCompanyBySymbol",
    }),
    // GET /fundamentals/{cik}/income-statement
    // Get income statement data and chart series
    getIncomeStatement: (cik) => apiFetch(`/fundamentals/${cik}/income-statement`, {
        operationId: "GetIncomeStatement",
    }),
    // GET /fundamentals/{cik}/balance-sheet
    // Get balance sheet data and chart series
    getBalanceSheet: (cik) => apiFetch(`/fundamentals/${cik}/balance-sheet`, {
        operationId: "GetBalanceSheet",
    }),
    // GET /watchlist
    // Get the default watchlist symbols
    getWatchlist: () => apiFetch("/watchlist", {
        operationId: "GetWatchlist",
    }),
    // GET /market/status
    // Get current market status and key dates
    getMarketStatus: () => apiFetch("/market/status", {
        operationId: "GetMarketStatus",
    }),
};
