// This file provides types for the API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package lso

import (
	"encoding/json/v2"
	"net/url"
	"time"

	"cloud.google.com/go/civil"
	"github.com/MarkRosemaker/jsonutil"
)

var jsonOpts = json.JoinOptions(
	json.RejectUnknownMembers(true),
	json.WithMarshalers(json.JoinMarshalers(
		json.MarshalToFunc(jsonutil.URLMarshal),
	)),
	json.WithUnmarshalers(json.JoinUnmarshalers(
		json.UnmarshalFromFunc(jsonutil.URLUnmarshal),
	)),
)

// Account defines a model
type Account struct {
	// IBKR account identifier
	AccountID   string             `json:"account_id,omitzero"`
	DisplayName string             `json:"display_name,omitzero"`
	AccountType AccountAccountType `json:"account_type,omitzero"`
	CreatedAt   time.Time          `json:"created_at,omitzero"`
}

// AccountAccountType defines a model
type AccountAccountType string

const (
	AccountAccountTypeIndividual AccountAccountType = "INDIVIDUAL"
	AccountAccountTypeCompany    AccountAccountType = "COMPANY"
)

// Valid indicates whether the value is a known member of the AccountAccountType enum.
func (e AccountAccountType) Valid() bool {
	switch e {
	case AccountAccountTypeIndividual, AccountAccountTypeCompany:
		return true
	default:
		return false
	}
}

// AccountSummary defines a model
type AccountSummary struct {
	Account  Account  `json:"account"`
	Stocks   Stocks   `json:"stocks,omitzero"`
	Options  Options  `json:"options,omitzero"`
	Balances Balances `json:"balances,omitzero"`
}

// Accounts defines a model
type Accounts []Account

// BalanceSheetAnalysis defines a model
type BalanceSheetAnalysis struct {
	Leverage BandResult                 `json:"leverage"`
	Series   BalanceSheetAnalysisSeries `json:"series"`
}

// BalanceSheetAnalysisSeries defines a model
type BalanceSheetAnalysisSeries struct {
	CurrentAssets      ChartSeries `json:"current_assets"`
	CurrentLiabilities ChartSeries `json:"current_liabilities"`
	Leverage           ChartSeries `json:"leverage"`
}

// Balances defines a model
type Balances []CashBalance

// BandResult defines a model
type BandResult struct {
	Value float64 `json:"value"`
	// Human-readable value (e.g. '23.5%', '1.82')
	Formatted string `json:"formatted,omitzero"`
	// Band label (e.g. 'OK', 'red flag', 'solid', 'very strong')
	Label string `json:"label,omitzero"`
	// Whether the value is within acceptable range
	Passing bool `json:"passing,omitzero"`
}

// CashBalance defines a model
type CashBalance struct {
	Currency Currency `json:"currency,omitzero"`
	// Settled cash balance
	Cash float64 `json:"cash"`
}

// ChartSeries defines a model
type ChartSeries struct {
	Label  string            `json:"label,omitzero"`
	Points ChartSeriesPoints `json:"points,omitzero"`
}

// ChartSeriesPoints defines a model
type ChartSeriesPoints []DataPoint

// Company defines a model
type Company struct {
	// SEC Central Index Key
	Cik int `json:"cik,omitzero"`
	// The name of the company
	Name string `json:"name,omitzero"`
	// A long summary of the company
	Summary           string  `json:"summary,omitzero"`
	Sector            string  `json:"sector,omitzero"`
	Industry          string  `json:"industry,omitzero"`
	Website           url.URL `json:"website,omitzero"`
	FullTimeEmployees int     `json:"full_time_employees,omitzero"`
}

// CompanyAndSecurity defines a model
type CompanyAndSecurity struct {
	Company  Company  `json:"company"`
	Security Security `json:"security"`
}

// Currency defines a model
type Currency string

const (
	CurrencyUSD Currency = "USD"
	CurrencyEUR Currency = "EUR"
)

// Valid indicates whether the value is a known member of the Currency enum.
func (e Currency) Valid() bool {
	switch e {
	case CurrencyUSD, CurrencyEUR:
		return true
	default:
		return false
	}
}

// DataPoint defines a model
type DataPoint struct {
	// X-axis value (date)
	Date civil.Date `json:"date,omitzero"`
	// Y-axis value
	Value float64 `json:"value"`
}

// Error defines a model
type Error struct {
	Code    int    `json:"code,omitzero"`
	Message string `json:"message,omitzero"`
}

// FundamentalsAnalysis defines a model
type FundamentalsAnalysis struct {
	Company         Company                 `json:"company"`
	IncomeStatement IncomeStatementAnalysis `json:"income_statement"`
	BalanceSheet    BalanceSheetAnalysis    `json:"balance_sheet"`
	// Red-flag warnings (e.g. low profit margin, high leverage)
	Warnings []string `json:"warnings,omitempty"`
}

// GetCashResult defines a model
type GetCashResult struct {
	Balances Balances  `json:"balances,omitzero"`
	AsOf     time.Time `json:"as_of,omitzero"`
}

// Twelve months summary of the income statement
type IncomeStatement struct {
	TotalRevenue    float64 `json:"total_revenue"`
	OperatingIncome float64 `json:"operating_income"`
}

// IncomeStatementAnalysis defines a model
type IncomeStatementAnalysis struct {
	// Twelve months summary of the income statement
	Ttm          IncomeStatement               `json:"ttm"`
	ProfitMargin BandResult                    `json:"profit_margin"`
	Series       IncomeStatementAnalysisSeries `json:"series"`
}

// IncomeStatementAnalysisSeries defines a model
type IncomeStatementAnalysisSeries struct {
	Revenue      ChartSeries `json:"revenue"`
	GrossProfit  ChartSeries `json:"gross_profit"`
	ProfitMargin ChartSeries `json:"profit_margin"`
	Eps          ChartSeries `json:"eps"`
}

// ListAccountsResult defines a model
type ListAccountsResult struct {
	Accounts Accounts `json:"accounts,omitzero"`
	// When the cached data was last refreshed from the broker
	AsOf time.Time `json:"as_of,omitzero"`
}

// MarketStatus defines a model
type MarketStatus struct {
	// Current NYSE-local date
	Today civil.Date `json:"today,omitzero"`
	// Whether today is a trading day (weekday + not NYSE holiday)
	IsTradingDay bool `json:"is_trading_day,omitzero"`
	// Next Friday for weekly options expiry
	NextFriday civil.Date `json:"next_friday,omitzero"`
}

// Option defines a model
type Option struct {
	// Put or Call
	Type OptionType `json:"type,omitzero"`
	// Underlying stock ticker
	Underlying string `json:"underlying,omitzero"`
	// Option expiration date
	Expiry civil.Date `json:"expiry,omitzero"`
	// Calendar days until expiration
	DaysToExpiry int `json:"days_to_expiry,omitzero"`
	// Strike price
	Strike float64 `json:"strike"`
	// Number of contracts (negative = short)
	Qty int `json:"qty,omitzero"`
}

// Put or Call
type OptionType string

const (
	OptionTypeP OptionType = "P"
	OptionTypeC OptionType = "C"
)

// Valid indicates whether the value is a known member of the OptionType enum.
func (e OptionType) Valid() bool {
	switch e {
	case OptionTypeP, OptionTypeC:
		return true
	default:
		return false
	}
}

// Options defines a model
type Options []Option

// Positions defines a model
type Positions struct {
	Stocks  Stocks    `json:"stocks,omitzero"`
	Options Options   `json:"options,omitzero"`
	AsOf    time.Time `json:"as_of,omitzero"`
}

// Security defines a model
type Security struct {
	Symbol string `json:"symbol,omitzero"`
	// The type of security (e.g. EQUITY, ETF)
	Type           SecurityType `json:"type,omitzero"`
	FirstTradeDate civil.Date   `json:"first_trade_date,omitzero"`
}

// The type of security (e.g. EQUITY, ETF)
type SecurityType string

const (
	SecurityTypeEquity SecurityType = "EQUITY"
	SecurityTypeETF    SecurityType = "ETF"
)

// Valid indicates whether the value is a known member of the SecurityType enum.
func (e SecurityType) Valid() bool {
	switch e {
	case SecurityTypeEquity, SecurityTypeETF:
		return true
	default:
		return false
	}
}

// Stock defines a model
type Stock struct {
	Symbol string `json:"symbol,omitzero"`
	// Number of shares held
	Qty int `json:"qty,omitzero"`
	// Average cost per share
	CostBasis *float64 `json:"cost_basis,omitempty"`
	// Current market price per share (if available from broker)
	MarketPrice *float64 `json:"market_price,omitempty"`
}

// Stocks defines a model
type Stocks []Stock

// Watchlist defines a model
type Watchlist struct {
	Symbols []string `json:"symbols,omitzero"`
}
