// This file provides a client with methods as well as functions to interact with the HTTP API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package notion

import (
	"context"
	"encoding/json/v2"
	"errors"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"strings"

	"github.com/go-api-libs/api"
)

const defaultUserAgent = "API"

var defaultBaseURL = &url.URL{
	Scheme: "https",
	Host:   "api.notion.com",
	Path:   "/v1",
}

// Client is an HTTP client for the notion API.
type Client struct {
	// The HTTP client to use for requests.
	cli *http.Client
	// The bearer token
	bearer string
	// The base URL
	baseURL *url.URL
	// The user agent
	userAgent string
}

// ClientOption configures a [Client].
type ClientOption func(*Client)

// WithBaseURL returns a [ClientOption] that overrides the default base URL.
// It will prefix a leading slash to the path if there is none.
func WithBaseURL(baseURL *url.URL) ClientOption {
	if !strings.HasPrefix(baseURL.Path, "/") {
		baseURL.Path = "/" + baseURL.Path
	}

	return func(c *Client) { c.baseURL = baseURL }
}

// WithHTTPClient returns a [ClientOption] that sets a custom HTTP client.
func WithHTTPClient(cli *http.Client) ClientOption {
	return func(c *Client) { c.cli = cli }
}

// WithBearer returns a [ClientOption] that sets a custom bearer.
func WithBearer(bearer string) ClientOption {
	return func(c *Client) {
		if bearer != "" {
			c.bearer = "Bearer " + strings.TrimPrefix(bearer, "Bearer ")
		}
	}
}

// NewClient creates a new Client, reading the bearer token from [os.Getenv]("API_TOKEN").
func NewClient(opts ...ClientOption) (*Client, error) {
	c := &Client{
		cli:       http.DefaultClient,
		baseURL:   defaultBaseURL,
		userAgent: defaultUserAgent,
	}

	WithBearer(os.Getenv("API_TOKEN"))(c)

	for _, opt := range opts {
		opt(c)
	}

	if c.bearer == "" {
		return nil, errors.New("bearer token API_TOKEN not provided")
	}

	return c, nil
}

// GET /pages/{pageId}
func (c *Client) GetV1PageByPageID(ctx context.Context, pageID string) (*GetV1PageByPageIDOkJSONResponse, error) {
	return c.GetV1PageByPageIDWithResult[GetV1PageByPageIDOkJSONResponse](ctx, pageID)
}

// GET /pages/{pageId}
func (c *Client) GetV1PageByPageIDWithResult[R any](ctx context.Context, pageID string) (*R, error) {
	u := c.baseURL.JoinPath("pages", pageID)
	req := (&http.Request{
		Header: http.Header{
			"Authorization":  []string{c.bearer},
			"Notion-Version": []string{"2026-03-11"},
			"User-Agent":     []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// OK
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// GET /blocks/{blockId}/children
func (c *Client) ListV1BlockChildren(ctx context.Context, blockID string, params *ListV1BlockChildrenParams) (*ListV1BlockChildrenOkJSONResponse, error) {
	return c.ListV1BlockChildrenWithResult[ListV1BlockChildrenOkJSONResponse](ctx, blockID, params)
}

// GET /blocks/{blockId}/children
func (c *Client) ListV1BlockChildrenWithResult[R any](ctx context.Context, blockID string, params *ListV1BlockChildrenParams) (*R, error) {
	u := c.baseURL.JoinPath("blocks", blockID, "children")
	if params != nil {
		q := make(url.Values, 1)

		if params.PageSize != 0 {
			q["page_size"] = []string{strconv.Itoa(params.PageSize)}
		}

		u.RawQuery = q.Encode()
	}

	req := (&http.Request{
		Header: http.Header{
			"Authorization":  []string{c.bearer},
			"Notion-Version": []string{"2026-03-11"},
			"User-Agent":     []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// OK
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}
