// This file provides types for the API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package notion

import (
	"encoding/json/v2"
	"net/url"
	"time"

	"github.com/MarkRosemaker/jsonutil"
	"github.com/google/uuid"
)

var jsonOpts = json.JoinOptions(
	json.RejectUnknownMembers(true),
	json.WithMarshalers(json.JoinMarshalers(
		json.MarshalToFunc(jsonutil.URLMarshal),
	)),
	json.WithUnmarshalers(json.JoinUnmarshalers(
		json.UnmarshalFromFunc(jsonutil.URLUnmarshal),
	)),
)

// ListV1BlockChildrenParams holds the query parameters for ListV1BlockChildren.
type ListV1BlockChildrenParams struct {
	PageSize int
}

// GetV1PageByPageIDOk defines a model
type GetV1PageByPageIDOk struct {
	Object         string                        `json:"object,omitzero"`
	ID             uuid.UUID                     `json:"id,omitzero"`
	CreatedTime    time.Time                     `json:"created_time,omitzero"`
	LastEditedTime time.Time                     `json:"last_edited_time,omitzero"`
	CreatedBy      PageByPageIDCreatedBy         `json:"created_by"`
	LastEditedBy   PageByPageIDCreatedBy         `json:"last_edited_by"`
	Cover          GetV1PageByPageIDOkCover      `json:"cover"`
	Icon           GetV1PageByPageIDOkIcon       `json:"icon"`
	Parent         PageByPageIDParent            `json:"parent"`
	InTrash        bool                          `json:"in_trash"`
	IsArchived     bool                          `json:"is_archived"`
	IsLocked       bool                          `json:"is_locked"`
	Properties     GetV1PageByPageIDOkProperties `json:"properties"`
	URL            url.URL                       `json:"url,omitzero"`
	PublicURL      url.URL                       `json:"public_url,omitzero"`
	RequestID      uuid.UUID                     `json:"request_id,omitzero"`
}

// GetV1PageByPageIDOkCover defines a model
type GetV1PageByPageIDOkCover struct {
	Type     string                           `json:"type,omitzero"`
	External GetV1PageByPageIDOkCoverExternal `json:"external"`
}

// GetV1PageByPageIDOkCoverExternal defines a model
type GetV1PageByPageIDOkCoverExternal struct {
	URL url.URL `json:"url,omitzero"`
}

// GetV1PageByPageIDOkIcon defines a model
type GetV1PageByPageIDOkIcon struct {
	Type  string `json:"type,omitzero"`
	Emoji string `json:"emoji,omitzero"`
}

// GetV1PageByPageIDOkProperties defines a model
type GetV1PageByPageIDOkProperties struct {
	Title GetV1PageByPageIDOkPropertiesTitle `json:"title"`
}

// GetV1PageByPageIDOkPropertiesTitle defines a model
type GetV1PageByPageIDOkPropertiesTitle struct {
	ID    string                      `json:"id,omitzero"`
	Type  string                      `json:"type,omitzero"`
	Title PageByPageIDPropertiesTitle `json:"title"`
}

// ListV1BlockChildrenOk defines a model
type ListV1BlockChildrenOk struct {
	Object     string                       `json:"object,omitzero"`
	Results    ListV1BlockChildrenOkResults `json:"results"`
	NextCursor uuid.UUID                    `json:"next_cursor,omitzero"`
	HasMore    bool                         `json:"has_more"`
	Type       string                       `json:"type,omitzero"`
	Block      struct{}                     `json:"block"`
	RequestID  uuid.UUID                    `json:"request_id,omitzero"`
}

// ListV1BlockChildrenOkResults defines a model
type ListV1BlockChildrenOkResults []ListV1BlockChildrenOkResultsItem

// ListV1BlockChildrenOkResultsItem defines a model
type ListV1BlockChildrenOkResultsItem struct {
	Object         string                                    `json:"object,omitzero"`
	ID             uuid.UUID                                 `json:"id,omitzero"`
	Parent         PageByPageIDParent                        `json:"parent"`
	CreatedTime    time.Time                                 `json:"created_time,omitzero"`
	LastEditedTime time.Time                                 `json:"last_edited_time,omitzero"`
	CreatedBy      PageByPageIDCreatedBy                     `json:"created_by"`
	LastEditedBy   PageByPageIDCreatedBy                     `json:"last_edited_by"`
	HasChildren    bool                                      `json:"has_children"`
	InTrash        bool                                      `json:"in_trash"`
	Type           string                                    `json:"type,omitzero"`
	Paragraph      ListV1BlockChildrenOkResultsItemParagraph `json:"paragraph"`
}

// ListV1BlockChildrenOkResultsItemParagraph defines a model
type ListV1BlockChildrenOkResultsItemParagraph struct {
	RichText PageByPageIDPropertiesTitle `json:"rich_text"`
	Icon     struct{}                    `json:"icon"`
	Color    string                      `json:"color,omitzero"`
}

// PageByPageIDCreatedBy defines a model
type PageByPageIDCreatedBy struct {
	Object string    `json:"object,omitzero"`
	ID     uuid.UUID `json:"id,omitzero"`
}

// PageByPageIDParent defines a model
type PageByPageIDParent struct {
	Type   string    `json:"type,omitzero"`
	PageID uuid.UUID `json:"page_id,omitzero"`
}

// PageByPageIDPropertiesTitle defines a model
type PageByPageIDPropertiesTitle []PageByPageIDPropertiesTitleItem

// PageByPageIDPropertiesTitleItem defines a model
type PageByPageIDPropertiesTitleItem struct {
	Type        string                                     `json:"type,omitzero"`
	Text        PageByPageIDPropertiesTitleItemText        `json:"text"`
	Annotations PageByPageIDPropertiesTitleItemAnnotations `json:"annotations"`
	PlainText   string                                     `json:"plain_text,omitzero"`
	Href        struct{}                                   `json:"href"`
}

// PageByPageIDPropertiesTitleItemAnnotations defines a model
type PageByPageIDPropertiesTitleItemAnnotations struct {
	Bold          bool   `json:"bold"`
	Italic        bool   `json:"italic"`
	Strikethrough bool   `json:"strikethrough"`
	Underline     bool   `json:"underline"`
	Code          bool   `json:"code"`
	Color         string `json:"color,omitzero"`
}

// PageByPageIDPropertiesTitleItemText defines a model
type PageByPageIDPropertiesTitleItemText struct {
	Content string   `json:"content,omitzero"`
	Link    struct{} `json:"link"`
}
